#!/usr/bin/env bash
MODIFIED_CONFIG=~/.config/termite/config

mkdir -p ~/.config/termite
cp $DOTFILES/termite/config $MODIFIED_CONFIG

# set background prevents another color from flashing when spawning a new term
background_color=$(xrdb -query | grep background | awk '{print $2}')
fontname=$(xrdb -query | grep facename | awk '{$1=""; print $0}')
fontsize=$(xrdb -query | grep fontsize | awk '{print $2}')

cat >> $MODIFIED_CONFIG<<EOF

[colors]
background = $background_color

[options]
font = $fontname $fontsize
EOF

for pid in $(pgrep -u "$(whoami)" -x termite); do
    /usr/bin/kill -s SIGUSR1 "$pid"
    pts=$(ps --ppid "$pid" | grep zsh | awk '{print $2}')
    if [[ $pts == pts* ]]; then
        echo -n $(sh ~/.base16_theme) > /dev/$pts
    fi
done
