#!/usr/bin/env sh
set -e

MODIFIED_CONFIG=~/.config/termite/config

mkdir -p ~/.config/termite
cp "$DOTFILES/termite/config" "$MODIFIED_CONFIG"

# set background prevents another color from flashing when spawning a new term
background_color="$(xrdb -query | grep background | awk '{print $2}')"
fontname="$(xrdb -query | grep facename | awk '{$1=""; print $0}')"
fontsize="$(xrdb -query | grep fontsize | awk '{print $2}')"

cat >> "$MODIFIED_CONFIG"<<EOF

[colors]
background = $background_color

[options]
font = $fontname $fontsize
EOF

reload_zsh() {
    zsh_tty="$(ps hotty "$zsh_pid")"
    if [ "$(echo "$zsh_tty" | cut -c1-3)" = 'pts' ]; then
        printf '%s' "$(sh ~/.base16_theme)" > "/dev/$zsh_tty"
    fi
}

reload_termite() {
    /usr/bin/kill -s SIGUSR1 "$termite_pid"
    for zsh_pid in $(pgrep -u "$(whoami)" -x zsh -P "$termite_pid"); do
        reload_zsh > /dev/null 2>&1 || true
    done
}

for termite_pid in $(pgrep -u "$(whoami)" -x termite); do
    reload_termite > /dev/null 2>&1 || true
done
