#!/usr/bin/env bash
shlex() {
    python -c "
import shlex
import sys

parts = [
    shlex.quote(s)
    for s in sys.argv[1:]
]
print(' '.join(parts))
" "$@"
}

set -e
echo -n Password:
read -rs sudopassword
echo
SERVER="$1"
shift
echo "$sudopassword" | ssh "$SERVER" "sudo -Sk \"-p$(echo -e \\b)\" "$(shlex "$@")""
