#!/usr/bin/env sh
set -ex

adb root

# enable tethering
adb shell settings put global tether_dun_required 0

# disables the annoying wifi "no internet" check
adb shell settings put global captive_portal_mode 0

# disable direct sharing
adb shell 'cat > /data/system/ifw/disable_direct_share.xml' <<EOF
<rules>
    <service block="true" log="true">
        <intent-filter>
            <action name="android.service.chooser.ChooserTargetService" />
        </intent-filter>
    </service>
</rules>
EOF

adb unroot
