#!/bin/sh

NAME=$1

if [[ -z $NAME ]]; then
    # compact is broken...
    # avdmanager list avd -c
    NAME=$(avdmanager list avd | grep '^    Name:'  | awk '{print $2}' | head -n 1)
fi

cd $ANDROID_HOME/emulator
export ANDROID_EMULATOR_USE_SYSTEM_LIBS=1
emulator -avd $NAME
