#!/usr/bin/env bash
export CFLAGS='-O2'
if [ "$1" = 'install' ]; then
    if [[ "$OSTYPE" == darwin* ]]; then
        prefix="$(brew --prefix openssl)"

        export CONFIGURE_OPTS="--with-openssl=${prefix}"

        export CFLAGS="-I${prefix}/include ${CFLAGS}"
        export CPPFLAGS="-I${prefix}/include ${CPPFLAGS}"
        export LDFLAGS="-L${prefix}/lib ${LDFLAGS}"
    fi
fi
exec "$(which -a "${0##*/}" | grep -m 1 -v "^$0$")" "$@"
