#!/usr/bin/env sh
set -e
# doesn't work with all compose files, but good enough for me
NETWORK="$(basename "$(pwd)")"_default
if [ -n "$(docker network ls -q -f "name=$NETWORK")" ]; then
    exec docker-shell --network "$NETWORK" "$@"
else
    exec docker-shell "$@"
fi
