#!/usr/bin/env sh
set -e
#PGDATA="${PGDATA:-$HOME/.pgdata}"
#mkdir -p "${PGDATA}"
#-e PGDATA=/data \
#-v "${PGDATA}":/data \
exec podman run \
    --rm \
    -it \
    -e POSTGRES_HOST_AUTH_METHOD=trust \
    -e POSTGRES_PASSWORD= \
    -p 5432:5432 \
    docker.io/postgres:alpine
