#!/usr/bin/env sh
set -e

show_help() {
    cat << EOF
usage nvim-repl: [-f FILE] COMMAND

    -f FILE     file to use. defaults to a temporary file.
EOF
}

arg_error() {
    show_help >&2
    if [ -n "$*" ]; then
        printf '\nerror: %s\n' "$*" >&2
    fi
    exit 1
}

determine_filetype() {
    case "$1" in
        python*)
            printf '%s' python
            ;;
        dash|bash)
            printf '%s' sh
            ;;
        *)
            printf '%s' "$1"
            ;;
    esac
}

NVIM_COMMAND=REPL
WORKFILE=
while true; do
    case "$1" in
        -i|--instant)
            NVIM_COMMAND=REPLInstant
            shift
            ;;
        -f)
            shift
            if [ $# -eq 0 ]; then
                arg_error missing FILE argument
            fi
            WORKFILE="$1"
            shift
            ;;
        *)
            if [ $# -eq 0 ]; then
                arg_error missing COMMAND
            elif [ $# -gt 1 ]; then
                arg_error unknown arguments
            else
                COMMAND="$1"
            fi
            break
    esac
done

FILETYPE="$(determine_filetype "$COMMAND")"
if [ -z "$WORKFILE" ]; then
    WORKFILE="${TMPDIR:-/tmp}/nvim-repl-${FILETYPE}"
fi

exec nvim "$WORKFILE" -c "set filetype=$FILETYPE | $NVIM_COMMAND '$COMMAND'"
