#!/usr/bin/env sh
set -e

update_venv() {
    VENV=~/.config/nvim/python3_env
    export PIP_USER=0
    if ! [ -d "$VENV" ]; then
        python -m venv "$VENV"
    fi
    . "$VENV/bin/activate"
    pip install --quiet --upgrade pynvim $(pip freeze --all | cut -d = -f 1)
}

if [ ! -f ~/.config/nvim/autoload/plug.vim ]; then
    echo Installing plugin manager environment ...
    curl --compressed -fLo ~/.config/nvim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

echo Updating python environment ...
(update_venv)

echo Updating plugins ...
nvim -c 'PlugUpgrade | PlugUpdate! | PlugClean!' -c 'qa'
