#!/usr/bin/env sh
set -e

while true; do
    case "$1" in
        -s)
            FILETYPE="$2"
            shift
            shift
            ;;
        *)
            break
    esac
done

COMMAND="$1"

if [ -z "$COMMAND" ]; then
    cat >&2 << EOF
usage nvim-repl: COMMAND [FILE]
EOF
    exit 1
fi

if [ -n "$2" ]; then
    WORKFILE="$2"
else
    WORKFILE="$(mktemp)"
    cleanup() {
        rm -f "$WORKFILE"
    }
    trap cleanup EXIT
fi

if [ -z "$FILETYPE" ]; then
    FILETYPE="$COMMAND"
fi

nvim "$WORKFILE" -c "set ft=$FILETYPE | REPL '$COMMAND'"
