#!/usr/bin/env sh
set -e

MAGENTA='\033[1;35m'
RESET='\033[0m'

VENV=~/.config/nvim/python3_env

log() {
    echo ${MAGENTA}$@${RESET}
}

if [ ! -f ~/.config/nvim/autoload/plug.vim ]; then
    log Installing plugin manager environment ...
    curl --compressed -fLo ~/.config/nvim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

log Updating python environment ...
virtualenv --quiet "$VENV"
PIP_USER=0 "$VENV/bin/pip" install --quiet --upgrade pynvim

log Updating plugins ...
nvim -c 'PlugUpgrade | PlugUpdate! | PlugClean!' -c 'qa'
