#!/usr/bin/env sh
set -e

MAGENTA='\033[1;35m'
RESET='\033[0m'

log() {
    echo ${MAGENTA}$@${RESET}
}

if [ ! -f ~/.config/nvim/autoload/plug.vim ]; then
    log Installing plugin manager environment ...
    curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

log Updating pipns environment ...
pipns -n pynvim install pynvim > /dev/null 2>&1
pipns -n pynvim update > /dev/null 2>&1
mkdir -p ~/.config/nvim/plugged
venv="$(pipns -n pynvim run pipenv --venv)"
ln -sf "${venv}/bin/python" ~/.config/nvim/plugged/python

log Updating plugins ...
nvim -c 'PlugUpgrade | PlugUpdate! | PlugClean!' -c 'qa'
