#!/usr/bin/env sh
set -e

show_help() {
    cat >&2 << EOF
usage nvim-repl: COMMAND [FILE]
EOF
}


while true; do
    case "$1" in
        -s)
            FILETYPE="$2"
            shift
            shift
            ;;
        *)
            if [ $# -eq 0 ]; then
                show_help >&2
                exit 1
            fi
            COMMAND="$1"
            if [ -n "$2" ]; then
                WORKFILE="$2"
            else
                WORKFILE="$(mktemp)"
                cleanup() {
                    rm -f "$WORKFILE"
                }
                trap cleanup EXIT
            fi
            break
    esac
done

if [ -z "$FILETYPE" ]; then
    FILETYPE="$COMMAND"
fi

nvim "$WORKFILE" -c "set ft=$FILETYPE | REPL '$COMMAND'"
