#!/usr/bin/env python
import argparse
import subprocess
import tempfile


def build_png(label, path):
    subprocess.run([
        'magick',
        '-gravity', 'center',
        '+antialias',
        '-background', 'white',
        '-size', 'x76',
        '-font', 'DejaVu-Sans'
        f'label:{label}',
        '-trim',
        '+repage',
        '-gravity', 'center',
        '-extent', 'x68',
        '-background', 'white',
        '-gravity', 'south',
        '-splice', '0x8', str(path)],
                   check=True)


def print_png(path):
    subprocess.run(['ptouch-print', '--writepng', path], check=True)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('label')
    args = parser.parse_args()

    with tempfile.NamedTemporaryFile(suffix='.png') as tmp:
        build_png(args.label, tmp.name)
        print_png(tmp.name)


if __name__ == '__main__':
    main()
