#!/usr/bin/env python3
import argparse
import pathlib



ATTRIBUTE_MAP = {
    'color00': 'color0',
    'color01': 'color1',
    'color02': 'color2',
    'color03': 'color3',
    'color04': 'color4',
    'color05': 'color5',
    'color06': 'color6',
    'color07': 'color7',
    'color08': 'color8',
    'color09': 'color9',
    'color10': 'color10',
    'color11': 'color11',
    'color12': 'color12',
    'color13': 'color13',
    'color14': 'color14',
    'color15': 'color15',
    'color16': 'color16',
    'color17': 'color17',
    'color18': 'color18',
    'color19': 'color19',
    'color20': 'color20',
    'color21': 'color21',
    'color_background': 'background',
    'color_foreground': 'foreground'
}


def base16_xresources(path):
    attributes = {}
    for line in path.read_text().split('\n'):
        line = line.strip()
        if not line.startswith('color'):
            continue

        attribute, remaining = line.split('=')

        color = remaining.split()[0]
        for char in ('"', '$', '/'):
            color = color.replace(char, '')

        if color.startswith('color'):
            color = attributes[color]
        else:
            attributes[attribute] = color
    return attributes


def main():
    parser = argparse.ArgumentParser('base16-xresources')
    parser.add_argument(
        '--theme',
        metavar='FILE',
        type=pathlib.Path,
        default=pathlib.Path('~/.base16_theme').expanduser(),
        help='(default: ~/.base16_theme)'
    )
    args = parser.parse_args()
    attributes = base16_xresources(args.theme)
    print(
        '\n'.join(
            f'*{ATTRIBUTE_MAP[attribute]} : #{color}'
            for attribute, color in attributes.items()
        )
    )


if __name__ == '__main__':
    main()
