#!/usr/bin/env python3
import argparse
import pathlib


ATTRIBUTE_MAP = {
    'color00': 'color_00',
    'color01': 'color_01',
    'color02': 'color_02',
    'color03': 'color_03',
    'color04': 'color_04',
    'color05': 'color_05',
    'color06': 'color_06',
    'color07': 'color_07',
    'color08': 'color_08',
    'color09': 'color_09',
    'color10': 'color_10',
    'color11': 'color_11',
    'color12': 'color_12',
    'color13': 'color_13',
    'color14': 'color_14',
    'color15': 'color_15',
    'color16': 'color_16',
    'color17': 'color_17',
    'color18': 'color_18',
    'color19': 'color_19',
    'color20': 'color_20',
    'color21': 'color_21',
    'color_background': 'color_bg',
    'color_foreground': 'color_fg'
}


def base16_xresources(path):
    attributes = {}
    for line in path.read_text().split('\n'):
        line = line.strip()
        if not line.startswith('color'):
            continue

        attribute, remaining = line.split('=')

        color = remaining.split()[0]
        for char in ('"', '$', '/'):
            color = color.replace(char, '')

        color = attributes.get(color, color)
        attributes[attribute] = color
    return attributes


def main():
    parser = argparse.ArgumentParser('base16-xresources')
    default = '~/.base16_theme'
    parser.add_argument(
        '--theme',
        metavar='FILE',
        type=pathlib.Path,
        default=pathlib.Path(default).expanduser(),
        help=f'(default: {default})'
    )
    args = parser.parse_args()
    attributes = base16_xresources(args.theme)
    print(
        '\n'.join(
            f'set ${ATTRIBUTE_MAP[attribute]} #{color}'
            for attribute, color in attributes.items()
        )
    )


if __name__ == '__main__':
    main()
