#!/usr/bin/env zsh
set -ex

cd "$(dirname "$0")/../.."

link_file() {
    source_path="$PWD/$1"
    target_path="$2"
    echo -e "\033[1;33mLinking $1 \033[0m"
    if ! [ -e "$source_path" ]; then
        echo error: path $source_path does not exist. >&2
        exit 1
    fi
    rm -rf "$target_path"
    ln -sf "$source_path" "$target_path"
}

zsh_command() {
    echo -e "\033[1;33mNow running $@ \033[0m..."
    "$@"
}

mkdir -p ~/.config

link_file git ~/.config/git
link_file nvim ~/.config/nvim
link_file lf ~/.config/lf
link_file tmux/.tmux.conf ~/.tmux.conf
link_file zsh/.zshenv ~/.zshenv
link_file zsh/.zshrc ~/.zshrc

. ~/.zshenv
. ~/.zshrc

osname=$(uname)
if [[ $osname == Darwin* ]]; then
    link_file pip ~/Library/Application\ Support/pip
    zsh_command '$DOTFILES/scripts/commands/brew/brew-update'
    brew install \
        coreutils \
        curl \
        dash \
        diffutils \
        direnv \
        docker-completion \
        docker-compose-completion \
        fd \
        findutils \
        fzf \
        gawk \
        git \
        gnu-sed \
        gnu-tar \
        grep \
        htop \
        jq \
        kubectl \
        kubernetes-helm \
        mpd \
        ncmpcpp \
        neovim \
        openssh \
        p7zip \
        ripgrep \
        stern \
        tmux \
        zsh
fi

if [[ $osname == Linux* ]]; then
    link_file pip ~/.config/pip

    if command -v pacman > /dev/null; then
        link_file pacman ~/.config/pacman
            #lf \
        yay -Syu --needed --noconfirm \
            aria2 \
            bind-tools \
            dash \
            fd \
            fzf \
            htop \
            jq \
            moreutils \
            neovim \
            openssh \
            perl-image-exiftool \
            pkgfile \
            python \
            ripgrep \
            rsync \
            tmux \
            zsh
    fi

fi

if command -v termux-info > /dev/null; then
    pkg install \
        dash \
        fd \
        fzf \
        htop \
        jq \
        lf \
        neovim \
        openssh \
        python \
        ripgrep \
        tmux \
        zsh
fi

mkdir -p ~/.local/bin
ln -sf "$(which dash)" "$HOME/.local/bin/sh"

if [[ $osname == Darwin* ]]; then
    zsh_command '$DOTFILES/scripts/commands/pyenv/pyenv-update'
    zsh_command 'pyenv global 3.7.3'
fi

full-update

pip install \
    flake8 \
    pint \
    speedtest-cli

if [ "$(hostname)" = 'sol' ]; then
    link_file systemd ~/.config/systemd
fi
