#!/usr/bin/env bash
set -e

if command -v yay 2> /dev/null; then
    yay -S --needed --noconfirm \
        alacritty \
        arandr \
        argyllcms \
        blueman \
        dunst \
        firefox \
        foliate \
        gnome-settings-daemon \
        hsetroot \
        i3-wm \
        i3lock \
        i3status-rust \
        kid3-qt \
        mpd \
        mpv \
        ncmpcpp \
        network-manager-applet \
        networkmanager \
        nomacs \
        noto-fonts \
        noto-fonts-cjk \
        noto-fonts-emoji \
        noto-fonts-extra \
        pamixer \
        pavucontrol \
        picom \
        rofi \
        rofimoji \
        syncthing \
        transmission-remote-gtk \
        ttf-dejavu-emojiless \
        xclip \
        xorg-server \
        xorg-xdpyinfo \
        xorg-xinit \
        xorg-xinput \
        xorg-xprop \
        xss-lock
fi

pip install base16-shell-preview
