#!/usr/bin/env bash
set -e

link_file() {
    source_path="$PWD/$1"
    target_path="$2"
    echo -e "\033[1;33mLinking $1 \033[0m"
    if ! [ -e "$source_path" ]; then
        echo error: path $source_path does not exist. >&2
        exit 1
    fi
    rm -rf "$target_path"
    ln -sf "$source_path" "$target_path"
}

zsh_command() {
    echo -e "\033[1;33mNow running $@ \033[0m..."
    zsh -c "$@"
}

mkdir -p ~/.config

link_file git/.gitignore ~/.gitignore
link_file nvim ~/.config/nvim
link_file ranger ~/.config/ranger
link_file psql/.psqlrc ~/.psqlrc
link_file ptpython ~/.ptpython
link_file sqlite/.sqliterc ~/.sqliterc
link_file tmux/.tmux.conf ~/.tmux.conf
link_file zsh/.zshenv ~/.zshenv
link_file zsh/.zshrc ~/.zshrc

osname=$(uname)
if [[ $osname == Darwin* ]]; then
    link_file pip ~/Library/Application\ Support/pip
    zsh_command '$DOTFILES/scripts/macos/brew-update'
    brew install \
        automake \
        coreutils \
        curl \
        direnv \
        findutils \
        fzf \
        git \
        grep \
        htop \
        kubectl \
        kubernetes-helm \
        libtool \
        mpd \
        ncmpcpp \
        neovim \
        openssh \
        p7zip \
        ripgrep \
        stern \
        tmux \
        zsh
fi

if [[ $osname == Linux* ]]; then
    link_file pip ~/.config/pip

    if command -v pacman > /dev/null; then
        link_file pacman ~/.config/pacman
        sudo pacman -S --noconfirm dash
        ln -sf "$(which dash)" "$HOME/.local/bin/sh"
    fi
fi

zsh_command '$DOTFILES/scripts/python/pyenv-update'
if [[ $osname == Darwin* ]]; then
    zsh_command 'pyenv global 3.7.1'
fi

zsh_command pip-update
zsh_command 'PIP_REQUIRE_VIRTUALENV=0 pip install pipns'

for name in flake8 ranger-fm speedtest-cli zepusu; do
    zsh_command "pipns install "$name""
done

zsh_command nvim-update
