#!/usr/bin/env bash
set -e

link_file() {
    source_path="$PWD/$1"
    target_path="$2"
    echo -e "\033[1;33mLinking $1 \033[0m"
    if ! [ -e "$source_path" ]; then
        echo error: path $source_path does not exist. >&2
        exit 1
    fi
    rm -rf "$target_path"
    ln -sf "$source_path" "$target_path"
}

zsh_command() {
    echo -e "\033[1;33mNow running $1 \033[0m..."
    zsh -c "$1"
}

mkdir -p ~/.config

link_file git/.gitignore ~/.gitignore
link_file httpie ~/.httpie
link_file nvim ~/.config/nvim
link_file psql/.psqlrc ~/.psqlrc
link_file ranger ~/.config/ranger
link_file sqlite/.sqliterc ~/.sqliterc
link_file tmux/.tmux.conf ~/.tmux.conf
link_file zsh/.zshenv ~/.zshenv
link_file zsh/.zshrc ~/.zshrc

osname=$(uname)
if [[ $osname == Darwin* ]]; then
    link_file pip ~/Library/Application\ Support/pip
fi

if [[ $osname == Linux* ]]; then
    link_file pacman ~/.config/pacman
    link_file pip ~/.config/pip
fi

zsh_command pyenv-update
zsh_command pip-update
zsh_command 'pip install pipenv ranger-fm httpie pyzmq virtualenv speedtest-cli youtube_dl'
zsh_command flake8-update
zsh_command nvim-update
