#!/usr/bin/env bash
set -e

cd "$(dirname "$0")/../.."

link_file() {
    source_path="$PWD/$1"
    target_path="$2"
    echo -e "\033[1;33mLinking $1 \033[0m"
    if ! [ -e "$source_path" ]; then
        echo error: path $source_path does not exist. >&2
        exit 1
    fi
    rm -rf "$target_path"
    ln -sf "$source_path" "$target_path"
}

zsh_command() {
    echo -e "\033[1;33mNow running $@ \033[0m..."
    zsh -c "$@"
}

osname=$(uname)
if [[ $osname == Linux* ]]; then
    link_file compton/compton.conf ~/.config/compton.conf
    link_file dunst ~/.config/dunst
    link_file environment.d ~/.config/environment.d
    link_file fontconfig ~/.config/fontconfig
    link_file i3 ~/.config/i3
    link_file i3status ~/.config/i3status
    link_file mimeapps/mimeapps.list ~/.config/mimeapps.list
    link_file mpd-notification/mpd-notification.conf ~/.config/mpd-notification.conf
    link_file mpv ~/.config/mpv
    link_file qt5ct ~/.config/qt5ct
    link_file rofi ~/.config/rofi
    link_file xbindkeys/.xbindkeysrc ~/.xbindkeysrc
    link_file xinit/.xinitrc ~/.xinitrc
    link_file zsh/.zlogin ~/.zlogin

    if command -v pacman 2> /dev/null; then
        yay -S --noconfirm \
            adwaita-qt \
            arandr \
            argyllcms \
            blueberry \
            compton \
            dunst \
            firefox \
            foliate \
            gnome-settings-daemon \
            gnome-themes-extra \
            hsetroot \
            i3-wm \
            i3lock \
            i3status \
            kid3-qt \
            maim \
            mpc \
            mpd \
            mpd-notification \
            mpv \
            ncmpcpp \
            network-manager-applet \
            networkmanager \
            nomacs \
            noto-fonts \
            noto-fonts-cjk \
            noto-fonts-emoji \
            noto-fonts-extra \
            pamixer \
            paswitch \
            pavucontrol \
            rofi \
            rofimoji \
            syncthing \
            syncthing-gtk \
            termite \
            transmission-remote-gtk \
            ttf-dejavu \
            xbindkeys \
            xclip \
            xorg-server \
            xorg-xdpyinfo \
            xorg-xinit \
            xorg-xinput \
            xorg-xprop \
            xss-lock

        # for rofimoji
        yay -S --noconfirm --asdeps xsel
    fi

    systemctl --user enable syncthing
    systemctl --user enable mpd
    systemctl --user enable mpd-notification

elif [[ $osname == Darwin ]]; then
    link_file karabiner ~/.config/karabiner

    find "$PWD/macos/LaunchAgents" -type f -exec ln -sf {} ~/Library/LaunchAgents \;
    zsh_command "pipns -n osxmpdkeys install osxmpdkeys"
fi

link_file mpd ~/.config/mpd
link_file ncmpcpp ~/.config/ncmpcpp

zsh_command "pipns -n base16-shell-preview install base16-shell-preview"
