#!/usr/bin/env sh
configure_device() {
    echo 0 | tee \
        "$1"/leds/*:white:player-1/brightness \
        "$1"/leds/*:white:player-2/brightness \
        "$1"/leds/*:white:player-3/brightness \
        "$1"/leds/*:white:player-4/brightness \
        "$1"/leds/*:white:player-5/brightness

    echo '255 0 0' | tee "$1"/leds/*:rgb:indicator/multi_intensity
    echo '8' | tee "$1"/leds/*:rgb:indicator/brightness
}

for d in /sys/module/hid_playstation/drivers/hid:playstation/*/; do
    case "$d" in
        *module/)
            ;;
        *)
            configure_device "$d"
            ;;
    esac
done
