#!/bin/sh
restore_default() {
    ln -sf "$DOTFILES/termux/termux.properties.normal" ~/.termux/termux.properties
}

trap restore_default EXIT INT TERM

if [ $# -eq 1 ]; then
    ln -sf "$1" ~/.termux/termux.properties
    termux-reload-settings
    . ~/.base16_theme
fi
