#!/bin/sh
restore_default() {
    ln -sf "$DOTFILES/termux/termux.properties.normal" ~/.termux/termux.properties
}

trap restore_default EXIT INT TERM

if [ -f "$1" ]; then
    ln -sf "$1" ~/.termux/termux.properties
fi

termux-reload-settings
