#!/bin/bash
set -e

packages=$(pip-user list --outdated --format=freeze)

pip-user install -U pip setuptools
if [[ ! -z $packages ]]; then
    echo "${packages}" | grep -v '^\-e' | cut -d = -f 1 | xargs pip-user install --upgrade
fi
