#!/usr/bin/env sh
set -e

export PIP_REQUIRE_VIRTUALENV=0

if ! [ -x "$(command -v pip)" ]; then
    python -m ensurepip --user --default-pip
fi

if [ "$(pip list | grep -e '^pip ' -e '^setuptools ' -e '^wheel ' | wc -l)" != '4' ]; then
    pip install -U --force-reinstall pip setuptools wheel
fi

ood_packages="$(pip list --outdated --format=freeze)"

if ! [ -z "${ood_packages}" ]; then
    echo "${ood_packages}" | grep -v '^\-e' | cut -d = -f 1 | xargs pip install --upgrade
fi
