#!/usr/bin/env bash
export CFLAGS='-O2'
if [ $1 = 'install' ]; then
    if [[ "$OSTYPE" == darwin* ]]; then
        export CONFIGURE_OPTS="--with-openssl=$(brew --prefix openssl)"
    fi
fi
"$(which -a pyenv | tail -n +2 | head -n 1)" "$@"
