#!/bin/bash
set -e

python_version=$1
site_dir=$(python$python_version -m site --user-site)
if [[ ! -d $site_dir ]]; then
    mkdir -p $site_dir
    touch "$site_dir/.pth"

    cd $(python$python_version -m site --user-base)
    curl -O https://bootstrap.pypa.io/get-pip.py
    python$python_version get-pip.py --user --force
    rm get-pip.py
fi
