#!/usr/bin/env python
import argparse
import pkgutil
import sys


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('module')
    args = parser.parse_args()
    loader = pkgutil.get_loader(args.module)
    if loader is None:
        print('error: module not found', file=sys.stderr)
        sys.exit(1)
    path = getattr(loader, 'path', None)
    if path is None:
        print('error: built-in module', file=sys.stderr)
        sys.exit(1)
    print(path)


if __name__ == '__main__':
    main()
