#!/usr/bin/env bash
set -e

env_root=~/.local/share/virtualenvs
parent=$(realpath $(pwd))
env_folder=$env_root/$(printf $parent | sha256sum | awk '{print $1}')

rm -rf $env_folder .envrc
unset VIRTUAL_ENV

if [ "$1" = '-d' ]; then
    pipenv --rm > /dev/null 2>&1 || true
    exit
elif [ -e Pipfile ]; then
    pipenv clean
    env_folder=$(pipenv --venv)
elif [ -n "$1" ]; then
    eval "$(pyenv init -)"
    pyenv shell $1
fi

mkdir -p $env_root
if command -v virtualenv > /dev/null 2>&1; then
    set +e
    virtualenv -q -p python $env_folder
    if [ $? -ne 0 ]; then
        rm -r $env_folder
        exit 1
    fi
    set -e
else
    set +e
    python -m venv $env_folder
    if [ $? -ne 0 ]; then
        rm -r $env_folder
        exit 1
    fi
    set -e
fi

echo . $env_folder/bin/activate > $env_folder/.envrc
ln -s $parent $env_folder/.parent
cat > $env_folder/pip.conf<<EOF
[global]
user = false
EOF

cd $env_folder
direnv allow
cd - > /dev/null

cp $env_folder/.envrc .

. $env_folder/bin/activate

pip install -q --upgrade pip setuptools wheel

direnv allow
direnv reload
