#!/usr/bin/env python
import argparse
import pkgutil
import sys


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('module')
    args = parser.parse_args()

    loader = pkgutil.get_loader(args.module)
    if loader is None:
        sys.stderr.write('error: module not found\n')
        sys.exit(1)

    # Use get_filename for Python 2 compatibility
    try:
        path = loader.get_filename(args.module)
    except AttributeError:
        path = None

    if path is None:
        sys.stderr.write('error: built-in module\n')
        sys.exit(1)

    print(path)


if __name__ == '__main__':
    main()
