#!/usr/bin/env python
import argparse
import os
import pkgutil
import sys


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('module')
    parser.add_argument(
        '-d',
        dest='directory',
        action='store_true',
        help='output the directory instead of file'
    )
    args = parser.parse_args()

    loader = pkgutil.get_loader(args.module)
    if loader is None:
        sys.stderr.write('error: module not found\n')
        sys.exit(1)

    # Use get_filename for Python 2 compatibility
    try:
        path = loader.get_filename(args.module)
    except AttributeError:
        path = None

    if path is None:
        sys.stderr.write('error: built-in module\n')
        sys.exit(1)

    if args.directory is not None:
        print(os.path.dirname(path))
    else:
        print(path)


if __name__ == '__main__':
    main()
