#!/usr/bin/env sh
xmodmap -e "keycode 135 = Super_L"
setxkbmap -device "$(xinput list --id-only 'keyboard:HK-ZYYK-US-A1-02-00 USB KEYBOARD')" -option caps:escape

xinput set-prop \
    "$(xinput | grep Goodix | grep pointer | awk '{print $6}' | cut -d= -f2)" \
    'Coordinate Transformation Matrix' 0 1 0 -1 0 1 0 0 1
