#!/usr/bin/env sh
setxkbmap -device "$(xinput list --id-only 'keyboard:HK-ZYYK-US-A1-02-00 USB KEYBOARD')" -option caps:escape
xmodmap -e "keycode 135 = Super_L"

xinput set-prop \
    "$(xinput | grep Goodix | grep pointer | awk '{print $6}' | cut -d= -f2)" \
    'Coordinate Transformation Matrix' 0 1 0 -1 0 1 0 0 1
