#!/usr/bin/env sh
set-performance performance
xmodmap -e "keycode 135 = Super_L"
xinput set-prop \
    "$(xinput | grep Goodix | grep pointer | awk '{print $6}' | cut -d= -f2)" \
    'Coordinate Transformation Matrix' 0 1 0 -1 0 1 0 0 1
