#!/usr/bin/env sh
container_name="docker_shell-$(cat /dev/urandom | tr -cd 'a-f0-9' | head -c 32)"
trap "docker kill "${container_name}" > /dev/null 2>&1" HUP EXIT
docker run --rm -it --name "${container_name}" "$@"
