#!/usr/bin/env sh
YELLOW='\033[1;33m'
RESET_COLOR='\033[0m'

log() {
    printf "${YELLOW}$@${RESET_COLOR}\n"
}

log "Removing all containers ..."
all_containers=$(docker ps -aq)
if [ -n "$all_containers" ]; then
    docker rm -f $all_containers
fi

log "Pruning volumes ..."
docker volume prune -f
log "Pruning networks ..."
docker network prune -f
