#!/bin/bash
# git clfk
# given how fragile this is, clfk = clone fork or cluster fuck?
set -e

YELLOW='\033[1;33m'
RESET_COLOR='\033[0m'

log() {
    printf "${YELLOW}$@${RESET_COLOR}\n"
}


GIT_HOST=$(echo $1 | awk -F: '{print $1}')
GIT_PATH=$(echo $1 | awk -F: '{print $2}')
OWNER_NAME=$(dirname $GIT_PATH)
REPO_NAME=$(basename $GIT_PATH)

CLONE_PATH="${GIT_HOST}:$(whoami)/${REPO_NAME}"
UPSTREAM_PATH="${GIT_HOST}:${OWNER_NAME}/${REPO_NAME}"

log Cloning ${CLONE_PATH}
git clone "${CLONE_PATH}"
log Upstream ${UPSTREAM_PATH}
git -C ${REPO_NAME} upstream "${UPSTREAM_PATH}"
