#!/usr/bin/env sh
PWD="$(pwd)"
for f in "$@"; do
    DEST="$PWD/$(basename "$f").tar.zst"
    cd "$f" || exit 1
    if [ -d "$f" ]; then
        s='.'
    else
        s="$f"
    fi
    tar cf - "$s" | zstd -T0 --ultra -22 -o "$DEST"
    cd "$PWD" || exit 1
done
