#!/usr/bin/env sh
set -e

REMOVE=''
if [ "$1" = '--rm' ]; then
    REMOVE=1
    shift
fi

ORIG_PWD="$(pwd)"

for f in "$@"; do
    DEST="$ORIG_PWD/$(basename "$f").tar.zst"
    cd "$f" || exit 1
    tar cf - . | zstd -T0 --ultra -22 -o "$DEST"
    cd "$ORIG_PWD" || exit 1
    if [ -n "$REMOVE" ]; then
        rm -rf "$f"
    fi
done
