#!/usr/bin/env sh
set -e
XDG_DATA_DIR="${XDG_DATA_DIR:-$HOME/.local/share}"
INSTALL_DIR="${XDG_DATA_DIR}/goenv"

if ! [ -d "$INSTALL_DIR" ]; then
    mkdir -p "$XDG_DATA_DIR"
    git clone https://github.com/syndbg/goenv "$INSTALL_DIR" > /dev/null
else
    cd "$INSTALL_DIR"
    git clean -fd
    git pull
fi
