#!/usr/bin/env sh
set -e

DEVICE='epkowa'
OUTPUT="scan_$(date +%s).png"

# more than 800 crashes 
RESOLUTION=800

scanimage \
    --scan-area Maximum \
    --resolution "$RESOLUTION" \
    --x-resolution "$RESOLUTION" \
    --y-resolution "$RESOLUTION" \
    --progress \
    --device "$DEVICE" \
    --output "$OUTPUT"
