local error_handling = require("config/error_handling")
local variables = require("config/variables")
local tags = require("config/tags")
local wibox = require("config/wibox")
local mouse_bindings = require("config/mouse_bindings")
local key_bindings = require("config/key_bindings")
local signals = require("config/signals")
local rules = require("config/rules")
