#!/usr/bin/env python3
import os
import pathlib
import shutil


def has_battery():
    root = pathlib.Path('/sys/class/power_supply')
    for path in root.iterdir():
        if not path.name.startswith('hidpp_'):
            return True
    return False


def has_bluetooth():
    return bool(shutil.which('bluetoothctl'))


config = """
[theme]
theme = "native"

[icons]
icons = "awesome4"
"""

if has_battery():
    config += """
[[block]]
block = "battery"
missing_format = ""
"""

if has_bluetooth():
    config += """
# Sony WH-1000XM4
[[block]]
block = "bluetooth"
mac = "F8:4E:17:93:84:67"
disconnected_format = ""
"""

config += """
[[block]]
block = "sound"
device_kind = "source"
max_vol = 100
[[block.click]]
button = "left"
cmd = "toggle-source-mute"

[[block]]
block = "sound"
device_kind = "sink"
max_vol = 100
[[block.click]]
button = "left"
cmd = "set-volume --toggle-mute"

[[block]]
block = "net"
format = "$icon"

[[block]]
block = "time"
interval = 30
format = "$timestamp.datetime(f:'%Y-%m-%d %R')"
"""

config_path = pathlib.Path('~/.config/i3status-rust/config.toml').expanduser()
config_path.parent.mkdir(exist_ok=True, parents=True)
config_path.write_text(config)

os.execvp('i3status-rs', ('i3status-rs',))
