#!/usr/bin/env python3
import os
import pathlib


def has_battery():
    root = pathlib.Path('/sys/class/power_supply')
    for path in root.iterdir():
        if not path.name.startswith('hidpp_'):
            return True
    return False


config = """
[theme]
theme = "native"

[icons]
icons = "awesome4"
"""

if has_battery():
    config += """
[[block]]
block = "battery"
missing_format = ""
device = "hidpp_battery_3"
"""

config += """
[[block]]
block = "sound"
device_kind = "source"
max_vol = 100

[[block]]
block = "sound"
device_kind = "sink"
max_vol = 100

[[block]]
block = "time"
interval = 30
format = "$timestamp.datetime(f:'%Y-%m-%d %R')"
"""

config_path = pathlib.Path('~/.config/i3status-rust/config.toml').expanduser()
config_path.parent.mkdir(exist_ok=True, parents=True)
config_path.write_text(config)

os.execvp('i3status-rs', ('i3status-rs',))
