#!/usr/bin/env sh
ORIG_BIN="$(which -a firefox | grep -v "^$0$" | head -n 1)"
if ! [ -e "$ORIG_BIN" ]; then
    echo error: command error >&2
    exit 1
fi

if [ "$XDG_SESSION_TYE" = 'wayland' ]; then
    export GDK_BACKEND=wayland
else
    export MOZ_USE_XINPUT2=1
fi
exec "$ORIG_BIN" "$@"
