#!/usr/bin/env python
import os
import pathlib

import mpd


def is_streaming(client):
    current_file = client.currentsong().get('file', '')
    return current_file.lower().startswith(('http://', 'https://'))


def main():
    runtime_dir = os.environ['XDG_RUNTIME_DIR']
    if runtime_dir:
        socket = pathlib.Path(runtime_dir) / 'mpd' / 'socket'
        if socket.exists():
            mpd_host = str(socket)

    client = mpd.MPDClient()
    client.connect(mpd_host)

    if client.status()['state'] == 'play':
        if is_streaming(client):
            client.stop()
        else:
            client.pause()
    else:
        client.play()


if __name__ == '__main__':
    main()
