#!/usr/bin/env sh

# bundled jdk doesn't respect GDK_SCALE or other scaling config
#export STUDIO_JDK=/usr/lib/jvm/default

# built-in dpi detection doesnt. fucking. work.
# https://intellij-support.jetbrains.com/hc/en-us/articles/360007994999-HiDPI-configuration
export GDK_SCALE="$(gsettings get org.gnome.desktop.interface scaling-factor | cut -d' ' -f2)"

exec /usr/bin/android-studio "$@"
