#!/usr/bin/env sh
set -e

show_help() {
    cat << EOF
usage: apk-release-tool APK (KEY)

Positional Arguments:
    APK     unsigned apk
    KEY     key to sign with (default: ~/.android/debug.keystore)
EOF
}

while true; do
    case "$1" in
        --help)
            show_help
            exit
            ;;
        *)
            case $# in
                1)
                    UNSIGNED_APK="$1"
                    RELEASE_KEY=~/.android/debug.keystore
                    ;;
                2)
                    UNSIGNED_APK="$1"
                    RELEASE_KEY="$2"
                    ;;
                *)
                    show_help >&2
                    echo error: missing required arguments >&2
                    exit 1
            esac
            break
    esac
done

ALIGNED_APK=$(echo "${UNSIGNED_APK}" | sed 's/-unsigned\.apk$/-aligned.apk/')
RELEASE_APK=$(echo "${UNSIGNED_APK}" | sed 's/-unsigned\.apk$/.apk/')

apksigner sign --ks "${RELEASE_KEY}" --out "${RELEASE_APK}" "${ALIGNED_APK}"
apksigner verify "${RELEASE_APK}"
