#!/usr/bin/env sh
set -e
IMAGE=nvllsvm/harmonize

SOURCE=/storage/Audio/Library
TARGET=/storage/Audio/Lossy_opus_128

harmonize() {
    podman run \
        --rm \
        --pull always \
        --quiet \
        --userns= \
        -v "$SOURCE:$SOURCE" \
        -v "$TARGET:$TARGET" \
        "$IMAGE" "$@"
}

harmonize -n "$(nproc)" "$SOURCE" "$TARGET" --codec opus --bitrate 128 --music
