#!/usr/bin/env sh
podman run \
    --rm \
    -d \
    --name kf2-server \
    --pull always \
    --quiet \
    -v "$HOME/.local/volumes/killingfloor2-server:/data" \
    --net host \
    --env-file "$DOTFILES_PRIVATE/kf2-server.env" \
    nvllsvm/killingfloor2-server update
