#!/usr/bin/env sh
set -e
IMAGE=nvllsvm/harmonize
docker pull $IMAGE > /dev/null
docker run \
    --rm \
    -e PUID=1000 \
    -e PGID=100 \
    -e NUM_PROCESSES=8 \
    -v /mnt/storage1/Audio/Library:/source \
    -v /mnt/storage1/Audio/MP3:/target \
    $IMAGE

printf 'Updating Airsonic library .'
airsonic-cli startScan > /dev/null

while [ $(airsonic-cli getScanStatus | jq '.scanning') = 'true' ]; do
    printf .
    sleep 1
done
echo ' Done'
