#!/usr/bin/env sh
set -e
IMAGE=nvllsvm/harmonize

SOURCE=/storage/Audio/Library
TARGET=/storage/Audio/MP3

harmonize() {
    podman run \
        --rm \
        --pull always \
        --quiet \
        --userns= \
        -v "$SOURCE:$SOURCE" \
        -v "$TARGET:$TARGET" \
        "$IMAGE" "$@"
}

harmonize -n 8 "$SOURCE" "$TARGET"

printf 'Updating Airsonic library .'
airsonic-cli startScan > /dev/null

while [ "$(airsonic-cli getScanStatus | jq '.scanning')" = 'true' ]; do
    printf .
    sleep 1
done
echo ' Done'
