#!/usr/bin/env sh
set -e
IMAGE=nvllsvm/harmonize:dev

SOURCE=/storage/Audio/Library
TARGET=/storage/Audio/MP3

docker pull "$IMAGE" > /dev/null

harmonize() {
    docker run \
        --rm \
        --user "$(id -u):$(id -g)" \
        -v "$SOURCE:$SOURCE" \
        -v "$TARGET:$TARGET" \
        "$IMAGE" "$@"
}

harmonize -n 8 "$SOURCE" "$TARGET"

printf 'Updating Airsonic library .'
airsonic-cli startScan > /dev/null

while [ "$(airsonic-cli getScanStatus | jq '.scanning')" = 'true' ]; do
    printf .
    sleep 1
done
echo ' Done'
