#!/usr/bin/env sh
rsync -av --progress --delete /storage/Syncthing/Default/RetroArch/rom/ odroidgoadvance:~/.config/retroarch/roms
rsync -av --progress --delete /storage/Syncthing/Default/RetroArch/bios/ odroidgoadvance:~/.config/retroarch/bios
