#!/usr/bin/env bash
set -e

DATABASE=sol
DATABASE_DIR="/var/cache/pacman/$DATABASE"
DATABASE_FILE="$DATABASE_DIR/$DATABASE.db.tar"

AURVCS='.*-(bzr|git|hg|svn)$'

if ! [ -f "$DATABASE_FILE" ]; then
    repo-add "$DATABASE_FILE"
fi

repotool_update() {
    sudo pacsync "$DATABASE" > /dev/null

    aur sync --no-view --no-confirm --database="$DATABASE" --no-ver --upgrades

    vcs_pkgs=$(aur repo --database="$DATABASE" --list | cut -f1 | grep -E "$AURVCS" || true)
    if [ -n "$vcs_pkgs" ]; then
        aur sync "$vcs_pkgs" --no-ver-argv --no-build --no-view
        for vcs_pkg in $vcs_pkgs; do
            repo_ver="$(aur repo --database "$DATABASE" --list | grep -P "^$vcs_pkg\t")"
            current_ver="$(aur srcver ~/.cache/aurutils/sync/"$vcs_pkg")"
            ood="$(printf '%s' "$repo_ver" | aur vercmp -p <(printf '%s' "$current_ver"))"
            if [ -n "$ood" ]; then
                repotool_add "$vcs_pkg"
            fi
        done
    fi

    sudo pacsync "$DATABASE" > /dev/null
    paccache --remove --keep 1 --cachedir "$DATABASE_DIR"
}

repotool_add() {
    sudo pacsync "$DATABASE" > /dev/null
    for i in "${@}"; do
        if [ -f "$i" ]; then
            sudo cp "$i" "$DATABASE_DIR"
            repo-add "$DATABASE_FILE" "$i"
        else
            packages_and_deps="$packages_and_deps $i $(echo "$i" | aur depends 2>/dev/null | cut -f2 | sort | comm -12 - <(aur pkglist | sort))"
        fi
    done
    if [ -n "$packages_and_deps" ]; then
        aur sync --no-view --no-confirm --no-ver --database="$DATABASE" -- ${packages_and_deps} || true
    fi
    sudo pacsync "$DATABASE" > /dev/null
    for i in "${@}"; do
        if ! [ -f "$i" ]; then
            pacman -Si "sol/$i" >&2 || true
        fi
    done
}

repotool_remove() {
    repo-remove "$DATABASE_FILE" "${@}"
    for pkg in "${@}"; do
        rm -rf "$DATABASE_DIR"/"$pkg"*.pkg.*
    done
    sudo pacsync "$DATABASE" > /dev/null
}

sync_nullsum() {
    rsync -av --progress --delete /var/cache/pacman/sol/ nullsum.net:~/srv/http/repo/arch/x86_64
}

usage() {
    cat << EOF
usage: sol-repotool (add|remove|update)
EOF
}

case "$1" in
    update)
        shift
        repotool_update "$@"
        sync_nullsum
        exit
        ;;
    add)
        shift
        repotool_add "$@"
        sync_nullsum
        exit
        ;;
    remove)
        shift
        repotool_remove "$@"
        sync_nullsum
        exit
        ;;
    --help)
        usage
        exit
        ;;
    *)
        usage >&2
        exit 1
esac
