#!/bin/bash
export COMPOSE_PROJECT_NAME=sol-docker 
export COMPOSE_FILE=~/Code/Private/sol-docker/docker-compose.yaml

if [[ "$1" == "restart" ]]; then
    if [[ -n "$2" ]]; then
        docker-compose stop -t 0 "$2"
        docker-compose rm -fs "$2"
    else
        docker-compose down -t 1 --remove-orphans -v
    fi
    docker-compose up -d
else
    docker-compose "$@"
fi
