#!/usr/bin/env bash
set -e

if [ -n "$DEBUG" ]; then
    set -x
fi

DATABASE=sol
DATABASE_DIR="/var/cache/pacman/$DATABASE"
DATABASE_FILE="$DATABASE_DIR/$DATABASE.db.tar"

if ! [ -f "$DATABASE_FILE" ]; then
    repo-add "$DATABASE_FILE"
fi

repotool_update() {
    sudo pacsync "$DATABASE" > /dev/null

    mkdir -p ~/.cache/aurutils/sync
    cd ~/.cache/aurutils/sync || exit 1

    aur sync --no-view --no-confirm --database="$DATABASE" --no-ver --upgrades

    pkgs=$(aur repo --database="$DATABASE" --list | cut -f1)
    aur sync "$pkgs" --no-ver-argv --no-build --no-view
    for pkg in $pkgs; do
        echo "Checking ${pkg}"
        escaped_pkg="$(printf '%s' "$pkg" | sed 's/\+/\\+/g')"
        repo_ver="$(aur repo --database "$DATABASE" --list | grep -P "^$escaped_pkg\t")"
        current_ver="$(aur srcver "$pkg" || true)"
        if [ -z "$current_ver" ]; then
            repotool_add "$pkg"
        fi

        ood="$(printf '%s' "$repo_ver" | aur vercmp -p <(printf '%s' "$current_ver"))"
        if [ -n "$ood" ]; then
            repotool_add "$pkg"
        fi
    done

    sudo pacsync "$DATABASE" > /dev/null
    paccache --remove --keep 1 --cachedir "$DATABASE_DIR"
}

repotool_add() {
    sudo pacsync "$DATABASE" > /dev/null
    for i in "${@}"; do
        if [ -f "$i" ]; then
            sudo cp "$i" "$DATABASE_DIR"
            repo-add "$DATABASE_FILE" "$i"
        else
            packages_and_deps="$packages_and_deps $i $(echo "$i" | aur depends 2>/dev/null | cut -f2 | sort | comm -12 - <(aur pkglist | sort))"
        fi
    done
    if [ -n "$packages_and_deps" ]; then
        aur sync --no-view --no-confirm --no-ver --database="$DATABASE" -- ${packages_and_deps} || true
    fi
    sudo pacsync "$DATABASE" > /dev/null
    for i in "${@}"; do
        if ! [ -f "$i" ]; then
            pacman -Si "sol/$i" >&2 || true
        fi
    done
}

repotool_remove() {
    repo-remove "$DATABASE_FILE" "${@}"
    for pkg in "${@}"; do
        rm -rf "$DATABASE_DIR"/"$pkg"*.pkg.*
    done
    sudo pacsync "$DATABASE" > /dev/null
}

repotool_prune() {
    python << EOF
import pathlib
import subprocess
import shutil

DATABASE = '${DATABASE}'

def get_packages():
    proc = subprocess.run(
        ['aur', 'repo', f'--database={DATABASE}', '--list'],
        stdout=subprocess.PIPE,
        check=True)
    return [
        line.split()[0]
        for line in proc.stdout.decode().splitlines()
    ]

packages = get_packages()

for path in pathlib.Path('~/.cache/aurutils/sync').expanduser().iterdir():
    if path.name not in packages:
        print('Clearing cache for', path.name)
        shutil.rmtree(path)
EOF
}

repotool_list() {
    aur repo --database="$DATABASE" --list | cut -f1
}

sync_nullsum() {
    rsync -av --progress --delete-after /var/cache/pacman/sol/ nullsum.net:~/srv/http/repo/arch/x86_64
}

usage() {
    cat << EOF
usage: sol-repotool (add|list|prune|remove|update)
EOF
}

case "$1" in
    update)
        shift
        repotool_update "$@"
        sync_nullsum
        exit
        ;;
    add)
        shift
        repotool_add "$@"
        sync_nullsum
        exit
        ;;
    remove)
        shift
        repotool_remove "$@"
        sync_nullsum
        exit
        ;;
    prune)
        shift
        repotool_prune
        ;;
    list)
        shift
        repotool_list
        ;;
    --help)
        usage
        exit
        ;;
    *)
        usage >&2
        exit 1
esac
