#!/usr/bin/env sh
set -e

update_server() {
    cd "$1"
    server="$(basename "$1")"
    echo "$server - syncing certs"
    ./bin/copy_certs_to_remote.sh > /dev/null 2>&1
    echo "$server - updating and reloading Docker containers"
    ./bin/reload_remote.sh > /dev/null 2>&1
    cd - > /dev/null
}

~/src/git.nullsum.net/nvllsvm/certs-nullsum.net/bin/renew_all.sh

update_server ~/src/github/nvllsvm/nullsum.net
