#!/usr/bin/env sh
set -e

HOME_BACKUP_DIR=/storage/Backup/sol/home

mkdir -p "$HOME_BACKUP_DIR"

backup_home() {
    echo Backing up home ...
    sudo rsync -av --progress --delete \
        --exclude .cache \
        --exclude .local \
        --exclude .npm \
        --exclude .nuget \
        --exclude .rustup \
        --exclude Code/sol-docker/volumes/jellyfin/cache \
        --exclude Code/sol-docker/volumes/jellyfin/logs \
        --exclude Code/sol-docker/volumes/jellyfin/transcoding-temp \
        ~ar "$HOME_BACKUP_DIR"
}

backup_home
wasabi-sync
