#!/bin/sh

set -e

HOME_BACKUP_DIR=/mnt/pool1/Backup/sol/home

backup_home() {
    echo Backing up home ...
    sudo rsync -av --progress --delete \
        --exclude Code/sol-docker/volumes/jellyfin/transcoding-temp \
        --exclude Code/sol-docker/volumes/jellyfin/logs \
        --exclude Code/sol-docker/volumes/jellyfin/cache \
        --exclude .cache \
        ~draje $HOME_BACKUP_DIR
}

backup_home
wasabi-sync
