#!/usr/bin/env bash
set -e

uptime --pretty

systemctl --user import-environment HOME PATH MAIL DOTFILES

sudo zfs load-key storage/encrypted

sudo systemctl start zfs-mount
sudo systemctl start zfs-share.service
sudo systemctl start zpool-check-health-storage.service

sudo zpool status -v

echo Mounting CCTV storage ...
sudo mkdir -p /mnt/frigate
sudo mount /dev/disk/by-uuid/e02387d5-c96e-4896-ab3a-86e4741be77e /mnt/frigate

echo Starting NFS binds ...
sudo mount --bind ~ar /srv/nfs4/ar
sudo mount --bind /storage /srv/nfs4/storage
sudo systemctl restart nfs-server.service

echo Starting systemd units ...
systemctl --user enable --now download-latest-vuescan-version.timer
systemctl --user enable --now git-repo-backup.timer
systemctl --user enable --now gog-update.timer
systemctl --user enable --now harmonize-library.timer
systemctl --user enable --now mbsync.timer
systemctl --user enable --now sol-fix-permissions.timer
systemctl --user enable --now sol-update-check.timer
systemctl --user enable --now sol-update-remotes.timer
systemctl --user enable --now wasabi-sync.timer

echo Starting Docker ...
sudo systemctl start docker
sol-docker startup

echo Starting podman ...
podman system migrate || true

echo Starting wireguard ...
sudo wg-quick up sol
