#!/usr/bin/env sh
set -eu
export RCLONE_CONFIG="${DOTFILES_PRIVATE}/wasabi/rclone.conf"

PREFIX='wasabi:nullsum-sol'

HAS_ERROR=

rclone_sync() {
    echo "Syncing $1"
    rclone sync "$@" -v || true
    NEW_RET=$?
    case "$NEW_RET" in
        0)
            ;;
        9)
            # no files transferred
            ;;
        *)
            echo "error: exit code ${NEW_RET}" >&2
            HAS_ERROR=1
    esac
}

rclone_sync /storage/Games \
    "${PREFIX}"/storage1/Games \
    --exclude /PC/GOG.com/ \
    --exclude /Nintendo\ Switch/
rclone_sync /storage/Audio \
    "${PREFIX}"/storage1/Audio \
    --exclude /Lossy*/
rclone_sync /storage/Syncthing/Default/Bitwig\ Studio \
    "${PREFIX}"/storage1/Bigwig\ Studio
rclone_sync /storage/Books \
    "${PREFIX}"/storage1/Books
rclone_sync /storage/Pictures \
    "${PREFIX}"/storage1/Pictures

echo 'Determing bucket size'
rclone size "${PREFIX}"
if [ -n "$HAS_ERROR" ]; then
    exit 1
fi
