#!/usr/bin/env zsh
if [ $# -ne 1 ]; then
    echo 'usage: SSH_HOST' >&2
    exit 1
fi
SSH_HOST="$1"
TITLE="tmux-${SSH_HOST}"
foot \
    --title "${TITLE}" \
    --app-id  "${TITLE}" \
    -- sh -c ". ~/.base16_theme; exec ssh-tmux-attach ${SSH_HOST}" 2> /dev/null > /dev/null &
disown
