#!/usr/bin/env zsh
case $# in
    0)
        SSH_HOST="$(kdialog --inputbox '<b>foot-ssh-tmux</b>\nEnter hostname:')"
        ;;
    1)
        SSH_HOST="$1"
        ;;
    *)
        echo 'usage: SSH_HOST' >&2
        exit 1
        ;;
esac
TITLE="ssh-tmux - ${SSH_HOST}"
foot \
    --title "${TITLE}" \
    --app-id  "${TITLE}" \
    -- sh -c ". ~/.base16_theme; exec ssh-tmux-attach ${SSH_HOST}" 2> /dev/null > /dev/null &
disown
