#!/usr/bin/env sh
format_json() {
    jq -S 'reduce (.[] | select(.key | endswith("/") | not)) as $item ({}; setpath($item.key | split("/"); ($item.value | @base64d)))'
}

if [ -t 0 ]; then
    consul kv export "$@" | format_json
else
    format_json
fi
