#!/usr/bin/env sh
file="$1"

if [ -z "$file" ]; then
    echo error: missing file parameter >&2
    exit 1
fi

filename=$(basename "$file")
extension="${filename##*.}"

if [ "${extension}" = "md" ]; then
    pandoc_format=gfm
elif [ "${extension}" = "rst" ]; then
    pandoc_format=rst
else
    echo error: unknown filetype >&2
    exit 1
fi

pandoc \
    --from "${pandoc_format}" \
    --to html \
    -c "${DOTFILES}"/pandoc/css/github-markdown.css \
    --self-contained \
    --standalone \
    --columns=10000 \
    "$@"
