#!/usr/bin/env sh
set -e
if [ $# -eq 1 ]; then
    cd "$1" || exit 1
fi

mount -t proc /proc ./proc

mount --rbind /sys ./sys
mount --make-rslave ./sys

mount --rbind /dev ./dev
mount --make-rslave ./dev

cp /etc/resolv.conf ./etc/resolv.conf

chroot ./ /bin/sh

umount --recursive ./dev
umount --recursive ./sys
