#!/usr/bin/env python
import argparse
import subprocess


def cards():
    proc = subprocess.run(
        ["pactl", "list", "cards"], stdout=subprocess.PIPE, check=True
    )
    return [
        line.strip().split(maxsplit=1)[1]
        for line in proc.stdout.decode().splitlines()
        if line.startswith("\tName: ")
    ]


def set_profile(card_name, profile_name):
    subprocess.run(["pactl", "set-card-profile", card_name, profile_name], check=True)


def set_default_sink(name):
    subprocess.run(["pactl", "set-default-sink", name], check=True)


def set_default_source(name):
    subprocess.run(["pactl", "set-default-source", name], check=True)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--profile", nargs=2, action="append")
    args = parser.parse_args()

    active_cards = set()
    for card_name, profile_name in args.profile:
        active_cards.add(card_name)
        set_profile(card_name, profile_name)

    for card_name in cards():
        if card_name not in active_cards:
            set_profile(card_name, "off")


if __name__ == "__main__":
    main()
