#!/usr/bin/env python3
import i3ipc

INSTANCE = 'i3-scratchpad-'


def on_window_focus(self, e):
    if not e.container.window_instance.startswith(INSTANCE):
        CONN.command(f'[instance={INSTANCE}] move scratchpad')


CONN = i3ipc.Connection()
try:
    CONN.on('window::focus', on_window_focus)
    CONN.main()
finally:
    CONN.main_quit()
