#!/usr/bin/env python3
import time
import traceback

import i3ipc

INSTANCE = 'i3-scratchpad-'


def run():
    conn = i3ipc.Connection()

    def on_window_focus(_, e):
        if not e.container.window_instance.startswith(INSTANCE):
            conn.command(f'[instance={INSTANCE}] move scratchpad')

    try:
        conn.on('window::focus', on_window_focus)
        conn.main()
    finally:
        conn.main_quit()


def main():
    while True:
        try:
            run()
        except Exception as e:
            traceback.print_exception(e)
            time.sleep(1)


if __name__ == '__main__':
    main()
