#!/usr/bin/env sh
cat > ~/.config/i3/config << EOF
set \$mod Mod4
set \$gap_size 10px
set \$border_size 2px
set \$bar_padding_top 0px
set \$bar_padding_bottom 0px
set \$bar_padding_left 0px
set \$bar_padding_right 0px

set \$color_bg #${BASE16_BACKGROUND}
set \$color_fg #${BASE16_FOREGROUND}
set \$color_00 #${BASE16_COLOR0}
set \$color_01 #${BASE16_COLOR1}
set \$color_02 #${BASE16_COLOR2}
set \$color_03 #${BASE16_COLOR3}
set \$color_04 #${BASE16_COLOR4}
set \$color_05 #${BASE16_COLOR5}
set \$color_06 #${BASE16_COLOR6}
set \$color_07 #${BASE16_COLOR7}
set \$color_08 #${BASE16_COLOR8}
set \$color_09 #${BASE16_COLOR9}
set \$color_10 #${BASE16_COLOR10}
set \$color_11 #${BASE16_COLOR11}
set \$color_12 #${BASE16_COLOR12}
set \$color_13 #${BASE16_COLOR13}
set \$color_14 #${BASE16_COLOR14}
set \$color_15 #${BASE16_COLOR15}
set \$color_16 #${BASE16_COLOR16}
set \$color_17 #${BASE16_COLOR17}
set \$color_18 #${BASE16_COLOR18}
set \$color_19 #${BASE16_COLOR19}
set \$color_20 #${BASE16_COLOR20}
set \$color_21 #${BASE16_COLOR21}

set \$font ${FONT_NAME}
set \$fontSize ${FONT_SIZE}

include config.d/config
EOF
