#!/usr/bin/env sh
CONF="${TMPDIR:-/tmp}/i3status-rs.toml"
cat > "$CONF" << EOF
[theme]
theme = "native"

[icons]
icons = "awesome4"
EOF

case "$(hostname)" in
    deimos|phobos)
        cat >> "$CONF" << EOF
[[block]]
block = "battery"
device = "BAT0"
EOF
        ;;
esac

cat >> "$CONF" << EOF
[[block]]
block = "sound"
device_kind = "source"
max_vol = 100
[[block.click]]
button = "left"
cmd = "toggle-source-mute"

[[block]]
block = "sound"
device_kind = "sink"
max_vol = 100
[[block.click]]
button = "left"
cmd = "set-volume --toggle-mute"

[[block]]
block = "time"
interval = 30
format = "\$timestamp.datetime(f:'%Y-%m-%d %R')"
EOF

exec i3status-rs "$CONF"
