#!/usr/bin/env sh
CONF="${TMPDIR:-/tmp}/i3status-rs"
cat > "$CONF" << EOF
theme = "native"
icons = "awesome"
EOF

case "$(hostname)" in
    deimos|phobos)
        cat >> "$CONF" << EOF
[[block]]
block = "battery"
device = "BAT0"
EOF
        ;;
esac

cat >> "$CONF" << EOF
[[block]]
block = "sound"
device_kind = "source"
max_vol = 100
on_click = "toggle-source-mute"

[[block]]
block = "sound"
device_kind = "sink"
max_vol = 100
on_click = "set-volume --toggle-mute"

[[block]]
block = "time"
interval = 30
format = "%F %R"
EOF

exec i3status-rs "$CONF"
