#!/usr/bin/env sh
alacritty --title "alacritty-launcher-$$" "$@" &
child=$!
i3-msg -t subscribe -m '[ "window" ]' | while read line ; do
    case "$line" in
        *"\"alacritty-launcher-$$\""*)
            ;;
        *)
            kill -9 "$child" > /dev/null 2>&1
            exit
            break
    esac
done
