#!/usr/bin/env python3
import argparse
import asyncio
import contextlib
import os
import pathlib
import re
import subprocess
import sys

import dbus
import psutil

FIFO_PATH = '/tmp/i3-hotkey-daemon.fifo'


class DBusNotifier:
    BUS_NAME = 'org.freedesktop.Notifications'
    OBJECT_PATH = '/org/freedesktop/Notifications'

    def __init__(self):
        self.interface = dbus.Interface(
            dbus.SessionBus().get_object(self.BUS_NAME,
                                         self.OBJECT_PATH),
            self.BUS_NAME)

    def notify(self,
               /,
               app_name='',
               replaces_id=None,
               app_icon='',
               summary='',
               body='',
               actions=None,
               hints=None,
               expire_timeout=-1):

        replaces_id = replaces_id or 0
        actions = actions or []
        hints = hints or {}

        return self.interface.Notify(
            app_name, replaces_id, app_icon, summary, body, actions, hints,
            expire_timeout)


class VolumeOutput:
    ACTIONS = {
        'up': ['--unmute', '--increase', '5'],
        'down': ['--unmute', '--decrease', '5'],
        'toggle-mute': ['--toggle-mute'],
    }

    def __init__(self, dbus):
        self.dbus = dbus
        self.dbus_replaces_id = None

    async def action(self, action):
        is_muted, volume = await self.pamixer(*self.ACTIONS[action])
        rounded_volume = round_to_nearest(volume, 5)
        if volume != rounded_volume:
            is_muted, volume = await self.pamixer(
                '--set-volume', str(rounded_volume))

        hints = {
            'x-dunst-stack-tag': 'hotkey-daemon-volume-output',
            'transient': 1,
            'urgency': 1,
        }
        if is_muted:
            body = '🔇'
        else:
            body = ''
            hints['value'] = volume
        self.dbus_replaces_id = self.dbus.notify(
            summary='Volume',
            body=body,
            hints=hints,
            replaces_id=self.dbus_replaces_id)

    @staticmethod
    async def pamixer(*args):
        proc = await asyncio.create_subprocess_exec(
            'pamixer', '--get-mute', '--get-volume', *args,
            stdout=asyncio.subprocess.PIPE,
        )
        stdout, _ = await proc.communicate()
        is_muted, volume = stdout.decode().strip().split()
        is_muted = True if is_muted == 'true' else False
        volume = int(volume)
        return is_muted, volume


class VolumeInput:
    ACTIONS = {
        'toggle-mute': ['--toggle-mute', '--set-volume', '100'],
    }

    def __init__(self, dbus):
        self.dbus = dbus
        self.dbus_replaces_id = None

    async def action(self, action):
        is_muted = await self.pamixer(*self.ACTIONS[action])
        hints = {
            'x-dunst-stack-tag': 'hotkey-daemon-volume-input',
            'transient': 1,
            'urgency': 1,
        }
        body = '🚫' if is_muted else 'Recording'
        self.dbus_replaces_id = self.dbus.notify(
            summary='🎙️ Microphone',
            body=body,
            hints=hints,
            replaces_id=self.dbus_replaces_id)

    @staticmethod
    async def pamixer(*args):
        proc = await asyncio.create_subprocess_exec(
            'pamixer', '--get-mute', '--default-source', *args,
            stdout=asyncio.subprocess.PIPE,
        )
        stdout, _ = await proc.communicate()
        is_muted = stdout.decode().strip()
        is_muted = True if is_muted == 'true' else False
        return is_muted


class Touchpad:
    ACTIONS = {
        'cycle',
    }

    def __init__(self, dbus):
        self.dbus = dbus
        self.dbus_replaces_id = None

    async def action(self, _):
        all_props = await xinput.list_props()
        for dev_id, props in all_props.items():
            if DISABLE_WHILE_TYPING not in props:
                continue

            if props['Device Enabled']['value'] == '0':
                await xinput.set_prop(dev_id, 'Device Enabled', '1')
                await xinput.set_prop(dev_id, DISABLE_WHILE_TYPING, '1')
                body = 'Disabled While Typing'
            elif props[DISABLE_WHILE_TYPING]['value'] == '1':
                await xinput.set_prop(dev_id, DISABLE_WHILE_TYPING, '0')
                body = 'Enabled While Typing'
            else:
                await xinput.set_prop(dev_id, 'Device Enabled', '0')
                body = 'Disabled'

        hints = {
            'transient': 1,
            'urgency': 1,
        }
        self.dbus_replaces_id = self.dbus.notify(
            summary='Touchpad',
            body=body,
            hints=hints,
            replaces_id=self.dbus_replaces_id)


DISABLE_WHILE_TYPING = 'libinput Disable While Typing Enabled'
PROP_ID = re.compile(r'^(?P<prop_name>.*) \((?P<prop_id>\d+)\)$')


class xinput:
    @staticmethod
    async def ids():
        proc = await asyncio.create_subprocess_exec(
            'xinput', 'list', '--id-only',
            stdout=asyncio.subprocess.PIPE)
        stdout, _ = await proc.communicate()
        if proc.returncode:
            raise RuntimeError
        return stdout.decode().splitlines()

    @classmethod
    async def list_props(cls, ids=None):
        if ids is None:
            ids = await cls.ids()
        ids = list(ids)
        proc = await asyncio.create_subprocess_exec(
            'xinput', 'list-props', *ids,
            stdout=asyncio.subprocess.PIPE)
        stdout, _ = await proc.communicate()
        if proc.returncode:
            raise RuntimeError
        props = {}
        current_id = None
        for line in stdout.decode().splitlines():
            if line.startswith('Device '):
                current_id = ids.pop(0)
                props[current_id] = {}
            else:
                line = line.strip()
                full_prop_name, prop_value = line.split(':\t', maxsplit=1)
                prop_name, prop_id = PROP_ID.findall(full_prop_name)[0]
                if prop_name in props[current_id]:
                    raise RuntimeError
                props[current_id][prop_name] = {
                    'id': prop_id,
                    'value': prop_value}
        return props

    @staticmethod
    async def set_prop(dev_id, prop_name, prop_value):
        proc = await asyncio.create_subprocess_exec(
            'xinput', '--set-prop', dev_id, prop_name, prop_value)
        await proc.communicate()
        if proc.returncode:
            raise RuntimeError




def round_to_nearest(value, nearest):
    return int(value / nearest) * nearest


class KeyboardBacklight:
    DEV = '/sys/class/leds/asus::kbd_backlight/brightness'
    STATE = '/tmp/set-keyboard-backlight.state'

    ACTIONS = {
        'up',
        'down',
    }

    MIN_VALUE = 0
    MAX_VALUE = 3

    def __init__(self):
        self.dev = pathlib.Path(self.DEV)

    async def action(self, action):
        match action:
            case 'up':
                brightness = min(self.MAX_VALUE, self.current_brightness() + 1)
            case 'down':
                brightness = max(self.MIN_VALUE, self.current_brightness() - 1)
        self.set_brightness(brightness)

    def current_brightness(self):
        return int(self.dev.read_text())

    def set_brightness(self, value):
        self.dev.write_text(str(value))


class DisplayBacklight:
    MAX_VALUE = 100
    MIN_VALUE = 1

    STEP = 10

    ACTIONS = {
        'up',
        'down',
    }

    def __init__(self, dbus):
        self.dbus = dbus
        self.dbus_replaces_id = None

    async def action(self, action):
        backlight = round(await self.get_backlight())
        if action == 'up':
            new_backlight = min(self.MAX_VALUE, backlight + self.STEP)
        elif action == 'down':
            new_backlight = max(self.MIN_VALUE, backlight - self.STEP)
        if self.MIN_VALUE < new_backlight < self.MAX_VALUE:
            new_backlight = round_to_nearest(new_backlight, self.STEP)
        print(backlight, new_backlight)
        if new_backlight != backlight:
            await self.set_backlight(new_backlight)

        hints = {
            'x-dunst-stack-tag': 'hotkey-daemon-display-backlight',
            'value': new_backlight,
            'transient': 1,
            'urgency': 1,
        }
        self.dbus_replaces_id = self.dbus.notify(
            summary='Backlight',
            hints=hints,
            replaces_id=self.dbus_replaces_id)

    @staticmethod
    async def set_backlight(value):
        proc = await asyncio.create_subprocess_exec(
            'light', '-S', str(value))
        await proc.communicate()
        if proc.returncode != 0:
            raise RuntimeError

    @staticmethod
    async def get_backlight():
        proc = await asyncio.create_subprocess_exec(
            'light',
            stdout=asyncio.subprocess.PIPE)
        stdout, _ = await proc.communicate()
        if proc.returncode != 0:
            raise RuntimeError
        return float(stdout.decode().strip())


@contextlib.contextmanager
def open_fifo():
    fifo_path = pathlib.Path(FIFO_PATH)
    try:
        fifo_path.unlink()
    except FileNotFoundError:
        pass
    os.mkfifo(fifo_path)
    with open(fifo_path, 'r') as fifo:
        yield fifo


def cleanup_lingering_predecessors():
    pid = os.getpid()
    for proc in psutil.process_iter(['pid', 'cmdline']):
        if proc.pid == pid:
            continue
        for arg in proc.cmdline():
            if 'i3-hotkey-daemon' in arg or 'i3-hotkey-client' in arg:
                os.kill(proc.pid, 9)
                break


async def action_loop():
    cleanup_lingering_predecessors()

    dbus_notifier = DBusNotifier()
    action_types = {
        'display-backlight': DisplayBacklight(dbus_notifier),
        'keyboard-backlight': KeyboardBacklight(),
        'touchpad': Touchpad(dbus_notifier),
        'volume-input': VolumeInput(dbus_notifier),
        'volume-output': VolumeOutput(dbus_notifier),
    }

    while True:
        with open_fifo() as fifo:
            for line in fifo:
                action_type, action = line.split()
                print(action_type, action)
                try:
                    await action_types[action_type].action(action)
                except Exception as e:
                    print(e, file=sys.stderr)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--loop', action='store_true')
    args = parser.parse_args()

    if args.loop:
        asyncio.run(action_loop())
    else:
        subprocess.Popen(['i3-hotkey-daemon', '--loop'])


if __name__ == '__main__':
    main()
