#!/usr/bin/env python
import i3ipc

conn = i3ipc.Connection()

primary_output = None
secondary_outputs = []

commands = []
for output in conn.get_outputs():
    name = output.name
    if output.active:
        if output.primary:
            primary_output = name
        else:
            secondary_outputs.append(name)
        conn.command(f'focus output {name}; workspace {name}')

conn.command(f'focus output {primary_output}')

for workspace in conn.get_workspaces():
    name = workspace.name
    if name not in (workspace.output, primary_output):
        conn.command(
            f'workspace {name}; move workspace to output {primary_output}')

for output, i in zip(sorted(secondary_outputs), range(10, 0, -1)):
    conn.command(f'workspace {i}; move workspace to {output}')

conn.command(f'focus output {primary_output}')
conn.command('workspace 1')
