#!/usr/bin/env sh
set -x
already_running() {
    i3-msg -t get_tree | jq | grep '"title": "i3-scratchpad"'
}
if ! already_running; then
    i3-msg "exec alacritty --title i3-scratchpad --command zsh -ic 'notes todo.md'" 
    # wait for the window to show
    while true; do
        if already_running; then
            break
        fi
        sleep 0.25
    done
fi
i3-msg 'scratchpad show'
