#!/usr/bin/env python3
import argparse
import time

import i3ipc


def show_scratchpad(conn, item):
    for output in conn.get_outputs():
        if output.primary:
            break

    max_aspect = 1.6
    size_ppt = 0.8

    # greater than 16:10
    if (output.rect.width / output.rect.height) > max_aspect:
        height = min(output.rect.width, output.rect.height)
        width = height * max_aspect
    else:
        width = output.rect.width
        height = output.rect.height

    width = int(width * size_ppt)
    height = int(height * size_ppt)

    item.command(
        'scratchpad show, '
        f'resize set width {width} px height {height} px, '
        'move absolute position center'
    )


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--title')
    parser.add_argument('args', nargs='+')
    args = parser.parse_args()

    title = args.title or args.args[0]

    conn = i3ipc.Connection()

    found = False
    for item in conn.get_tree().find_instanced('i3-scratchpad'):
        if item.window_title == title:
            found = True
            show_scratchpad(conn, item)
        else:
            # hide other scratchpad windows
            if item.ipc_data['output'] != '__i3':
                item.command('scratchpad show')
    if not found:
        command = [
            'exec',
            '--no-startup-id',
            'terminal',
            '--class', 'i3-scratchpad',
            '--title', title,
            *args.args,
        ]
        conn.command(' '.join(command))
        for attempt in range(1, 10):
            for item in conn.get_tree().find_instanced('i3-scratchpad'):
                if item.window_title == title:
                    show_scratchpad(conn, item)
                    return
            time.sleep(0.5)


if __name__ == '__main__':
    main()
