#!/usr/bin/env python3
import argparse
import shlex
import time

import i3ipc


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--title')
    parser.add_argument('args', nargs='+')
    args = parser.parse_args()

    title = args.title or args.args[0]

    conn = i3ipc.Connection()

    found = False
    for item in conn.get_tree().find_instanced('i3-scratchpad'):
        if item.window_title == title:
            found = True
            item.command('scratchpad show')
        else:
            if item.ipc_data['output'] != '__i3':
                item.command('scratchpad show')
    if not found:
        command = [
            'exec',
            '--no-startup-id alacritty',
            '--class i3-scratchpad',
            f'--title {title}',
            f"--command zsh -ic '{shlex.join(args.args)}'"
        ]
        conn.command(' '.join(command))
        for attempt in range(1, 10):
            for item in conn.get_tree().find_instanced('i3-scratchpad'):
                if item.window_title == title:
                    item.command('scratchpad show')
                    return
            time.sleep(0.5)


if __name__ == '__main__':
    main()
