#!/usr/bin/env python3
import subprocess

import i3ipc


def rofi(data):
    proc = subprocess.run(
        ['rofi', '-i', '-format', 'i', '-dmenu', '-p', '', '-no-tokenize'],
        input='\n'.join(data).encode(),
        stdout=subprocess.PIPE,
    )
    try:
        result = proc.stdout.decode().splitlines()[-1]
    except IndexError:
        result = None

    return result


CONN = i3ipc.Connection()
try:
    nodes = [
        node
        for node in CONN.get_tree().descendants()
        if node.type == 'con'
        and node.window_class not in ('i3bar', None)
    ]
    table = []
    for node in nodes:
        num = node.workspace().num
        if num == -1:
            num = ''
        table.append((node, '\t'.join([str(num), node.name])))
    table = sorted(table, key=lambda x: x[1])
    result = rofi(row[1] for row in table)
    if result and result != '-1':
        node = table[int(result)][0]
        CONN.command(f'[id={node.window}] focus')


finally:
    CONN.main_quit()
