#!/usr/bin/env sh
set -e

connected_outputs() {
    xrandr | grep ' connected ' | awk '{print $1}'
}

clear_existing_calibration() {
    dispwin -h 2>&1 | grep Output | awk '{print $1}' | xargs -n 1 dispwin -c -d > /dev/null 2>&1
}

show_help() {
    cat << EOF
usage: apply-display-calibration [--help] [--reset]

no args will apply display calibration automatically

    --reset     reset display calibration
    --help      show help and exit
EOF
}


apply_profile() {
    OUTPUT="$1"
    PROFILE="$2"
    for dispwin_number in $(dispwin -h 2>&1 | grep Output | awk '{print $1}'); do
        dispwin_output="$(dispwin -h 2>&1 | grep Output | awk '{print $1, $6}' | grep "^${dispwin_number} " | awk '{print $2}')"
        if [ "$dispwin_output" = "$OUTPUT" ]; then
            echo "Applying profile to ${OUTPUT}: ${PROFILE}"
            dispwin -d${dispwin_number} "$PROFILE" 2> /dev/null
        fi
    done
}


while true; do
    case "$1" in
        --help)
            show_help
            exit
            ;;
        --reset)
            clear_existing_calibration
            exit
            ;;
        *)
            clear_existing_calibration
            if [ $# -eq 2 ]; then
                PROFILE="$1"
                OUTPUT="$2"
                apply_profile "$OUTPUT" "$PROFILE"
            elif [ $# -eq 1 ]; then
                PROFILE="$1"
                for OUTPUT in $(xrandr | grep ' connected ' | awk '{print $1}'); do
                    apply_profile "$OUTPUT" "$PROFILE"
                done
            elif [ $# -eq 0 ]; then
                for OUTPUT in $(xrandr | grep ' connected ' | awk '{print $1}'); do
                    PROFILE=
                    edid_b64="$(xrandr-edid "$OUTPUT" | base64 -w0)"
                    #echo "EDID Base64: ${edid_b64}"
                    case "$edid_b64" in
                        # mars lounge - Dell U2412M
                        AP///////wAQrHqgU0RKMBEXAQOANCB46u6Vo1RMmSYPUFShCACBQIGAqUCzANHAAQEBAQEBKDyAoHCwI0AwIDYABkQhAAAaAAAA/wBZTVlIMTM0TDBKRFMKAAAA/ABERUxMIFUyNDEyTQogAAAA/QAyPR5TEQAKICAgICAgAAY=)
                            PROFILE="${DOTFILES}/icc/mars_lounge U2412M #1 2022-03-15 19-25 D6500 2.2 F-S XYZLUT+MTX.icc"
                            ;;
                        # mars office - LG 34GP83A-B
                        AP///////wAebUt31PYBAAIfAQS1UCF4n/Z1r05CqyYOUFQhCQBxQIGAgcCpwLMA0cCBANHP2qdwUNWgNFCQIDowIE8xAAAaAAAA/QAwkOHhUAEKICAgICAgAAAA/ABMRyBVTFRSQUdFQVIKAAAA/wAxMDJOVEpKM1M3MjQKAnQCAzBxIwkHB0cQBAMBHxMSgwEAAOMFwADiAGrmBgUBYWE9bRoAAAIFMJAABGE9YT1O1HDQ0KAyUDAgOgAgTzEAABoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7nASeQAAAwEUZjgBhm8N7wAvgB8AnwVFAAIACQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAuQ)
                            PROFILE="${DOTFILES}/icc/mars_office LG34GP83A-B 2022-03-15 19-52 D6500 2.2 F-S XYZLUT+MTX.icc"
                            ;;
                        # phobos - Asus Flow X13
                        AP///////wBNEB4VAAAAADEeAQSlHRJ4B95Qo1RMmSYPUFQAAAABAQEBAQEBAQEBAQEBAQEB7XuAoHCwR0AwIDYAILQQAAAY9z2AoHCwR0AwIDYAILQQAAAYAAAA/QAweJmZIAEKICAgICAgAAAA/ABMUTEzNE4xSlc1MgogAAo=)
                            PROFILE="${DOTFILES}/icc/phobos_flowx13 LQ134N1JW52 #1 2022-03-15 14-14 D6500 2.2 F-S XYZLUT+MTX.icc"
                            ;;
                        # gisual - Sceptre E275B-FPT165
                        AP///////wBOFAVsAAAAADIeAQSlPCF4O44FrU8zsCYNUFSlSwCBwIGAlQCpwLMA0cABAQEBAjqAGHE4LUAwIDUACEAhAAAaG4KAiHA4LUAYIDUAVlAhAAAeAAAA/QAwpt7ePAEKICAgICAgAAAA/ABTY2VwdHJlIE0yNwogAQECAybxSwEDAAAEEx8SAhGQIwkHB4MBAABtGgAAAgEwpQAAAAAAAIGRgIhwOBJAGCA1AFZQIQAAGPglAKBQOC1AMCBFAFZQIQAAHmYhVqpRAB4wRo8zAFZQIQAAGGYhULBRABswQHA2AFZQIQAAHgAAAAAAAAAAAAAAAAAAAAAABg==)
                            PROFILE="${DOTFILES}/icc/gisual Sceptre E275B-FPT165 D6500 2.2 F-S XYZLUT+MTX (monitor settings - red 49, green, 48, blue 49, gamma 2.2).icc"
                            ;;
                        # gisual - Sceptre E275B-FPT165
                        AP///////wBOFAVsAQAAADIeAQOAPCF4Krbgo1ZQoCcOUFS/7wCVAIGAswCBwEVoRXxhaGF8AjqAGHE4LUBYLEUAVlAhAAAeAAAA/QAwkB6gJAAKICAgICAgKkSAoHA4J0AwIDUAVlAhAAAAAAAA/ABTY2VwdHJlIE0yNwogAf4CAy7xSx8AAAQTAxICEQGQIwkHB4MBAABnAwwAIAAYRG0aAAACATCQ7QAAAAAAhm+AoHA4QEAwIDUAVlAhAAAe+CUAoFA4LUAwIDYAVlAhAAAa/n6AiHA4EkAYIDUAVlAhAAB/ZiFWqlEAHjBGjzMAVlAhAAB/AAAAAAAAAAAAVg==)
                            PROFILE="${DOTFILES}/icc/gisual Sceptre E275B-FPT165 D6500 2.2 F-S XYZLUT+MTX (monitor settings - red 49, green, 48, blue 49, gamma 2.2).icc"
                            ;;
                        # mars office - LG C2 42"
                        AP///////wAebcjAAQEBAQEfAQOAoFp4CO6Ro1RMmSYPUFShCAAxQEVAYUBxQIGA0cABAQEBCOgAMPJwWoCwWIoAQIRjAAAeb8IAoKCgVVAwIDUAQIRjAAAeAAAA/QAYeB7/dwAKICAgICAgAAAA/ABMRyBUViBTU0NSMgogAWcCA2ryV2FgdnUQHwQTBRQDAhIgISIVAV1eXz9ALAlXBxUHUFcHAWcEA20DDABAALg8LABgAQIDathdxAF4gFsCKHhtGgAAAgEoeAAAAAAAAOIAz+MFwADjBg0B4g//6wFG0ABIA3aCXm2VAAAAAAAAAAAAAAAAAAAAAAAAAAAAng==)
                            PROFILE="${DOTFILES}/icc/FINAL SDR TV SSCR2 #1 2023-02-03 12-27 D6500 2.2 M-S 3xCurve.icm"
                            ;;
                    esac

                    if [ -z "$PROFILE" ]; then
                        echo "error: no profile detected for ${OUTPUT}" >&2
                    else
                        apply_profile "$OUTPUT" "$PROFILE"
                    fi
                done
            else
                show_help
                echo error: unknown arguments >&2
                exit 1
            fi
            break
    esac
done
