#!/usr/bin/env sh
set -e

clear_existing_calibration() {
    dispwin -h 2>&1 | grep Output | awk '{print $1}' | xargs -n 1 dispwin -c -d > /dev/null 2>&1
}

show_help() {
    cat << EOF
usage: apply-display-calibration [--help] [--reset]

no args will apply display calibration automatically

    --reset     reset display calibration
    --help      show help and exit
EOF
}


while true; do
    case "$1" in
        --help)
            show_help
            exit
            ;;
        --reset)
            clear_existing_calibration
            exit
            ;;
        *)
            if [ $# -eq 1 ]; then
                if ! [ -f "$1" ]; then
                    echo 'error: profile not found' >&2
                    exit 1
                fi
                PROFILE="$1"
            elif [ $# -eq 0 ]; then
                # xrandr-edid $(xrandr-primary-output) | base64 -w0
                case "$(xrandr-edid "$(xrandr-primary-output)" | base64 -w0)" in
                    # mars lounge - Dell U2412M
                    AP///////wAQrHqgU0RKMBEXAQOANCB46u6Vo1RMmSYPUFShCACBQIGAqUCzANHAAQEBAQEBKDyAoHCwI0AwIDYABkQhAAAaAAAA/wBZTVlIMTM0TDBKRFMKAAAA/ABERUxMIFUyNDEyTQogAAAA/QAyPR5TEQAKICAgICAgAAY=)
                        PROFILE="$DOTFILES/icc/mars_lounge U2412M #1 2022-03-15 19-25 D6500 2.2 F-S XYZLUT+MTX.icc"
                        ;;
                    # mars office - LG 34GP83A-B
                    AP///////wAebUt31PYBAAIfAQS1UCF4n/Z1r05CqyYOUFQhCQBxQIGAgcCpwLMA0cCBANHP2qdwUNWgNFCQIDowIE8xAAAaAAAA/QAwkOHhUAEKICAgICAgAAAA/ABMRyBVTFRSQUdFQVIKAAAA/wAxMDJOVEpKM1M3MjQKAnQCAzBxIwkHB0cQBAMBHxMSgwEAAOMFwADiAGrmBgUBYWE9bRoAAAIFMJAABGE9YT1O1HDQ0KAyUDAgOgAgTzEAABoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7nASeQAAAwEUZjgBhm8N7wAvgB8AnwVFAAIACQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAuQ)
                        PROFILE="$DOTFILES/icc/mars_office LG34GP83A-B 2022-03-15 19-52 D6500 2.2 F-S XYZLUT+MTX.icc"
                        ;;
                    # phobos - Asus Flow X13
                    AP///////wBNEB4VAAAAADEeAQSlHRJ4B95Qo1RMmSYPUFQAAAABAQEBAQEBAQEBAQEBAQEB7XuAoHCwR0AwIDYAILQQAAAY9z2AoHCwR0AwIDYAILQQAAAYAAAA/QAweJmZIAEKICAgICAgAAAA/ABMUTEzNE4xSlc1MgogAAo=)
                        PROFILE="$DOTFILES/icc/phobos_flowx13 LQ134N1JW52 #1 2022-03-15 14-14 D6500 2.2 F-S XYZLUT+MTX.icc"
                        ;;
                esac
            else
                show_help
                echo error: unknown arguments >&2
                exit 1
            fi
            break
    esac
done


clear_existing_calibration

if [ -z "$PROFILE" ]; then
    echo "error: no profile detected" >&2
    exit 1
fi

echo "Profile: $PROFILE"
dispwin -d1 "$PROFILE" 2> /dev/null
