#!/usr/bin/env sh
notify() {
    dunstify \
        --hints=string:x-dunst-stack-tag:set-volume \
        --hints=int:transient:1 \
        'Volume' "$@"
}

res="$(pamixer --get-mute --get-volume "$@")"
set -- $res
MUTED="$1"
VOLUME="$2"

case "$MUTED" in
    true)
        notify 🔇
        ;;
    *)
        notify -h "int:value:${VOLUME}"
        ;;
esac
