#!/usr/bin/env sh
set -e

STEP=10
MINIMUM=1

current_light() {
    printf %.0f "$(light)"
}

case "$1" in
    dec)
        if [ "$(current_light)" -gt "$STEP" ]; then
            light -U "$STEP"
        else
            light -S "$MINIMUM"
        fi
        ;;
    inc)
        if [ "$(current_light)" -lt "$STEP" ]; then
            light -S "$STEP"
        else
            light -A "$STEP"
        fi
        ;;
    *)
        cat << EOF
inc:  Increase backlight by 10
dec:  Decrease backlight by 10
EOF
    exit 1
esac

dunstify \
    --hints=string:x-dunst-stack-tag:set-backlight \
    "💡 Backlight $(current_light)"
