#!/usr/bin/env sh
set -e

STEP=5

if [ -z "$1" ]; then
    if [ "$(pamixer --get-mute)" = "true" ]; then
        echo Mute
    else
        pamixer --get-volume || true
    fi
else
    if [ "$1" = "mute" ]; then
        pamixer --toggle-mute
    else
        pamixer --unmute
        pamixer --$1 $STEP
    fi

    if [ "$(pamixer --get-mute)" = "true" ]; then
        ARGS="Mute"
    else
        ARGS="-h int:value:$(pamixer --get-volume || true)"
    fi
    dunstify --replace=10002 Volume $ARGS
fi
