#!/usr/bin/env sh
set -e

STEP=10
MINIMUM=1

floor() {
    sed 's/\..*//g'
}

if [ "$1" = "dec" ]; then
    if [ "$(light | floor)" -gt "$STEP" ]; then
        light -U "$STEP"
    else
        light -S "$MINIMUM"
    fi
elif [ "$1" = "inc" ]; then
    if [ "$(light | floor)" -lt "$STEP" ]; then
        light -S "$STEP"
    else
        light -A "$STEP"
    fi
elif [ "$#" = '0' ]; then
    light | floor
    exit
else
    cat << EOF
inc:  Increase backlight by 10
dec:  Decrease backlight by 10
EOF
    exit 1
fi

dunstify \
    --hints "int:value:$(light | floor)" \
    --appname backlight \
    '💡 Backlight'
