#!/usr/bin/env python3
import argparse
import subprocess

STEP = 10
MINIMUM = 1
MAXIMUM = 100


def set_backlight(value):
    subprocess.run(['light', '-S', str(value)], check=True)


def get_backlight():
    proc = subprocess.run(['light'], stdout=subprocess.PIPE, check=True)
    # fix "ugly" values on asus flowx13 (ex. 31, 41)
    return max(round(float(proc.stdout.strip()) / 10) * 10, 1)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('value', choices=['inc', 'dec'])
    args = parser.parse_args()

    value = get_backlight()
    if args.value == 'inc':
        value = min(value + STEP, MAXIMUM)
        set_backlight(value)
    elif args.value == 'dec':
        value = max(value - STEP, MINIMUM)
        set_backlight(value)

    subprocess.Popen(
        ['dunstify',
         '--hints=string:x-dunst-stack-tag:set-backlight',
         '--hints=int:transient:1',
         f'--hints=int:value:{value}',
         'Backlight'])


if __name__ == '__main__':
    main()
