#!/usr/bin/env python3
import argparse
import pathlib
import subprocess
import sys


AUTORANDR_ROOT = pathlib.Path('~/.config/autorandr').expanduser()


def base16_theme():
    proc = subprocess.run(
        ['base16-export'],
        stdout=subprocess.PIPE,
        check=True
    )
    colors = {}
    for line in proc.stdout.decode().splitlines():
        name, color = line\
            .removeprefix('export BASE16_')\
            .replace("'", '')\
            .split('=')
        colors[name.lower()] = f'#{color}'
    assert len(colors) == 24
    return colors


def current_autorandr_profile():
    proc = subprocess.run(['autorandr', '--current'],
                          stdout=subprocess.PIPE,
                          check=True)
    if lines := proc.stdout.decode().splitlines():
        return lines[0]


def set_wallpaper_color(color):
    subprocess.run(
        ['hsetroot', '-solid', color],
        stdout=subprocess.PIPE,
        check=True)


def set_wallpaper_image(path):
    subprocess.run(
        ['hsetroot', '-cover', path],
        stdout=subprocess.PIPE,
        check=True)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--none', action='store_true')
    parser.add_argument('path', type=pathlib.Path, nargs='?')
    args = parser.parse_args()

    profile = current_autorandr_profile()
    if profile := current_autorandr_profile():
        wallpaper = AUTORANDR_ROOT / profile / 'wallpaper'
    else:
        print('warning: no autorandr profile detected', file=sys.stderr)
        wallpaper = None

    if args.none:
        if wallpaper and wallpaper.exists():
            wallpaper.unlink()

    if args.path:
        wallpaper = wallpaper or args.path
        path = args.path.absolute()
        if not path.is_file():
            raise argparse.ArgumentError('does not exist')
        if profile:
            wallpaper.unlink(missing_ok=True)
            print(wallpaper)
            wallpaper.symlink_to(path)

    if wallpaper and wallpaper.exists():
        set_wallpaper_image(wallpaper)
    else:
        colors = base16_theme()
        set_wallpaper_color(colors['background'])

        if profile:
            wallpaper.unlink(missing_ok=True)


if __name__ == '__main__':
    main()
