#!/usr/bin/env sh
set -e

CURRENT_THEME=~/.setdesktoptheme

show_help() {
    cat << EOF
usage: set-desktop-themes [--help] [--dpi DPI] [--large]

    --dpi DPI       scale theme to this DPI
    --help          show help and exit
    --medium-large  use medium-large fonts
    --large         use large fonts
EOF
}

LARGE=
MEDIUM_LARGE=

while [ $# -gt 0 ]; do
    case "$1" in
        --dpi)
            DPI="$2"
            shift
            shift
            ;;
        --large)
            LARGE=1
            shift
            ;;
        --medium-large)
            MEDIUM_LARGE=1
            shift
            ;;
        --help)
            show_help
            exit
            ;;
        *)
            echo error: unrecognized arguments >&2
            exit 1
    esac
done

if [ -z "$DPI" ]; then
    . "$CURRENT_THEME"
else
    FONT_NAME='monospace'

    if [ "$DPI" -le 138 ]; then
        BORDER_WIDTH=2
        CURSOR_SIZE=16
        DUNST_MAX_ICON_SIZE=64
        SCALING_FACTOR=1

        if [ -n "$LARGE" ]; then
            DUNST_GEOMETRY=300x5-0+28
            FONT_SIZE=14
        elif [ -n "$MEDIUM_LARGE" ]; then
            DUNST_GEOMETRY=300x5-0+28
            FONT_SIZE=12
        else
            DUNST_GEOMETRY=300x5-0+20
            FONT_SIZE=9
        fi
    else
        BORDER_WIDTH=3
        CURSOR_SIZE=48
        DUNST_MAX_ICON_SIZE=128
        SCALING_FACTOR=2

        if [ -n "$LARGE" ]; then
            DUNST_GEOMETRY=800x5-0+56
            FONT_SIZE=14
        elif [ -n "$MEDIUM_LARGE" ]; then
            DUNST_GEOMETRY=800x5-0+56
            FONT_SIZE=12
        else
            DUNST_GEOMETRY=800x5-0+44
            FONT_SIZE=10
        fi
    fi

    # save settings
    cat > "$CURRENT_THEME" << EOF
BORDER_WIDTH="$BORDER_WIDTH"
CURSOR_SIZE="$CURSOR_SIZE"
DPI="$DPI"
DUNST_GEOMETRY="$DUNST_GEOMETRY"
DUNST_MAX_ICON_SIZE="$DUNST_MAX_ICON_SIZE"
FONT_NAME="$FONT_NAME"
FONT_SIZE="$FONT_SIZE"
SCALING_FACTOR="$SCALING_FACTOR"
EOF
fi

# changing org.gnome.desktop.interface cursor-size after xrdb steps
# fucks up i3's scaling...
gsettings set org.gnome.desktop.interface cursor-size "$CURSOR_SIZE"
gsettings set org.gnome.desktop.interface scaling-factor "$SCALING_FACTOR"

# Xft/DPI: needed for Qt5 applications
gsettings set org.gnome.settings-daemon.plugins.xsettings overrides \
    "{'Gdk/WindowScalingFactor': <$SCALING_FACTOR>, 'Gtk/CursorThemeSize': <$CURSOR_SIZE>, 'Xft/DPI': <$((${DPI}*1024))>}"

# set default base16 theme
if ! [ -f ~/.base16_theme ]; then
    ln -s ~/.local/share/base16-shell/scripts/base16-classic-dark.sh ~/.base16_theme
fi

# update xresources
COLORS="$(base16-xresources)"
BACKGROUND_COLOR="$(echo "$COLORS" | grep background | awk '{print substr($2, 2, 8)}')"

xrdb << EOF
*facename: ${FONT_NAME}
*fontsize: ${FONT_SIZE}
*font: xft:${FONT_NAME}:size=${FONT_SIZE}:antialias=true:dpi=${DPI}
*boldFont:

Xft.dpi: ${DPI}

Xcursor.size: ${CURSOR_SIZE}
${COLORS}
EOF

mkdir -p ~/.config/rofi
eval "$(base16-export)"
cat > ~/.config/rofi/config.rasi << EOF
configuration {
    dpi: ${DPI};
    font: "${FONT_NAME} ${FONT_SIZE}";
}

window {
    border: ${BORDER_WIDTH};
    width: 50em;
}

listview {
    scrollbar: false;
}

* {
    background:                     ${BASE16_BACKGROUND};
    border-color:                   ${BASE16_COLOR19};
    foreground:                     ${BASE16_FOREGROUND};
    lightbg:                        var(background);
    selected-normal-background:     var(border-color);
    selected-normal-foreground:     var(foreground);
    separatorcolor:                 var(background);
}
EOF

xrandr --dpi "$DPI"

alacritty-config-reload

mkdir -p ~/.config/alacritty
cat > ~/.config/alacritty/alacritty.yml << EOF
env:
    TERM: screen-256color
font:
  normal:
    family: ${FONT_NAME}
  size: ${FONT_SIZE}
colors:
  primary:
    background: '0x${BACKGROUND_COLOR}'
EOF

hsetroot -solid "$BASE16_BACKGROUND"

if pidof i3 > /dev/null; then
    i3 restart > /dev/null 2>&1 || true
fi

pkill -9 dunst || true
dunst \
    -font "$FONT_NAME $FONT_SIZE" \
    -frame_width "$BORDER_WIDTH" \
    -max_icon_size "$DUNST_MAX_ICON_SIZE" \
    -geometry "$DUNST_GEOMETRY" > /dev/null 2>&1 &

if [ -d ~/.config/sway ]; then
    base16-sway-colors > ~/.config/sway/colors
fi
if pidof sway > /dev/null; then
    swaymsg reload
fi
