#!/usr/bin/env sh
set -e

MODE="$1"


phobos() {
    if [ -z "$MODE" ]; then
        MODE=internal
    fi

    xrandr-custom-resolution eDP1 1600 900 60
    xrandr-custom-resolution eDP1 1280 720 60

    case "$MODE" in
        internal)
            xrandr \
                --output DP1 --off \
                --output DP2 --off \
                --output eDP1 --primary --mode 3200x1800 --pos 0x0 --rotate normal
            set-desktop-themes --dpi 192
            apply-display-calibration
            ;;
        internal-half)
            xrandr \
                --output DP1 --off \
                --output DP2 --off \
                --output eDP1 --primary --mode 1600x900 --pos 0x0 --rotate normal
            set-desktop-themes --dpi 138
            apply-display-calibration
            ;;
        internal-720)
            xrandr \
                --output DP1 --off \
                --output DP2 --off \
                --output eDP1 --primary --mode 1280x720 --pos 0x0 --rotate normal
            set-desktop-themes --dpi 96
            apply-display-calibration
            ;;
        *)
            cat << EOF
Options:
- internal
- internal-half
- internal-720
EOF
            exit 1
            ;;
    esac
}


mars() {
    if [ -z "$MODE" ]; then
        MODE=desktop
    fi

    DESKTOP_SINK='alsa_output.usb-Schiit_Audio_USB_Modi_Device-00.iec958-stereo'
    TV_SINK="$(pactl list sinks short | awk '{print $2}' | grep alsa_output.pci-0000_01_00.1.hdmi)"

    case "$MODE" in
        desktop)
            paswitch "$DESKTOP_SINK" || true
            xrandr \
                --output DP-0 --off \
                --output DP-1 --off \
                --output DP-2 --off \
                --output DP-3 --off \
                --output DP-5 --off \
                --output DVI-I-0 --off \
                --output DVI-I-1 --off \
                --output HDMI-0 --off \
                --output DP-4 --primary --mode 3440x1440 --refresh 144 --pos 0x0 --rotate normal
            set-desktop-themes --dpi 96
            apply-display-calibration --reset
            ;;
        tv)
            paswitch "$TV_SINK" || true
            xrandr \
                --output DP-0 --off \
                --output DP-1 --off \
                --output DP-2 --off \
                --output DP-3 --off \
                --output DP-4 --off \
                --output DP-5 --off \
                --output DVI-I-0 --off \
                --output DVI-I-1 --off \
                --output HDMI-0 --primary --mode 3840x2160 --pos 0x0 --rotate normal
            set-desktop-themes --dpi 192 --large
            apply-display-calibration --reset
            ;;
        tv-half)
            paswitch "$TV_SINK" || true
            xrandr \
                --output DP-0 --off \
                --output DP-1 --off \
                --output DP-2 --off \
                --output DP-3 --off \
                --output DP-4 --off \
                --output DP-5 --off \
                --output DVI-I-0 --off \
                --output DVI-I-1 --off \
                --output HDMI-0 --primary --mode 1920x1080 --pos 0x0 --rotate normal
            set-desktop-themes --dpi 96 --large
            apply-display-calibration --reset
            ;;
        *)
            cat << EOF
Options:
- desktop
- tv
- tv-half
EOF
            exit 1
            ;;
    esac
}


deimos() {
    if [ -z "$MODE" ]; then
        if [ -z "$(xrandr | grep '^DP1 connected ')" ]; then
            MODE=internal
        else
            MODE=external
        fi
    fi
    case "$MODE" in
        internal)
            xrandr \
                --output DP1 --off \
                --output HDMI1 --off \
                --output HDMI2 --off \
                --output eDP1 --primary --mode 720x1280 --pos 0x0 --rotate right
            set-desktop-themes --dpi 96 --large
            apply-display-calibration
            xinput set-prop \
                "$(xinput | grep Goodix | grep pointer | awk '{print $6}' | cut -d= -f2)" \
                'Coordinate Transformation Matrix' 0 1 0 -1 0 1 0 0 1
            ;;
        external)
            xrandr \
                --output DP1 --primary --mode 1920x1200 --pos 0x0 \
                --output HDMI1 --off \
                --output HDMI2 --off \
                --output eDP1 --off
            set-desktop-themes --dpi 96
            apply-display-calibration --reset
            ;;
        *)
            cat << EOF
Options:
- internal
- external
EOF
            exit 1
            ;;
    esac
}

apollo() {
    xrandr \
        --output DP1 --off \
        --output DP2 --off \
        --output HDMI1 --off \
        --output HDMI2 --off \
        --output VIRTUAL1 --off \
        --output eDP1 --primary --mode 1800x1200
    set-desktop-themes --dpi 96 --large
    apply-display-calibration
}


hostname="$(uname -n)"
case "$hostname" in
    "deimos")
        deimos
        ;;
    "mars")
        mars
        ;;
    "phobos")
        phobos
        ;;
    apollo)
        apollo
        ;;
    *)
        echo "WARN: Host '$hostname' undefined" >&2
        set-desktop-themes --dpi 96
        ;;
esac
