#!/usr/bin/env sh
notify() {
    dunstify --replace=10003 '🎙 Microphone' "$@"
}

MUTED="$(pamixer --get-mute --toggle --default-source)"
case "$MUTED" in
    true)
        notify 🚫
        ;;
    *)
        notify Recording
        ;;
esac
