#!/usr/bin/env sh
notify() {
    dunstify \
        --appname volume \
        --replace 10003 \
        '🎙 Microphone' "$@"
}

MUTED="$(pamixer --get-mute --toggle --set-volume 100 --default-source)"
case "$MUTED" in
    true)
        notify 🚫
        ;;
    *)
        notify Recording
        ;;
esac
