#!/usr/bin/env sh
notify() {
    dunstify --replace=10003 '🎙 Microphone' "$@"
}

MUTED="$(pamixer --get-mute --toggle --default-source)"
if [ "$MUTED" = 'true' ]; then
    notify 🚫
else
    notify Recording
fi

