#!/usr/bin/env sh
xrandr --output DisplayPort-0 --mode 2048x1536_120 --scale 0.5x0.5 --filter nearest

set-desktop-themes --dpi 96

pactl-set-only \
    --profile alsa_card.usb-Schiit_Audio_I_m_Fulla_Schiit-00 output:iec958-stereo

i3-move-ws
