#!/bin/sh
DEVICE_ID=$(xinput list --id-only 'DLL0665:01 06CB:76AD Touchpad')

xinput --set-prop $DEVICE_ID 'libinput Accel Speed' 1
xinput --set-prop $DEVICE_ID 'libinput Tapping Enabled' 1 
xinput --set-prop $DEVICE_ID 'libinput Natural Scrolling Enabled' 1 
xinput --set-prop $DEVICE_ID 'libinput Middle Emulation Enabled' 1 
