#!/bin/sh

REMOTE_MOUNT=/mnt/storage

if mount | awk '{print $3}' | grep "$REMOTE_MOUNT$" > /dev/null ; then
    rsync -av --progress --delete --exclude Library --exclude MP3_192 $REMOTE_MOUNT/Audio ~
    rsync -av --progress --delete $REMOTE_MOUNT/Books ~
else
    echo Not mounted - $REMOTE_DIR
fi
