#!/bin/sh

REMOTE_MOUNT=/mnt/sol

if mount | awk '{print $3}' | grep "$REMOTE_MOUNT$" > /dev/null ; then
    rsync -av --progress --delete --exclude Library $REMOTE_MOUNT/storage1/Audio ~
else
    echo Not mounted - $REMOTE_DIR
fi
