#!/bin/sh

if [[ $(xrandr | grep \* | cut -d' ' -f4) == "3200x1800" ]] 
then
    RESOLUTION=1280x720
    DPI=96
else 
    RESOLUTION=3200x1800
    DPI=192
fi

xrandr \
    --output eDP-1 --mode $RESOLUTION --pos 0x0 --rotate normal \
    --output HDMI-1 --off \
    --output DP-1 --off \
    --output VIRTUAL1 --off
set-x-dpi $DPI
