#!/bin/sh
PROPERTY='libinput Disable While Typing Enabled'

xinput list --id-only | while read id; do
    value=$(xinput list-props $id | grep "$PROPERTY (" | awk '{print $NF}')

    if [[ ! -z $value ]]; then
        if [[ ! -z $1 ]]; then
            value=$1
        elif [[ $value == '0' ]]; then
            value=1
        else
            value=0
        fi
        xinput --set-prop $id "$PROPERTY" $value
    fi
done
