#!/usr/bin/env sh
set -e
xmodmap-caps-to-esc

TOUCHPAD_ID=$(xinput list --id-only 'DLL0665:01 06CB:76AD Touchpad')

xinput --set-prop $TOUCHPAD_ID 'libinput Accel Speed' 0.5
xinput --set-prop $TOUCHPAD_ID 'libinput Tapping Enabled' 1
xinput --set-prop $TOUCHPAD_ID 'libinput Natural Scrolling Enabled' 1
xinput --set-prop $TOUCHPAD_ID 'libinput Middle Emulation Enabled' 1
