#!/usr/bin/env sh
set -x
if [ $# != '4' ]; then
    echo "usage: $0 OUTPUT WIDTH HEIGHT REFRESH" >&2
    exit 1
fi

cvt_output=$(cvt $2 $3 $4 | tail -n 1 | awk '{$1=$2=""}1')
mode_name="$2x$3_$4"
echo "$mode_name"

xrandr --rmmode "$mode_name"
xrandr --newmode $mode_name $cvt_output
xrandr --addmode $1 $mode_name
