#!/usr/bin/env sh
launch() {
    if [ -n "$I3SOCK" ]; then
        i3-msg -t command exec -- "$*"
    else
        exit 1
    fi
}


find_executables() {
    IFS=:
    for dir in $PATH; do
        for file in "$dir"/*; do
            if [ -f "$file" ] && [ -x "$file" ]; then
                echo "${file##*/}"
            fi
        done
    done
}

. ~/.base16_theme
command="$(IFS=: find_executables | sort -u | fzf --exact --no-extended -i --layout=reverse --print-query)"
ret=$?
command="$(echo "$command" | tail -n 1)"
case $ret in
    1)
        launch "$(shlex open "https://duckduckgo.com/?q=$command")"
        ;;
    0)
        launch "$command"
        exit
        ;;
    *)
        exit $ret
esac
