#!/usr/bin/env sh
launch() {
    if [ -n "$I3SOCK" ]; then
        echo "$@"
        i3-msg -t command exec -- "$@"
    else
        exit 1
    fi
}


find_executables() {
    IFS=:
    for dir in $PATH; do
        for file in "$dir"/*; do
            if [ -f "$file" ] && [ -x "$file" ]; then
                echo "${file##*/}"
            fi
        done
    done
}

if [ $# -eq 0 ]; then
    . ~/.base16_theme
    IFS=: find_executables | sort -u | fzf --exact --no-extended -i --layout=reverse --print-query | tail -n 1 | xargs -r alacritty-launcher > /dev/null 2>&1
else
    case "$1" in
        /*)
            all="$*"
            launch open "https://duckduckgo.com/?q=${all#/}"
            ;;
        *)
            launch "$@"
    esac
fi
