#!/usr/bin/env sh
for alacritty_pid in $(pgrep -u "$(whoami)" -x alacritty); do
    for zsh_pid in $(pgrep -u "$(whoami)" -x zsh -P "$alacritty_pid"); do
        zsh_tty="$(ps hotty "$zsh_pid")"
        if [ "$(echo "$zsh_tty" | cut -c1-3)" = 'pts' ]; then
            export TERM="$(strings /proc/${zsh_pid}/environ | grep '^TERM=' | cut -d = -f2)"
            export TMUX="$(strings /proc/${zsh_pid}/environ | grep '^TMUX=' | cut -d = -f2)"
            printf '%s' "$(sh ~/.base16_theme)" > "/dev/$zsh_tty"
        fi
    done
done
