#!/usr/bin/env sh
http_request() {
    curl -v "http://127.0.0.1${1}"
}

case "$1" in
    volume-up)
        http_request /volume/up
        ;;
    volume-down)
        http_request /volume/down
        ;;
    volume-mute-toggle)
        http_request /volume/mute/toggle
        ;;
    power-toggle)
        http_request /power/toggle
        ;;
    *)
        echo 'usage: (power-toggle|volume-up|volume-down|volume-mute-toggle)' >&2
        exit 1
esac
