#!/usr/bin/env sh
set-desktop-themes --dpi 96

pactl set-card-profile alsa_card.pci-0000_0b_00.1 off
pactl set-card-profile alsa_card.pci-0000_0d_00.4 off
pactl set-card-profile alsa_card.usb-Schiit_Audio_USB_Modi_Device-00 off
pactl set-card-profile alsa_card.usb-audio-technica_AT2020USB_-00 off

pactl set-card-profile alsa_card.usb-C-Media_Electronics_Inc._USB_Audio_Device-00 output:analog-stereo

apply-display-calibration
i3-move-ws
