#!/usr/bin/env sh
SESSION="python-lmk-$$"

trap "tmux kill-session -t $SESSION 2> /dev/null" EXIT HUP

if [ "$(tmux display-message -p '#S' 2> /dev/null)" = "$TMUX_SESSION" ]; then
    if [ -z "$1" ]; then
        LMK_FILE=$(mktemp --suffix='.py')
        trap "rm -f "$LMK_FILE"" EXIT
        mkdir -p "$(dirname "$LMK_FILE")"
    else
        LMK_FILE="$1"
    fi
    touch "$LMK_FILE"

    if [ "$1" = '-p' ]; then
        PYTHON_BIN="$2"
        shift
        shift
    else
        PYTHON_BIN=python3
    fi

    tmux split-window -h "lmk $PYTHON_BIN $LMK_FILE"

    tmux select-pane -l

    $EDITOR $LMK_FILE

    tmux kill-session -t $TMUX_SESSION
else
    unset TMUX

    if [ -n "$VIRTUAL_ENV" ]; then
        tmux new-session -d -s $SESSION "TMUX_SESSION="$SESSION" VIRTUAL_ENV="$VIRTUAL_ENV" $0 "$@""
    else
        tmux new-session -d -s $SESSION "TMUX_SESSION="$SESSION" $0 "$@""
    fi
    tmux set-option -t $SESSION status off
    tmux attach-session -t $SESSION > /dev/null
fi
