#!/bin/bash
EDITOR=$EDITOR
PYTHON_FILE=test.py
TEMP_DIR=/tmp/python-wtchr

unset TMUX

SESSION=python-wtchr
trap "tmux kill-session -t $SESSION 2> /dev/null" SIGHUP
trap "tmux kill-session -t $SESSION 2> /dev/null" EXIT


if [[ -z $1 ]]; then
    PYTHON_BIN=python3
else
    PYTHON_BIN=$1
fi

if [[ -n $VIRTUAL_ENV ]]; then
    PYTHON_BIN=python
fi

mkdir -p $TEMP_DIR
cd $TEMP_DIR

build_venv() {
    if [[ ! $(test -d env) ]] ; then
        virtualenv -p $PYTHON_BIN env
    fi
    . env/bin/activate
}

while getopts 'v' flag; do
    case "${flag}" in
        v) build_venv ;;
    esac
done

if [ ! -f $PYTHON_FILE ]; then
    cat > $PYTHON_FILE<<EOF
from pprint import pprint


EOF
fi

if [[ $(tmux display-message -p '#S' 2> /dev/null) == $SESSION ]]; then
    tmux split-window -h "wtchr $PYTHON_BIN $PYTHON_FILE"
    tmux select-pane -l
    $EDITOR $PYTHON_FILE
else
    tmux new-session -d -s $SESSION $0 $@
    tmux set-option -t $SESSION status off
    tmux attach-session -t $SESSION > /dev/null
fi
