#!/bin/bash
EDITOR=$EDITOR
PYTHON_FILE=test.py
TEMP_DIR=/tmp/python-wtchr
SESSION=python-wtchr

trap "tmux kill-session -t $SESSION 2> /dev/null" SIGHUP
trap "tmux kill-session -t $SESSION 2> /dev/null" EXIT

if [[ -n $VIRTUAL_ENV ]]; then
    PYTHON_BIN=python
elif [[ -z $1 ]]; then
    PYTHON_BIN=python3
else
    PYTHON_BIN=$1
fi

mkdir -p $TEMP_DIR
cd $TEMP_DIR

touch $PYTHON_FILE

if [[ $(tmux display-message -p '#S' 2> /dev/null) == $SESSION ]]; then
    tmux split-window -h "wtchr -x $PYTHON_BIN $PYTHON_FILE"
    tmux select-pane -l
    $EDITOR $PYTHON_FILE &

    # fixes occasional NeoVim display corruption
    tmux select-layout even-horizontal

    wait
else
    unset TMUX
    tmux new-session -d -s $SESSION $0 "$@"
    tmux set-option -t $SESSION status off
    tmux attach-session -t $SESSION > /dev/null
fi
