#!/bin/bash
EDITOR="$EDITOR -n"
LMK_DIR=/tmp/python-lmk
PYTHON_FILE=$LMK_DIR/test.py
SESSION=python-lmk

trap "tmux kill-session -t $SESSION 2> /dev/null" SIGHUP
trap "tmux kill-session -t $SESSION 2> /dev/null" EXIT

if [[ -n $VIRTUAL_ENV ]]; then
    PYTHON_BIN=python
elif [[ -z $1 ]]; then
    PYTHON_BIN=python3
else
    PYTHON_BIN=$1
fi

if [[ $(tmux display-message -p '#S' 2> /dev/null) == $SESSION ]]; then
    cd $LMK_DIR
    pwd
    tmux split-window -h "lmk $PYTHON_BIN $PYTHON_FILE"
    tmux select-pane -l
    $EDITOR $PYTHON_FILE
else
    mkdir -p $LMK_DIR
    # prevent lmk python from whining
    touch $PYTHON_FILE

    unset TMUX
    tmux new-session -d -s $SESSION $0 "$@"
    tmux set-option -t $SESSION status off
    tmux attach-session -t $SESSION > /dev/null
fi
