#!/bin/bash
EDITOR="$EDITOR -n"
PYTHON_FILE=/tmp/python-wtchr/test.py
WTCHR_DIR=$(dirname $PYTHON_FILE)
SESSION=python-wtchr

trap "tmux kill-session -t $SESSION 2> /dev/null" SIGHUP
trap "tmux kill-session -t $SESSION 2> /dev/null" EXIT

if [[ -n $VIRTUAL_ENV ]]; then
    PYTHON_BIN=python
elif [[ -z $1 ]]; then
    PYTHON_BIN=python3
else
    PYTHON_BIN=$1
fi

if [[ $(tmux display-message -p '#S' 2> /dev/null) == $SESSION ]]; then
    tmux split-window -h "wtchr -p $WTCHR_DIR -x $PYTHON_BIN $PYTHON_FILE"
    tmux select-pane -l
    $EDITOR $PYTHON_FILE &

    # fixes occasional NeoVim display corruption
    tmux select-layout even-horizontal

    wait
else
    mkdir -p $WTCHR_DIR
    # prevent wtchr python from whining
    touch $PYTHON_FILE

    unset TMUX
    tmux new-session -d -s $SESSION $0 "$@"
    tmux set-option -t $SESSION status off
    tmux attach-session -t $SESSION > /dev/null
fi
