#!/usr/bin/env bash

pane_command() {
    echo "echo $2 && $1 $2 && echo Press enter to exit ... && read -s"
}

if [ -z "$2" ]; then
    echo "No arguments supplied for command."
    exit 1
elif [ -n "$TMUX" ]; then
    clear

    command="$1"
    shift

    num_args=$#

    first_arg="$1"
    shift

    for i in $(seq 1 $#); do
        tmux split-window -h "$(pane_command "$command" "$1")"
        shift
    done

    if [ $num_args = 2 ]; then
        tmux select-layout even-horizontal
    elif [ $num_args = 3 ]; then
        tmux select-layout even-vertical
    else
        tmux select-layout tiled
    fi

    tmux set-window-option synchronize-panes on

    eval $(pane_command "$command" "$first_arg")
    tmux set-window-option synchronize-panes off
    clear
else
    tmux new-session -d -s "sync$$" "$0" "$@"
    tmux attach-session -t "sync$$"
fi
