#!/bin/bash
EDITOR=$EDITOR
PYTHON_BIN=python3
PYTHON_FILE=test.py
TEMP_DIR=/tmp/python-wtchr

mkdir -p $TEMP_DIR
cd $TEMP_DIR

build_venv() {
    if [[ ! $(test -d env) ]] ; then
        virtualenv -p $PYTHON_BIN env
    fi
    . env/bin/activate
}

while getopts 'v' flag; do
    case "${flag}" in
        v) build_venv ;;
    esac
done

touch $PYTHON_FILE
tmux split-window -h "wtchr $PYTHON_BIN $PYTHON_FILE"
tmux select-pane -l
$EDITOR $PYTHON_FILE
tmux select-pane -l
tmux kill-pane
