#!/bin/bash
TEMP_DIR=/tmp/python-wtchr
mkdir -p $TEMP_DIR
cd $TEMP_DIR

PYTHON_BIN=python3

build_venv() {
    if [[ ! $(test -d env) ]] ; then
        $PYTHON_BIN -m venv env
    fi
    . env/bin/activate
}

while getopts 'v' flag; do
    case "${flag}" in
        v) build_venv ;;
    esac
done

PYTHON_FILE=test.py
touch $PYTHON_FILE
tmux split-window -h "wtchr $PYTHON_BIN $PYTHON_FILE"
tmux select-pane -l
nvim $PYTHON_FILE
tmux select-pane -l
tmux kill-pane
