#!/usr/bin/env sh
if [ "$1" != '-n' ] || [ $# != 3 ]; then
    echo usage: $(basename "$0") -n NAMESPACE DEPLOYMENT >&2
    exit 1
fi
NAMESPACE="$2"
DEPLOYMENT="$3"

exec tmux-sync "KUBECONFIG="$KUBECONFIG" kubectl podshell -n mobile" $(kubectl deploymentpods -n "${NAMESPACE}" "${DEPLOYMENT}")
