#!/bin/bash
set -e

dispwin -h |& grep Output | awk '{print $1}' | xargs -n 1 dispwin -c -d

if [[ $1 == 'clear' ]]; then
    exit
fi

case "$HOSTNAME" in
    "mars")
        dispwin -h |& grep Output | \
        awk '{print $1}' | \
        xargs -I % -n 1 dispwin -c -d% $DOTFILES_DIR/icc/dell_u2412m_custom.icc
        ;;
    "phobos")
        dispwin -d1 $DOTFILES_DIR/icc/xps13_phobos.icc
        ;;
    *)
esac
