#!/usr/bin/env python3
import sys
import os


attribute_map = {'color00': 'color0',
                 'color01': 'color1',
                 'color02': 'color2',
                 'color03': 'color3',
                 'color04': 'color4',
                 'color05': 'color5',
                 'color06': 'color6',
                 'color07': 'color7',
                 'color08': 'color8',
                 'color09': 'color9',
                 'color10': 'color10',
                 'color11': 'color11',
                 'color12': 'color12',
                 'color13': 'color13',
                 'color14': 'color14',
                 'color15': 'color15',
                 'color16': 'color16',
                 'color17': 'color17',
                 'color18': 'color18',
                 'color19': 'color19',
                 'color20': 'color20',
                 'color21': 'color21',
                 'color_foreground': 'foreground',
                 'color_background': 'background'}


lines = []
with open(os.path.expanduser('~/.base16_theme')) as f:
    for l in f:
        if l.startswith('color'):
            lines.append(l.strip())

attributes = {}
for l in lines:
    attribute, remaining = l.split('=')
    color = remaining.split()[0].replace('"', '').replace('$', '').replace('/', '')

    if color.startswith('color'):
        color = attributes[color]
    else:
        attributes[attribute] = color


temp_file = sys.argv[1]
with open(os.path.expanduser(temp_file), 'w') as f:
    for attribute, color in attributes.items():
        f.write(f'*{attribute_map[attribute]} : #{color}\n')
