#!/bin/sh

BACKUP_ROOT="$DOTFILES_DIR"/desktop

sync_file() {
    if [ -f "$target" ]; then
        echo Syncing "$target"
        sudo cp "$source" "$target"
    fi
}

for source in $(find "$BACKUP_ROOT" -type f); do
    target=${source#$BACKUP_ROOT}
    sync_file "$source" "$target"
done
