#!/usr/bin/env sh

CONFIG_DIR="$HOME/.config/i3"

rm -rf "$CONFIG_DIR"
mkdir -p "$CONFIG_DIR"
cat "$DOTFILES/i3/general" > "$CONFIG_DIR/config"

HOST_CONFIG="$DOTFILES/i3/$(uname -n)"
if [ -f "$HOST_CONFIG" ]; then
    cat $HOST_CONFIG >> $CONFIG_DIR/config
fi
