#!/bin/sh

CONFIG_DIR=~/.config/i3

rm -rf $CONFIG_DIR
mkdir -p $CONFIG_DIR
cat "$DOTFILES"/i3/general > $CONFIG_DIR/config

HOST_CONFIG="$DOTFILES/i3/$HOSTNAME"
if [ -f "$HOST_CONFIG" ]; then
    cat $HOST_CONFIG >> $CONFIG_DIR/config
fi
