#!/bin/sh
temp_file=$(mktemp)
base16-set-xresources $temp_file
xrdb -merge $temp_file
rm $temp_file

termite-config-reload
i3 reload > /dev/null
hsetroot -solid $(xrdb -query | grep '*background' | awk '{print $2}')
