#!/bin/zsh

DPI=${1#0}

XRESOURCES_TEMP_FILE=/tmp/dpi_xresources

if [[ $DPI -le 138 ]]; then
    CURSOR_SIZE=16

    FONT_NAME=Tamzen
    FONT_SIZE=9

    ANTIALIAS=false

    BORDER_WIDTH=1

    DUNST_GEOMETRY=120x5-0+18
else
    CURSOR_SIZE=32

    FONT_NAME='DejaVu Sans Mono'
    FONT_SIZE=9

    ANTIALIAS=true

    BORDER_WIDTH=3

    DUNST_GEOMETRY=300x5-0+40
fi

    cat > $XRESOURCES_TEMP_FILE <<- EOF
*facename: ${FONT_NAME}
*fontsize: ${FONT_SIZE}
*font: xft:${FONT_NAME}:size=${FONT_SIZE}:antialias=${ANTIALIAS}:dpi=${DPI}
*boldFont:

rofi.font: ${FONT_NAME} ${FONT_SIZE}
rofi.dpi: ${DPI}
rofi.bw: ${BORDER_WIDTH}

Xft.dpi: ${DPI}

Xcursor.size: ${CURSOR_SIZE}
EOF

xrandr --dpi $DPI

xrdb $DOTFILES_DIR/xresources/general
xrdb -merge $XRESOURCES_TEMP_FILE

pkill -9 dunst
dunst \
    -font "$FONT_NAME $FONT_SIZE" \
    -frame_width $BORDER_WIDTH \
    -geometry $DUNST_GEOMETRY &

load-xresources-theme

i3 restart

rm $XRESOURCES_TEMP_FILE
