#!/bin/zsh

DPI=${1#0}

XRESOURCES_TEMP_FILE=/tmp/dpi_xresources

if [[ $DPI -le 138 ]]; then
    CURSOR_SIZE=16

    FONT_NAME=Tamzen
    FONT_SIZE=9

    ANTIALIAS=false

    BORDER_WIDTH=1

    DUNST_GEOMETRY=300x5-0+18
    DUNST_MAX_ICON_SIZE=64

    SCALING_FACTOR=1
else
    CURSOR_SIZE=48

    FONT_NAME='DejaVu Sans Mono'
    FONT_SIZE=10

    ANTIALIAS=true

    BORDER_WIDTH=3

    DUNST_GEOMETRY=800x5-0+40
    DUNST_MAX_ICON_SIZE=128

    SCALING_FACTOR=2
fi

if [[ $2 == 'large' ]]; then
    FONT_NAME='DejaVu Sans Mono'
    FONT_SIZE=14

    ANTIALIAS=true
fi

    cat > $XRESOURCES_TEMP_FILE <<- EOF
*facename: ${FONT_NAME}
*fontsize: ${FONT_SIZE}
*font: xft:${FONT_NAME}:size=${FONT_SIZE}:antialias=${ANTIALIAS}:dpi=${DPI}
*boldFont:

rofi.font: ${FONT_NAME} ${FONT_SIZE}
rofi.dpi: ${DPI}
rofi.bw: ${BORDER_WIDTH}

Xft.dpi: ${DPI}

Xcursor.size: ${CURSOR_SIZE}
EOF

xrandr --dpi $DPI

# changing org.gnome.desktop.interface cursor-size after xrdb steps
# fucks up i3's scaling...
gsettings set org.gnome.desktop.interface cursor-size $CURSOR_SIZE
gsettings set org.gnome.desktop.interface scaling-factor $SCALING_FACTOR
gsettings set org.gnome.settings-daemon.plugins.xsettings overrides \
    "{'Gdk/WindowScalingFactor': <$SCALING_FACTOR>, 'Gtk/CursorThemeSize': <$CURSOR_SIZE>}"

xrdb $XRESOURCES_TEMP_FILE

pkill -9 dunst
dunst \
    -font "$FONT_NAME $FONT_SIZE" \
    -frame_width $BORDER_WIDTH \
    -max_icon_size $DUNST_MAX_ICON_SIZE \
    -geometry $DUNST_GEOMETRY &

load-xresources-theme

i3 restart

rm $XRESOURCES_TEMP_FILE
