#!/bin/bash

LIBRARY_DIR=~/.config/mpd/library
OUTPUT=$(mpc $1 --format '%artist% - %title%')

if [[ $1 == 'toggle' ]]; then
    STATE=$(echo "$OUTPUT" | head -n 2 | tail -n 1 | awk '{print $1}')
    echo $OUTPUT
    if [[ $STATE == '[playing]' ]]; then
        SYMBOL='▶️'
    elif [[ $STATE == '[paused]' ]]; then
        SYMBOL='⏸'
    fi
elif [[ $1 == 'prev' ]]; then
    SYMBOL='⏮'
elif [[ $1 == 'next' ]]; then
    SYMBOL='⏭'
fi

INFO=$(echo "$OUTPUT" | head -n 1)

#FILE_DIR="$LIBRARY_DIR/$(dirname "$(mpc -f %file% | head -n 1)")"

#if [ -f "$FILE_DIR/front.jpg" ]; then
#    IMAGE_PATH="$FILE_DIR/front.jpg"
#elif [ -f "$FILE_DIR/front.png" ]; then
#    IMAGE_PATH="$FILE_DIR/front.png"
#fi

if [ ! -z "$IMAGE_PATH" ]; then
    ICON_ARG="--icon=$IMAGE_PATH"
else
    ICON_ARG=""
fi

#dunstify --replace=10001 "$ICON_ARG" $SYMBOL "$INFO"
dunstify --replace=10001 $SYMBOL "$INFO"
