#!/bin/bash

if [[ $1 == 'dec' ]]; then
    if [[ $(xbacklight -get) -gt 10 ]]; then
        xbacklight -dec 10
    else
        xbacklight -set 1
    fi
elif [[ $1 == 'inc' ]]; then
    if [[ $(xbacklight -get) -lt 10 ]]; then
        xbacklight -set 10
    else
        xbacklight -inc 10
    fi
else
    cat << EOF
inc:  Increase backlight by 10
dec:  Decrease backlight by 10
EOF
    exit 1
fi

dunstify Backlight -h int:value:$(xbacklight -get)
