#!/usr/bin/env sh

STEP=10
MINIMUM=1

if [ "$1" = "dec" ]; then
    if [l "$(xbacklight -get)" -gt "$STEP" ]; then
        xbacklight -dec $STEP
    else
        xbacklight -set $MINIMUM
    fi
elif [ "$1" = "inc" ]; then
    if [ "$(xbacklight -get)" -lt "$STEP" ]; then
        xbacklight -set $STEP
    else
        xbacklight -inc $STEP
    fi
else
    cat << EOF
inc:  Increase backlight by 10
dec:  Decrease backlight by 10
EOF
    exit 1
fi

dunstify Backlight -h int:value:$(xbacklight -get)
