#!/bin/bash

if [[ $1 == 'mute' ]]; then
    pamixer --toggle-mute
    notify_value=$(pamixer --get-mute)
else
    pamixer --unmute
    pamixer --$1 3
    notify_value=$(pamixer --get-volume)
fi

dunstify -t 2 "Volume: $notify_value"
