#!/usr/bin/env sh

STEP=5

if ! [ -z $BLOCK_BUTTON ]; then
    pavucontrol &
fi

if [ -z $1 ]; then
    if [ $(pamixer --get-mute) = "true" ]; then
        echo Mute
    else
        pamixer --get-volume
    fi
else
    if [ $1 = "mute" ]; then
        pamixer --toggle-mute
    else
        pamixer --unmute
        pamixer --$1 $STEP
    fi

    if [ $(pamixer --get-mute) = "true" ]; then
        ARGS="Mute"
    else
        ARGS="-h int:value:$(pamixer --get-volume)"
    fi
    dunstify --replace=10002 Volume $ARGS
fi

pkill -RTMIN+1 i3blocks
