#!/usr/bin/env sh
set -e

MODE="$1"


phobos() {
    if [ -z "$MODE" ]; then
        if [ -z "$(xrandr | grep '^DP1 connected ')" ]; then
            MODE=internal
        else
            MODE=external
        fi
    fi

    xrandr-custom-resolution eDP1 1600 900 60
    xrandr-custom-resolution eDP1 1280 720 60

    if [ "$MODE" = "internal" ]; then
        xrandr \
            --output HDMI1 --off \
            --output DP1 --off \
            --output eDP1 --primary --mode 3200x1800 --pos 0x0 --rotate normal
        set-x-dpi 192
    elif [ "$MODE" = "internal-half" ]; then
        xrandr \
            --output HDMI1 --off \
            --output DP1 --off \
            --output eDP1 --primary --mode 1600x900 --pos 0x0 --rotate normal
        set-x-dpi 138
    elif [ "$MODE" = "internal-720" ]; then
        xrandr \
            --output HDMI1 --off \
            --output DP1 --off \
            --output eDP1 --primary --mode 1280x720 --pos 0x0 --rotate normal
        set-x-dpi 96
    elif [ "$MODE" = "external" ]; then
        xrandr \
            --output HDMI1 --off \
            --output eDP1 --off \
            --output DP1 --primary --mode 1920x1200 --pos 0x0 --rotate normal
        set-x-dpi 96
    else
        printf "Options:\n- internal\n- internal-half\n- external"
        exit 1
    fi
}


mars() {
    if [ -z "$MODE" ]; then
        if [ "$(xrandr | grep -e '^DP-2 ' -e '^DP-4 ' | grep ' connected' | wc -l)" = '2' ]; then
            MODE=multi
        else
            MODE=single
        fi
    fi

    if [ "$MODE" = "single" ]; then
        xrandr \
            --output DP-0 --off \
            --output DP-1 --off \
            --output DP-2 --off \
            --output DP-3 --off \
            --output DP-5 --off \
            --output DVI-I-0 --off \
            --output DVI-I-1 --off \
            --output HDMI-0 --off \
            --output DP-4 --primary --mode 1920x1200 --pos 0x0 --rotate normal
        set-x-dpi 96
    elif [ "$MODE" = "multi" ]; then
        xrandr \
            --output DP-0 --off \
            --output DP-1 --off \
            --output DP-3 --off \
            --output DP-5 --off \
            --output DVI-I-0 --off \
            --output DVI-I-1 --off \
            --output HDMI-0 --off \
            --output DP-2 --mode 1920x1200 --pos 1920x0 --rotate normal \
            --output DP-4 --primary --mode 1920x1200 --pos 0x0 --rotate normal
        set-x-dpi 96
    elif [ "$MODE" = "tv" ]; then
        xrandr \
            --output DP-0 --off \
            --output DP-1 --off \
            --output DP-2 --off \
            --output DP-3 --off \
            --output DP-4 --off \
            --output DP-5 --off \
            --output DVI-I-0 --off \
            --output DVI-I-1 --off \
            --output HDMI-0 --primary --mode 1920x1080 --pos 0x0 --rotate normal
        set-x-dpi 96 large
    else
        printf "Options:\n- single\n- multi"
        exit 1
    fi
}


deimos() {
    if [ -z "$MODE" ]; then
        if [ -z "$(xrandr | grep '^DP1 connected ')" ]; then
            MODE=internal
        else
            MODE=external
        fi
    fi
    if [ "$MODE" = "internal" ]; then
        xrandr \
            --output DP1 --off \
            --output HDMI1 --off \
            --output HDMI2 --off \
            --output eDP1 --primary --mode 720x1280 --pos 0x0 --rotate right
        set-x-dpi 96 large
    elif [ "$MODE" = "external" ]; then
        xrandr \
            --output DP1 --primary --mode 1920x1200 --pos 0x0 \
            --output HDMI1 --off \
            --output HDMI2 --off \
            --output eDP1 --off
        set-x-dpi 96
    fi
}

hostname="$(uname -n)"
case "$hostname" in
    "deimos")
        deimos
        ;;
    "mars")
        mars
        ;;
    "phobos")
        phobos
        ;;
    *)
        echo "WARN: Host '$hostname' undefined" >&2
        set-x-dpi 96
        ;;
esac

apply-display-calibration
