#!/usr/bin/env sh
if [ $# != '4' ]; then
    echo "usage: $0 OUTPUT WIDTH HEIGHT REFRESH" >&2
    exit 1
fi

cvt_output=$(cvt $2 $3 $REFRESH | tail -n 1 | awk '{$1=$2=""}1')
mode_name="$2x$3"

xrandr --newmode $mode_name $cvt_output 2> /dev/null
xrandr --addmode $1 $mode_name
