var nw={},_gaq=[];nw.pegasus={};$(function(){nw.pegasus.common.init()});
nw.pegasus.common=function(){return{settings:{googleAnalyticsId:"UA-7094499-1"},init:function(){nw.pegasus.common.settings.cookieDomain="."+window.location.hostname.split(".").reverse()[1]+"."+window.location.hostname.split(".").reverse()[0];if(nw.pegasus.common.settings.cookieDomain==".neogamr.net")nw.pegasus.common.settings.googleAnalyticsId="UA-7094499-4";nw.pegasus.common.initGoogleAnalytics();nw.pegasus.common.setAjaxDefaults();nw.pegasus.common.setTriggers()},initGoogleAnalytics:function(){_gaq.push(["_setAccount",
nw.pegasus.common.settings.googleAnalyticsId]);_gaq.push(["_trackPageview"]);_gaq.push(["_trackPageLoadTime"]);var a=document.createElement("script");a.type="text/javascript";a.async=true;a.src=("https:"==document.location.protocol?"https://ssl":"http://www")+".google-analytics.com/ga.js";var b=document.getElementsByTagName("script")[0];b.parentNode.insertBefore(a,b)},setAjaxDefaults:function(){$("#ajax-spinner").ajaxStart(function(){$(this).fadeIn(300)}).ajaxStop(function(){$(this).fadeOut(300)});
$.ajaxSetup({cache:false,dataType:"json",timeout:1E4})},setTriggers:function(){$(".modal-close, #overlay").live("click",function(){nw.pegasus.common.closeModals()});$("#style-submit").live("click",function(){nw.pegasus.common.saveCustomizeSettings();return false});$("a").filter(function(){return this.hostname&&$(this).attr("rel")!="internal"&&this.hostname.split(":")[0]!==location.hostname.split(":")[0]||$(this).attr("rel")=="external"}).not(":has(img, mailto)").end().click(function(a){open(this.href);
a.preventDefault()});$("#news-header-short").live("click",function(){nw.pegasus.common.toggleShortnews($(this).attr("href"));return false});$("#nav-login").live("click",function(){nw.pegasus.common.launchModal("site-signin")});$("#notifications_link").live("click",function(){nw.pegasus.common.getNotifications($(this));return false});$(document).click(function(){if($("#notifications_link").hasClass("active")){$("#notifications_link").removeClass("active");$("#notifications-wrapper").hide("fast",function(){$("#notifications-list").empty()})}});
$("#notifications-wrapper").click(function(a){a.stopPropagation()})},toggleShortnews:function(a){if(nw.pegasus.common.readCookie("shortnews")=="1"){$("#news-header-short").text("Show Software News");nw.pegasus.common.setCookie("shortnews","0",365)}else{$("#news-header-short").text("Hide Software News");nw.pegasus.common.setCookie("shortnews","1",365)}nw.pegasus.mainPage.loadContentPage(a)},launchModal:function(a){$("#"+a).fadeIn(100);$("#overlay").css("opacity",0.3).fadeIn(100)},closeModals:function(){$(".modal-window, #overlay").fadeOut(200,
function(){$(".modal-trash").remove()})},ajaxError:function(a){alert("Error received: "+a)},formatString:function(a){for(i=1;i<arguments.length;i++)a=a.replace(new RegExp("\\{"+(i-1)+"\\}","g"),arguments[i]);return a},setCookie:function(a,b,d){if(d){var c=new Date;c.setTime(c.getTime()+d*24*60*60*1E3);d="; expires="+c.toGMTString()}else d="";document.cookie=a+"="+b+d+"; path=/; domain="+nw.pegasus.common.settings.cookieDomain},readCookie:function(a){a=a+"=";for(var b=document.cookie.split(";"),d=
0;d<b.length;d++){for(var c=b[d];c.charAt(0)==" ";)c=c.substring(1,c.length);if(c.indexOf(a)==0)return c.substring(a.length,c.length)}return null},eraseCookie:function(a){nw.pegasus.common.setCookie(a,"",-1)},getNotifications:function(a){if($("#notifications_link").hasClass("active")){$("#notifications_link").removeClass("active");$("#nav-notify").removeClass("notifynew");$("#notifications-wrapper").hide("fast",function(){$("#notifications-list").empty()})}else{$("#notifications_link").addClass("active");
$.getJSON(a.attr("href"),{ajax:true},function(b){if(b.status=="ok"){$("#notifications-list").html(b.data);$("#notifications-wrapper").show("fast")}else nw.pegasus.common.ajaxError(b.data)})}}}}();
