$(function(){nw.pegasus.mainPage.init()});
nw.pegasus.mainPage=function(){return{settings:{},init:function(){nw.pegasus.mainPage.initViewSelector();nw.pegasus.mainPage.initPagination();nw.pegasus.mainPage.initStyleSelector();nw.pegasus.mainPage.initLatestWidget();nw.pegasus.mainPage.initScrollNews()},initViewSelector:function(){$("#news-view li a").click(function(){$("#news-view li").removeClass("active");var b=$(this).parent();b.addClass("active");nw.pegasus.common.setCookie("view",b.attr("id"),365);b.attr("id")=="news-view-headline"&&$("#archive").empty();
nw.pegasus.mainPage.loadContentPage($(this).attr("href"));return false})},initPagination:function(){$("#main .pagination a").live("click",function(){nw.pegasus.mainPage.loadContentPage($(this).attr("href"));return false})},initStyleSelector:function(){$("#nav-style").click(function(){$.getJSON("/stylePanel/",{ajax:true},function(b){if(b.status=="ok"){$(innerShiv(b.data,false)).appendTo("body").addClass("modal-trash");nw.pegasus.common.launchModal("site-options");nw.pegasus.mainPage.initStyleSelectorBehaviors();
$("#fonts li[rel="+$("#fonts").data("default")+"]").addClass("active");$("#colors li[rel="+$("#colors").data("default")+"]").addClass("active");$("#scenes li[rel="+$("#scenes").data("default")+"]").addClass("active");nw.pegasus.common.readCookie("atwork")=="1"&&$("#disable_nsfw").attr("checked","checked");nw.pegasus.common.readCookie("shortnews")||$("#disable_shortnews").attr("checked","checked");nw.pegasus.common.readCookie("noTipsy")=="1"&&$("#disable_tipsy").attr("checked","checked");nw.pegasus.common.readCookie("fluid")==
"1"&&$("#style_fluid").attr("checked","checked");nw.pegasus.common.readCookie("noShadow")=="1"&&$("#style_noshadow").attr("checked","checked");$("#style-submit").click(function(){nw.pegasus.mainPage.saveStyleOptions();return false})}else nw.pegasus.common.ajaxError(b.data)})})},initStyleSelectorBehaviors:function(){$(".styleselector li").click(function(){$(this).hasClass("active")||$(this).parent().find("li").removeClass("active").filter(":eq("+$(this).index()+")").addClass("active")})},saveStyleOptions:function(){nw.pegasus.common.setCookie("style_font",
$("#fonts li.active").attr("rel"),365);nw.pegasus.common.setCookie("style_color",$("#colors li.active").attr("rel"),365);nw.pegasus.common.setCookie("style_scene",$("#scenes li.active").attr("rel"),365);$("#disable_nsfw").is(":checked")?nw.pegasus.common.setCookie("atwork","1",365):nw.pegasus.common.eraseCookie("atwork");$("#disable_shortnews").is(":checked")?nw.pegasus.common.setCookie("shortnews","0",365):nw.pegasus.common.eraseCookie("shortnews");$("#disable_tipsy").is(":checked")?nw.pegasus.common.setCookie("noTipsy",
"1",365):nw.pegasus.common.eraseCookie("noTipsy");$("#style_fluid").is(":checked")?nw.pegasus.common.setCookie("fluid","1",365):nw.pegasus.common.eraseCookie("fluid");$("#style_noshadow").is(":checked")?nw.pegasus.common.setCookie("noShadow","1",365):nw.pegasus.common.eraseCookie("noShadow");location.reload(true)},initLatestWidget:function(){$("#widget-latest-activity-type li").click(function(){$(this).hasClass("active")||nw.pegasus.mainPage.changeLatestWidgetTab($(this).index());return false});$("#widget-latest-activity-refresh").click(function(){nw.pegasus.mainPage.refreshLatestWidget();
$(this).addClass("active")})},refreshLatestWidget:function(){$.getJSON("/refresh",{ajax:true},function(b){if(b.status=="ok"){var c="",d="";for(a=0;a<b.data.forum.length;a++)c+=nw.pegasus.common.formatString('<li><a href="{2}" title="{0}">{1}</a></li>',b.data.forum[a][0],b.data.forum[a][1],b.data.forum[a][2]);for(a=0;a<b.data.blog.length;a++)d+=nw.pegasus.common.formatString('<li><a href="{2}" title="{0}">{1}</a></li>',b.data.blog[a][0],b.data.blog[a][1],b.data.blog[a][2]);$("#widget-latest-activity-bits div:eq(0) ul").empty().append(c);
$("#widget-latest-activity-bits div:eq(1) ul").empty().append(d)}else nw.pegasus.common.ajaxError(b.data);$("#widget-latest-activity-refresh").removeClass("active")})},changeLatestWidgetTab:function(b){$("#widget-latest-activity-bits div.active, #widget-latest-activity-type li.active").removeClass("active");$("#widget-latest-activity-type li:eq("+b+")").addClass("active");$("#widget-latest-activity-bits > div:eq("+b+")").addClass("active")},initScrollNews:function(){if(window.location.href.split("/")[3]!=
"search"){newsOffset=1;$("#ajax-appendContentPage").click(function(){nw.pegasus.mainPage.appendContentPage(document.URL)})}},appendContentPage:function(b){$("#ajax-appendContentPage").fadeIn(300);$.getJSON(b,{ajax:true,newsOffset:newsOffset},function(c){if(c.status=="ok"){$("#news-content").append(innerShiv(c.data.news,false));newsOffset++}})},loadContentPage:function(b){window.location.hash=b;$.getJSON(b,{ajax:true},function(c){if(c.status=="ok"){_gaq.push(["_trackPageview",b]);if(c.storypage==true){$(".pagination").remove();
$(".article-content").empty().append(innerShiv(c.data.news,false)).append(innerShiv(c.data.pager,false))}else{$("#news-content").empty().append(innerShiv(c.data.news,false));$(".pagination").after(innerShiv(c.data.pager,false)).remove()}b.indexOf("?page=")>-1&&$.scrollTo("#news-filter",500)}})}}}();
