(function(c){function u(h){return typeof h=="object"?h:{top:h,left:h}}var B=c.scrollTo=function(h,p,d){c(window).scrollTo(h,p,d)};B.defaults={axis:"xy",duration:parseFloat(c.fn.jquery)>=1.3?0:1,limit:true};B.window=function(){return c(window)._scrollable()};c.fn._scrollable=function(){return this.map(function(){if(!(!this.nodeName||c.inArray(this.nodeName.toLowerCase(),["iframe","#document","html","body"])!=-1))return this;var h=(this.contentWindow||this).document||this.ownerDocument||this;return/webkit/i.test(navigator.userAgent)||
h.compatMode=="BackCompat"?h.body:h.documentElement})};c.fn.scrollTo=function(h,p,d){if(typeof p=="object"){d=p;p=0}if(typeof d=="function")d={onAfter:d};if(h=="max")h=9E9;d=c.extend({},B.defaults,d);p=p||d.duration;d.queue=d.queue&&d.axis.length>1;if(d.queue)p/=2;d.offset=u(d.offset);d.over=u(d.over);return this._scrollable().each(function(){function l(C){j.animate(k,p,d.easing,C&&function(){C.call(this,h,d)})}if(h){var w=this,j=c(w),e=h,R,k={},q=j.is("html,body");switch(typeof e){case "number":case "string":if(/^([+-]=)?\d+(\.\d+)?(px|%)?$/.test(e)){e=
u(e);break}e=c(e,this);if(!e.length)return;case "object":if(e.is||e.style)R=(e=c(e)).offset()}c.each(d.axis.split(""),function(C,S){var A=S=="x"?"Left":"Top",E=A.toLowerCase(),v="scroll"+A,V=w[v],M=B.max(w,S);if(R){k[v]=R[E]+(q?0:V-j.offset()[E]);if(d.margin){k[v]-=parseInt(e.css("margin"+A))||0;k[v]-=parseInt(e.css("border"+A+"Width"))||0}k[v]+=d.offset[E]||0;if(d.over[E])k[v]+=e[S=="x"?"width":"height"]()*d.over[E]}else{A=e[E];k[v]=A.slice&&A.slice(-1)=="%"?parseFloat(A)/100*M:A}if(d.limit&&/^\d+$/.test(k[v]))k[v]=
k[v]<=0?0:Math.min(k[v],M);if(!C&&d.queue){V!=k[v]&&l(d.onAfterFirst);delete k[v]}});l(d.onAfter)}}).end()};B.max=function(h,p){var d=p=="x"?"Width":"Height",l="scroll"+d;if(!c(h).is("html,body"))return h[l]-c(h)[d.toLowerCase()]();d="client"+d;var w=h.ownerDocument.documentElement,j=h.ownerDocument.body;return Math.max(w[l],j[l])-Math.min(w[d],j[d])}})(jQuery);
(function(c,u,B){function h(b){if(!da){z=b;l();m=c(z);n=0;a.rel!=="nofollow"&&(m=c("."+C).filter(function(){return(c.data(this,k).rel||this.rel)===a.rel}),n=m.index(z),n===-1&&(m=m.add(z),n=m.length-1));if(!F){F=W=true;r.show();if(a.returnFocus)try{z.blur();c(z).one(V,function(){try{this.focus()}catch(i){}})}catch(f){}J.css({opacity:+a.opacity,cursor:a.overlayClose?"pointer":"auto"}).show();a.w=j(a.initialWidth,"x");a.h=j(a.initialHeight,"y");g.position();X&&y.bind("resize."+ea+" scroll."+ea,function(){J.css({width:y.width(),
height:y.height(),top:y.scrollTop(),left:y.scrollLeft()})}).trigger("resize."+ea);d(S,a.onOpen);ha.add(ia).hide();ja.html(a.close).show()}g.load(true)}}function p(){var b,f=q+"Slideshow_",i="click."+q,s,t;a.slideshow&&m[1]?(s=function(){Y.text(a.slideshowStop).unbind(i).bind(E,function(){if(n<m.length-1||a.loop)b=setTimeout(g.next,a.slideshowSpeed)}).bind(A,function(){clearTimeout(b)}).one(i+" "+v,t);r.removeClass(f+"off").addClass(f+"on");b=setTimeout(g.next,a.slideshowSpeed)},t=function(){clearTimeout(b);
Y.text(a.slideshowStart).unbind([E,A,v,i].join(" ")).one(i,s);r.removeClass(f+"on").addClass(f+"off")},a.slideshowAuto?s():t()):r.removeClass(f+"off "+f+"on")}function d(b,f){f&&f.call(z);c.event.trigger(b)}function l(b){a=c.extend({},c.data(z,k));for(b in a)c.isFunction(a[b])&&b.substring(0,2)!=="on"&&(a[b]=a[b].call(z));a.rel=a.rel||z.rel||"nofollow";a.href=a.href||c(z).attr("href");a.title=a.title||z.title;typeof a.href=="string"&&(a.href=c.trim(a.href))}function w(b){return a.photo||/\.(gif|png|jpg|jpeg|bmp)(?:\?([^#]*))?(?:#(\.*))?$/i.test(b)}
function j(b,f){return Math.round((/%/.test(b)?(f==="x"?y.width():y.height())/100:1)*parseInt(b,10))}function e(b,f,i){i=u.createElement("div");b&&(i.id=q+b);i.style.cssText=f||"";return c(i)}var R={transition:"elastic",speed:300,width:false,initialWidth:"600",innerWidth:false,maxWidth:false,height:false,initialHeight:"450",innerHeight:false,maxHeight:false,scalePhotos:true,scrolling:true,inline:false,html:false,iframe:false,fastIframe:true,photo:false,href:false,title:false,rel:false,opacity:0.9,
preloading:true,current:"image {current} of {total}",previous:"previous",next:"next",close:"close",open:false,returnFocus:true,loop:true,slideshow:false,slideshowAuto:true,slideshowSpeed:2500,slideshowStart:"start slideshow",slideshowStop:"stop slideshow",onOpen:false,onLoad:false,onComplete:false,onCleanup:false,onClosed:false,overlayClose:true,escKey:true,arrowKey:true,top:false,bottom:false,left:false,right:false,fixed:false,data:false},k="colorbox",q="cbox",C=q+"Element",S=q+"_open",A=q+"_load",
E=q+"_complete",v=q+"_cleanup",V=q+"_closed",M=q+"_purge",T=c.browser.msie&&!c.support.opacity,X=T&&c.browser.version<7,ea=q+"_IE6",J,r,N,D,ka,la,ma,na,m,y,x,Z,$,ia,oa,Y,aa,ba,ja,ha,a,K,L,G,H,z,n,o,F,W,da,pa,qa,g;g=c.fn[k]=c[k]=function(b,f){var i=this;b=b||{};if(!i[0]){if(i.selector)return i;i=c("<a/>");b.open=true}f&&(b.onComplete=f);i.each(function(){c.data(this,k,c.extend({},c.data(this,k)||R,b));c(this).addClass(C)});(c.isFunction(b.open)&&b.open.call(i)||b.open)&&h(i[0]);return i};g.init=function(){y=
c(B);r=e().attr({id:k,"class":T?q+(X?"IE6":"IE"):""});J=e("Overlay",X?"position:absolute":"").hide();N=e("Wrapper");D=e("Content").append(x=e("LoadedContent","width:0; height:0; overflow:hidden"),$=e("LoadingOverlay").add(e("LoadingGraphic")),ia=e("Title"),oa=e("Current"),aa=e("Next"),ba=e("Previous"),Y=e("Slideshow").bind(S,p),ja=e("Close"));N.append(e().append(e("TopLeft"),ka=e("TopCenter"),e("TopRight")),e(false,"clear:left").append(la=e("MiddleLeft"),D,ma=e("MiddleRight")),e(false,"clear:left").append(e("BottomLeft"),
na=e("BottomCenter"),e("BottomRight"))).children().children().css({"float":"left"});Z=e(false,"position:absolute; width:9999px; visibility:hidden; display:none");c("body").prepend(J,r.append(N,Z));D.children().hover(function(){c(this).addClass("hover")},function(){c(this).removeClass("hover")}).addClass("hover");K=ka.height()+na.height()+D.outerHeight(true)-D.height();L=la.width()+ma.width()+D.outerWidth(true)-D.width();G=x.outerHeight(true);H=x.outerWidth(true);r.css({"padding-bottom":K,"padding-right":L}).hide();
aa.click(function(){g.next()});ba.click(function(){g.prev()});ja.click(function(){g.close()});ha=aa.add(ba).add(oa).add(Y);D.children().removeClass("hover");J.click(function(){a.overlayClose&&g.close()});c(u).bind("keydown."+q,function(b){var f=b.keyCode;F&&a.escKey&&f===27&&(b.preventDefault(),g.close());F&&a.arrowKey&&m[1]&&(f===37?(b.preventDefault(),ba.click()):f===39&&(b.preventDefault(),aa.click()))})};g.remove=function(){r.add(J).remove();c("."+C).removeData(k).removeClass(C)};g.position=function(b,
f){function i(O){ka[0].style.width=na[0].style.width=D[0].style.width=O.style.width;$[0].style.height=$[1].style.height=D[0].style.height=la[0].style.height=ma[0].style.height=O.style.height}var s=0,t=0;y.unbind("resize."+q);r.hide();a.fixed&&!X?r.css({position:"fixed"}):(s=y.scrollTop(),t=y.scrollLeft(),r.css({position:"absolute"}));a.right!==false?(t+=Math.max(y.width()-a.w-H-L-j(a.right,"x"),0)):a.left!==false?(t+=j(a.left,"x")):(t+=Math.round(Math.max(y.width()-a.w-H-L,0)/2));a.bottom!==false?
(s+=Math.max(u.documentElement.clientHeight-a.h-G-K-j(a.bottom,"y"),0)):a.top!==false?(s+=j(a.top,"y")):(s+=Math.round(Math.max(u.documentElement.clientHeight-a.h-G-K,0)/2));r.show();b=r.width()===a.w+H&&r.height()===a.h+G?0:b||0;N[0].style.width=N[0].style.height="9999px";r.dequeue().animate({width:a.w+H,height:a.h+G,top:s,left:t},{duration:b,complete:function(){i(this);W=false;N[0].style.width=a.w+H+L+"px";N[0].style.height=a.h+G+K+"px";f&&f();setTimeout(function(){y.bind("resize."+q,g.position)},
1)},step:function(){i(this)}})};g.resize=function(b){if(F){b=b||{};b.width&&(a.w=j(b.width,"x")-H-L);b.innerWidth&&(a.w=j(b.innerWidth,"x"));x.css({width:a.w});b.height&&(a.h=j(b.height,"y")-G-K);b.innerHeight&&(a.h=j(b.innerHeight,"y"));if(!b.innerHeight&&!b.height){b=x.wrapInner("<div style='overflow:auto'></div>").children();a.h=b.height();b.replaceWith(b.children())}x.css({height:a.h});g.position(a.transition==="none"?0:a.speed)}};g.prep=function(b){function f(){a.h=a.h||x.height();a.h=a.mh&&
a.mh<a.h?a.mh:a.h;return a.h}function i(){a.w=a.w||x.width();a.w=a.mw&&a.mw<a.w?a.mw:a.w;return a.w}if(F){var s,t=a.transition==="none"?0:a.speed;x.remove();x=e("LoadedContent").append(b);x.hide().appendTo(Z.show()).css({width:i(),overflow:a.scrolling?"auto":"hidden"}).css({height:f()}).prependTo(D);Z.hide();c(o).css({"float":"none"});X&&c("select").not(r.find("select")).filter(function(){return this.style.visibility!=="hidden"}).css({visibility:"hidden"}).one(v,function(){this.style.visibility="inherit"});
s=function(){function O(){T&&r[0].style.removeAttribute("filter")}var U,P,fa,Q,ca=m.length,I,ga;!F||(ga=function(){clearTimeout(qa);$.hide();d(E,a.onComplete)},T&&o&&x.fadeIn(100),ia.html(a.title).add(x).show(),ca>1?(typeof a.current=="string"&&oa.html(a.current.replace("{current}",n+1).replace("{total}",ca)).show(),aa[a.loop||n<ca-1?"show":"hide"]().html(a.next),ba[a.loop||n?"show":"hide"]().html(a.previous),U=n?m[n-1]:m[ca-1],fa=n<ca-1?m[n+1]:m[0],a.slideshow&&Y.show(),a.preloading&&(Q=c.data(fa,
k).href||fa.href,P=c.data(U,k).href||U.href,Q=c.isFunction(Q)?Q.call(fa):Q,P=c.isFunction(P)?P.call(U):P,w(Q)&&(c("<img/>")[0].src=Q),w(P)&&(c("<img/>")[0].src=P))):ha.hide(),a.iframe?(I=c("<iframe/>").addClass(q+"Iframe")[0],a.fastIframe?ga():c(I).one("load",ga),I.name=q+ +new Date,I.src=a.href,a.scrolling||(I.scrolling="no"),T&&(I.frameBorder=0,I.allowTransparency="true"),c(I).appendTo(x).one(M,function(){I.src="//about:blank"})):ga(),a.transition==="fade"?r.fadeTo(t,1,O):O())};a.transition==="fade"?
r.fadeTo(t,0,function(){g.position(0,s)}):g.position(t,s)}};g.load=function(b){var f,i,s=g.prep;W=true;o=false;z=m[n];b||l();d(M);d(A,a.onLoad);a.h=a.height?j(a.height,"y")-G-K:a.innerHeight&&j(a.innerHeight,"y");a.w=a.width?j(a.width,"x")-H-L:a.innerWidth&&j(a.innerWidth,"x");a.mw=a.w;a.mh=a.h;a.maxWidth&&(a.mw=j(a.maxWidth,"x")-H-L,a.mw=a.w&&a.w<a.mw?a.w:a.mw);a.maxHeight&&(a.mh=j(a.maxHeight,"y")-G-K,a.mh=a.h&&a.h<a.mh?a.h:a.mh);f=a.href;qa=setTimeout(function(){$.show()},100);a.inline?(e().hide().insertBefore(c(f)[0]).one(M,
function(){c(this).replaceWith(x.children())}),s(c(f))):a.iframe?s(" "):a.html?s(a.html):w(f)?(c(o=new Image).addClass(q+"Photo").error(function(){a.title=false;s(e("Error").text("This image could not be loaded"))}).load(function(){var t;o.onload=null;a.scalePhotos&&(i=function(){o.height-=o.height*t;o.width-=o.width*t},a.mw&&o.width>a.mw&&(t=(o.width-a.mw)/o.width,i()),a.mh&&o.height>a.mh&&(t=(o.height-a.mh)/o.height,i()));a.h&&(o.style.marginTop=Math.max(a.h-o.height,0)/2+"px");m[1]&&(n<m.length-
1||a.loop)&&(o.style.cursor="pointer",o.onclick=function(){g.next()});T&&(o.style.msInterpolationMode="bicubic");setTimeout(function(){s(o)},1)}),setTimeout(function(){o.src=f},1)):f&&Z.load(f,a.data,function(t,O,U){s(O==="error"?e("Error").text("Request unsuccessful: "+U.statusText):c(this).contents())})};g.next=function(){!W&&m[1]&&(n<m.length-1||a.loop)&&(n=n<m.length-1?n+1:0,g.load())};g.prev=function(){!W&&m[1]&&(n||a.loop)&&(n=n?n-1:m.length-1,g.load())};g.close=function(){F&&!da&&(da=true,
F=false,d(v,a.onCleanup),y.unbind("."+q+" ."+ea),J.fadeTo(200,0),r.stop().fadeTo(300,0,function(){r.add(J).css({opacity:1,cursor:"auto"}).hide();d(M);x.remove();setTimeout(function(){da=false;d(V,a.onClosed)},1)}))};g.element=function(){return c(z)};g.settings=R;pa=function(b){b.button!==0&&typeof b.button!="undefined"||b.ctrlKey||b.shiftKey||b.altKey||(b.preventDefault(),h(this))};c.fn.delegate?c(u).delegate("."+C,"click",pa):c("."+C).live("click",pa);c(g.init)})(jQuery,document,this);
window.innerShiv=function(){function c(p,d,l){return/^(?:area|br|col|embed|hr|img|input|link|meta|param)$/i.test(l)?p:d+"></"+l+">"}var u,B=document,h="abbr article aside audio canvas datalist details figcaption figure footer header hgroup mark meter nav output progress section summary time video".split(" ");return function(p,d){if(!u&&(u=B.createElement("div"),u.innerHTML="<nav></nav>",u.childNodes.length!==1)){for(var l=B.createDocumentFragment(),w=h.length;w--;)l.createElement(h[w]);l.appendChild(u)}p=
p.replace(/^\s\s*/,"").replace(/\s\s*$/,"").replace(/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi,"").replace(/(<([\w:]+)[^>]*?)\/>/g,c);u.innerHTML=(l=p.match(/^<(tbody|tr|td|col|colgroup|thead|tfoot)/i))?"<table>"+p+"</table>":p;l=l?u.getElementsByTagName(l[1])[0].parentNode:u;if(d===false)return l.childNodes;w=B.createDocumentFragment();for(var j=l.childNodes.length;j--;)w.appendChild(l.firstChild);return w}}();
