#!/bin/sh

if [ -z "$2" ]; then
    OUTPUT_FILE=/tmp/pandoc-rst.html
else
    OUTPUT_FILE=$2
fi


pandoc --from rst --to html -c $DOTFILES_DIR/pandoc/css/github-markdown.css --self-contained --standalone  "$1" > $OUTPUT_FILE
