#!/usr/bin/env sh
ID=$(xdpyinfo | grep focus | cut -f4 -d " ")
if xprop -id $ID | grep '^WM_CLASS(STRING)' | grep -i '"termite"'; then
    WINDOW_PID=$(xprop -id $ID | grep -m 1 PID | cut -d " " -f 3)
    TREE=$(pstree -lAp $WINDOW_PID | head -n 1)
    PID=$(echo $TREE | sed 's/-+-/\n/g' | sed 's/---/\n/g' | grep '^zsh(' | tail -n 1 | sed 's/[\(,\)]/ /g' | awk '{print $2}')
    CWD="$(readlink -f /proc/$PID/cwd)"
fi

if [ -d "${CWD}" ]; then
    exec termite -d "${CWD}"
else
    exec termite
fi
