#!/usr/bin/env sh
xset +dpms
xset dpms 0 0 10
if ! pidof i3lock; then
    pkill -x onboard
    onboard &
    i3lock -n -c 8c8cb8
    pkill -x onboard
    xset -dpms
    killall -USR1 i3status i3status-rs
fi
