#!/usr/bin/env python3
import argparse
import contextlib
import subprocess
import unittest


def find_tests(name):
    tests = set()
    for suite in unittest.defaultTestLoader.discover(name):
        for case in suite:
            try:
                iter_case = iter(case)
            except TypeError:
                continue
            for test in iter_case:
                fullname = '.'.join([
                    test.__module__,
                    test.__class__.__qualname__,
                    test._testMethodName
                ])
                tests.add(fullname)
    return tests


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('name', default='.', nargs='?')
    args = parser.parse_args()

    # redirect stdout to make loud imports stfu
    with contextlib.redirect_stdout(subprocess.DEVNULL):
        tests = find_tests(args.name)

    print('\n'.join(sorted(tests)))


if __name__ == '__main__':
    main()
