#!/usr/bin/env sh
if [ -z "$1" ]; then
    echo error: must specify image path >&2
    exit 1
fi
docker-shell \
    -v "$HOME/.jellyfin_dev:/config" \
    -v /mnt/storage1/Shows:/media/Shows1:ro \
    -v /mnt/storage2/Movies:/media/Movies:ro \
    -v /mnt/storage2/Shows:/media/Shows2:ro \
    -v /home/draje/.jellyfin_dev/music:/media/Music \
    --net=host \
    --user $(id -u):$(id -g) \
    "$1"
