#!/usr/bin/env sh
set -uex

IMAGE="jellyfin/jellyfin"
VERSION="$1"
if [ -z "$VERSION" ]; then
    echo error: must specify version >&2
    exit 1
fi

docker run --rm --privileged multiarch/qemu-user-static:register || true

docker build --no-cache --pull . -t "${IMAGE}":$VERSION-amd64 -f Dockerfile
docker build --no-cache --pull . -t "${IMAGE}":$VERSION-arm -f Dockerfile.arm
docker build --no-cache --pull . -t "${IMAGE}":$VERSION-arm64 -f Dockerfile.arm64

for arch in amd64 arm arm64; do
    docker push "${IMAGE}":$VERSION-$arch
done

for tag in "$@" ; do
    docker manifest create "${IMAGE}:${tag}" \
        "${IMAGE}:${VERSION}-arm64" \
        "${IMAGE}:${VERSION}-amd64" \
        "${IMAGE}:${VERSION}-arm"

    docker manifest push --purge "${IMAGE}:${tag}"
done
