#!/usr/bin/env sh
set -ex

VERSION="$1"
if [ -z "$VERSION" ]; then
    echo error: must specify version >&2
    exit 1
fi

IMAGE="jellyfin/jellyfin"

for tag in amd64 arm arm64; do
    docker pull "${IMAGE}:${VERSION}-${tag}"
done

for tag in "${VERSION}" latest; do
    docker manifest create "${IMAGE}:${tag}" \
        "${IMAGE}:${VERSION}-arm64" \
        "${IMAGE}:${VERSION}-amd64" \
        "${IMAGE}:${VERSION}-arm"

    docker manifest push --purge "${IMAGE}:${tag}"
done
