#!/usr/bin/env sh
set -ex
IMAGE=jellyfin/jellyfin

for tag in amd64 arm arm64; do
    docker pull "${IMAGE}:${tag}"
done

docker manifest create "${IMAGE}" \
    "${IMAGE}":arm64 \
    "${IMAGE}":amd64 \
    "${IMAGE}":arm

docker manifest push --purge "${IMAGE}"
