#!/usr/bin/env sh
set -e

JELLYFIN_DATA=~/.jellyfin_dev

cd ~/Code/jellyfin

rm -rf debug

if [ "$1" = 'podman' ]; then
    if [ -z "$2" ]; then
        IMAGE=jellyfin_dev
        podman build -t jellyfin_dev --pull .
    else
        IMAGE="jellyfin/jellyfin:$2"
    fi
        #--volume "/dev/dri:/dev/dri" \
    mkdir -p "$JELLYFIN_DATA"
    podman-shell \
        -v "$JELLYFIN_DATA/config:/config" \
        -v "$JELLYFIN_DATA/cache:/cache" \
        --net host \
        --volume "/storage/Video:/media:ro" \
        --volume "/storage/Audio/MP3:/audio:ro" \
        "$IMAGE"
elif [ "$1" = 'dotnet' ]; then
    OUTPUT_DIR="$(pwd)/debug"
    dotnet publish \
        --configuration debug \
        --output "${OUTPUT_DIR}" \
        Jellyfin.Server

    dotnet "${OUTPUT_DIR}/jellyfin.dll" --datadir ~/.jellyfin_dev "$@"
else
    echo "usage: jellyfin-dev {dotnet,podman}" >&2
    exit 1
fi
