#!/usr/bin/env sh
set -e

JELLYFIN_DATA=~/.jellyfin_dev

cd ~/Code/jellyfin

rm -rf debug

if [ "$1" = 'podman' ]; then
    shift
    if [ -n "$1" ]; then
        IMAGE="$1"
        shift
    else
        IMAGE=jellyfin_dev
        podman build --pull -t jellyfin_dev .
    fi
        #--volume "/dev/dri:/dev/dri" \
    mkdir -p "${JELLYFIN_DATA}/cache"
    mkdir -p "${JELLYFIN_DATA}/config"
    exec podman run \
        -v "$JELLYFIN_DATA/config:/config" \
        -v "$JELLYFIN_DATA/cache:/cache" \
        --name jellyfin_dev \
        --net host \
        --volume "/storage/Video:/video:ro" \
        --volume "/storage/Audio/MP3:/music:ro" \
        "$@" \
        "$IMAGE"
elif [ "$1" = 'dotnet' ]; then
    OUTPUT_DIR="$(pwd)/debug"
    dotnet publish \
        --configuration debug \
        --output "${OUTPUT_DIR}" \
        Jellyfin.Server

    exec dotnet "${OUTPUT_DIR}/jellyfin.dll" --datadir ~/.jellyfin_dev "$@"
else
    echo "usage: jellyfin-dev {dotnet,podman}" >&2
    exit 1
fi
