#!/usr/bin/env sh
MAGENTA='\033[1;35m'
RESET='\033[0m'

update_repo() {
    dotfiles_root="$2"
    if [ -d "$dotfiles_root/.git" ]; then
        printf "${MAGENTA}Updating $1 ($dotfiles_root)...${RESET}\n"
        git auto-update "$dotfiles_root"
    fi
}

update_repo "DOTFILES" "$DOTFILES"


for d in $(env | grep ^DOTFILES_ | sort); do
    name="$(echo "$d" | cut -d = -f 1)"
    loc="$(echo "$d" | cut -d = -f 2)"
    update_repo "$name" "$loc"
done
