#!/usr/bin/env sh
set -e

if ! command -v pacman > /dev/null; then
    exit
fi

MAGENTA='\033[1;35m'
RESET='\033[0m'

export PKGEXT='.pkg.tar'

log() {
    printf "${MAGENTA}$1 ...${RESET}\n"
}

if ! [ -d ~/.config/pacman ] || [ "$(realpath ~/.config/pacman)" != "${DOTFILES}/pacman" ]; then
    rm -rf ~/.config/pacman
    mkdir -p ~/.config/
    ln -sfT "${DOTFILES}/pacman" ~/.config/pacman
fi

if ! command -v yay > /dev/null 2>&1; then
    mkdir /tmp/yay-install
    trap 'rm -rf /tmp/yay-install' INT EXIT
    cd /tmp/yay-install
    curl https://aur.archlinux.org/cgit/aur.git/snapshot/yay.tar.gz | tar -zxv
    cd -
    cd /tmp/yay-install/yay
    makepkg -s --install --noconfirm
    rm -rf /tmp/yay-install
    cd -
fi

log 'Updating packages'
yay -Syu --noconfirm --devel

if command -v pkgfile > /dev/null; then
    log 'Updating file cache'
    sudo pkgfile --update > /dev/null
fi

# TODO create prune script which keeps n-number of old versions of a package
#log 'Pruning package cache'
#yay -Sc --noconfirm > /dev/null

log 'Locating .pac* files'
sudo find /etc -regextype posix-extended -regex ".+\.pac(new|save)" 2> /dev/null || true
