#!/usr/bin/env sh
set -e

if ! command -v pacman > /dev/null; then
    exit
fi

MAGENTA='\033[1;35m'
RESET='\033[0m'

export PKGEXT='.pkg.tar'

log() {
    printf "${MAGENTA}$1 ...${RESET}\n"
}

if ! [ -d ~/.config/pacman ] || [ "$(realpath ~/.config/pacman)" != "${DOTFILES}/pacman" ]; then
    rm -rf ~/.config/pacman
    mkdir -p ~/.config/
    ln -sfT "${DOTFILES}/pacman" ~/.config/pacman
fi

if ! command -v yay > /dev/null 2>&1; then
    mkdir /tmp/yay-install
    trap 'rm -rf /tmp/yay-install' INT EXIT
    cd /tmp/yay-install
    curl https://aur.archlinux.org/cgit/aur.git/snapshot/yay.tar.gz | tar -zxv
    cd -
    cd /tmp/yay-install/yay
    makepkg -s --install --noconfirm
    rm -rf /tmp/yay-install
    cd -
fi

log 'Updating packages'
yay -Sy

# ignore pipewire 1:1.4.3-1 due to mpv stutter https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/4713
pipewire_ver="$(pacman -Sdp --print-format '%v' pipewire)"
if [ "$pipewire_ver" != '1:1.4.3-1' ]; then
    printf 'error: unexpected pipewire version (%s)\n' "$pipewire_ver" >&2
    printf 'modify this script to resolve.' >&2
    exit 1
fi
yay -Su --noconfirm --devel \
    --ignore libpipewire,pipewire,pipewire-alsa,pipewire-audio,pipewire-jack,pipewire-pulse

if command -v pkgfile > /dev/null; then
    log 'Updating file cache'
    sudo pkgfile --update > /dev/null
fi

# TODO create prune script which keeps n-number of old versions of a package
if command -v paccache > /dev/null; then
    log 'Pruning package cache'
    paccache \
        --remove \
        --keep 3 \
        --min-mtime '30 days ago'
fi

log 'Locating .pac* files'
sudo find /etc -regextype posix-extended -regex ".+\.pac(new|save)" 2> /dev/null || true
