#!/usr/bin/env sh
set -e

if ! command -v pacman > /dev/null; then
    exit
fi

MAGENTA='\033[1;35m'
RESET='\033[0m'

export PKGEXT='.pkg.tar'

log() {
    printf "${MAGENTA}$1 ...${RESET}\n"
}

if ! [ -d ~/.config/pacman ] || [ "$(realpath ~/.config/pacman)" != "${DOTFILES}/pacman" ]; then
    rm -rf ~/.config/pacman
    ln -sfT "${DOTFILES}/pacman" ~/.config/pacman
fi

if ! command -v yay > /dev/null 2>&1; then
    mkdir /tmp/yay-install
    trap 'rm -rf /tmp/yay-install' INT EXIT
    cd /tmp/yay-install
    curl https://aur.archlinux.org/cgit/aur.git/snapshot/yay.tar.gz | tar -zxv
    cd -
    cd /tmp/yay-install/yay
    makepkg -s --install --noconfirm
    rm -rf /tmp/yay-install
    cd -
fi
log 'Updating packages'
yay -Syu --noconfirm --devel

log 'Removing bullshit gcr-prompter 🖕'
sudo rm -f /usr/lib/gcr-prompter

log 'Fixing the bullshit combination of libappindicator and electron 🖕'
# https://bugs.launchpad.net/ubuntu/+source/libappindicator/+bug/1910521
sudo touch \
       /usr/lib/electron/libappindicator3.so \
       /usr/lib/electron/libappindicator3.so.1 \
       /usr/lib/element/libappindicator3.so \
       /usr/lib/element/libappindicator3.so.1 \
       /usr/lib/signal-desktop/libappindicator3.so \
       /usr/lib/signal-desktop/libappindicator3.so.1 \
       /usr/lib/slack/libappindicator3.so \
       /usr/lib/slack/libappindicator3.so.1 \
    2> /dev/null || true

log 'Updating file cache'
sudo pkgfile --update > /dev/null

log 'Pruning package cache'
yay -Sc --noconfirm > /dev/null

GIMP_BIN="$(which 'gimp-2.99' 2> /dev/null || true)"
if [ -n "$GIMP_BIN" ]; then
    log 'Linking gimp-2.99 to gimp'
    rm -rf ~/.local/bin/gimp
    ln -sT "$GIMP_BIN" ~/.local/bin/gimp
fi
