#!/usr/bin/env sh
set -e

if ! command -v termux-info > /dev/null; then
    exit
fi

if [ "$(realpath ~/.termux)" != "$DOTFILES/termux" ]; then
    echo "Linking configuration ..."
    rm -rf ~/.termux
    ln -s "${DOTFILES}/termux" ~/.termux
fi

if [ "$(realpath ~/bin)" != "$DOTFILES/termux/bin" ]; then
    echo "Linking configuration ..."
    rm -rf ~/bin
    ln -s "${DOTFILES}/termux/bin" ~/bin
fi

if [ -f '/data/data/com.termux/files/usr/etc/ssh/sshd_config' ]; then
    echo "Linking sshd configuration ..."
    cat > /data/data/com.termux/files/usr/etc/ssh/sshd_config << EOF
PrintMotd no
PasswordAuthentication no
Subsystem sftp /data/data/com.termux/files/usr/libexec/sftp-server
EOF
fi

#yes | termux-setup-storage
ln -sfT /storage/emulated/0/Syncthing/default/notes ~/notes
ln -sfT /storage/emulated/0/Syncthing ~/syncthing
ln -sfT /storage/emulated/0/Download ~/download

# symlinking wont work 
rsync -a --delete "${DOTFILES}/termux/shortcuts/" ~/.shortcuts

yes | pkg upgrade
yes | apt autoremove

touch ~/.hushlogin
