#!/usr/bin/env sh
set -e

if ! command -v termux-info > /dev/null; then
    exit
fi

if [ "$(realpath ~/.termux)" != "$DOTFILES/termux" ]; then
    echo "Linking configuration ..."
    rm -rf ~/.termux
    ln -s "${DOTFILES}/termux" ~/.termux
fi

if [ "$(realpath ~/bin)" != "$DOTFILES/termux/bin" ]; then
    echo "Linking configuration ..."
    rm -rf ~/bin
    ln -s "${DOTFILES}/termux/bin" ~/bin
fi

yes | termux-setup-storage
ln -sfT ~/storage/shared/syncthing/default/notes ~/notes
ln -sfT ~/storage/shared/syncthing ~/syncthing
ln -sfT ~/storage/shared/Download ~/download

yes | pkg upgrade
yes | apt autoremove
rm -rf ~/../usr/etc/motd
