#!/usr/bin/env sh
set -e

if ! command -v termux-info > /dev/null; then
    exit
fi

if [ "$(realpath ~/.termux)" != "$DOTFILES/termux" ]; then
    echo "Linking configuration ..."
    rm -rf ~/.termux
    ln -s "${DOTFILES}/termux" ~/.termux
fi

if [ -d ~/storage ]; then
    ln -s /storage/emulated/0 ~/storage
fi
if [ -d ~/notes ]; then
    ln -s /storage/emulated/0/syncthing/default/notes ~/notes
fi

yes | pkg upgrade
yes | apt autoremove
rm -rf ~/../usr/etc/motd
