#!/usr/bin/env sh
set -e

if [ "$(uname)" != 'Darwin' ]; then
    exit
fi

if ! command -v brew > /dev/null; then
    /usr/bin/ruby -e "$(curl --compressed -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

brew update
brew upgrade
brew cask upgrade
brew cleanup
