#!/usr/bin/env sh
set -e

XDG_DATA_DIR="${XDG_DATA_DIR:-$HOME/.local/share}"
INSTALL_DIR="${XDG_DATA_DIR}/nvm"

show_help() {
    cat << EOF
usage:
    -f, --force     force installation
    --help          show help and exit
EOF
}

FORCE=
while [ $# -gt 0 ]; do
    case "$1" in
        -f|--force)
            FORCE=1
            shift
            ;;
        --help)
            show_help
            exit
            ;;
        *)
            echo 'error: unknown argument(s)' >&2
            exit 1
    esac
done

if [ -z "$FORCE" ] && ! [ -d "$INSTALL_DIR" ]; then
    exit
fi

if ! [ -d "$INSTALL_DIR" ]; then
    mkdir -p "$XDG_DATA_DIR"
    git clone https://github.com/creationix/nvm "$INSTALL_DIR" > /dev/null
else
    cd "$INSTALL_DIR"
    git clean -fd
    git pull
fi

cd "$INSTALL_DIR"
. ./nvm.sh
nvm install node --latest-npm
npm install -g npm@latest
NVM_SYMLINK_CURRENT=true nvm use node
