#!/usr/bin/env sh
set -e
XDG_DATA_DIR="${XDG_DATA_DIR:-$HOME/.local/share}"
INSTALL_DIR="${XDG_DATA_DIR}/pyenv"

if ! [ -d "$INSTALL_DIR" ]; then
    if [ "$1" != '--force' ]; then
        exit
    fi
    mkdir -p "$XDG_DATA_DIR"
    git clone https://github.com/pyenv/pyenv "$INSTALL_DIR" > /dev/null
else
    cd "$INSTALL_DIR"
    git clean -fd
    git pull
fi

"$INSTALL_DIR"/bin/pyenv rehash

exit
if [ -d "${INSTALL_DIR}"/versions ]; then
    PYTHON_VERSION="$(ls "${INSTALL_DIR}/versions" | rg '^\d' | sort --version-sort | tail -n 1 | sed 's/[ \t]*$//')"
    "${INSTALL_DIR}/versions/${PYTHON_VERSION}/bin/python" << EOF
import os
import pathlib
import shutil

PYENV_ROOT = pathlib.Path(os.environ['PYENV_ROOT'])
LINK_DIR = PYENV_ROOT / 'plugins' / 'pyenv-global-links'
if LINK_DIR.exists():
    shutil.rmtree(LINK_DIR)
LINK_DIR.mkdir()

VERSION_FILE = PYENV_ROOT / 'version'
if VERSION_FILE.exists():
    versions = [
        line
        for line in VERSION_FILE.read_text().split('\n')
        if line
    ]

    def create_link(version, linkname):
        source = PYENV_ROOT / 'versions' / version / 'bin' / linkname

        target = LINK_DIR / linkname
        target.symlink_to(source)


    done = set()

    for version in versions:
        major, minor, patch = version.split('.')
        links = {
            'python',
            f'python{major}',
            f'python{major}.{minor}',
        }

        for link in sorted(links - done):
            create_link(version, link)

        done.update(links)
EOF
fi
