#!/usr/bin/env sh
set -e
XDG_DATA_DIR="${XDG_DATA_DIR:-$HOME/.local/share}"
INSTALL_DIR="${XDG_DATA_DIR}/pyenv"

if ! [ -d "$INSTALL_DIR" ]; then
    if [ "$1" != '--force' ]; then
        exit
    fi
    mkdir -p "$XDG_DATA_DIR"
    git clone https://github.com/pyenv/pyenv "$INSTALL_DIR" > /dev/null
else
    cd "$INSTALL_DIR"
    git clean -fd
    git pull
fi

"$INSTALL_DIR"/bin/pyenv rehash
