#!/usr/bin/env sh
set -e

show_help() {
    cat << EOF
usage:
    -f, --force     force installation
    --help          show help and exit
EOF
}

FORCE=
while [ $# -gt 0 ]; do
    case "$1" in
        -f|--force)
            FORCE=1
            shift
            ;;
        --help)
            show_help
            exit
            ;;
        *)
            echo 'error: unknown argument(s)' >&2
            exit 1
    esac
done

if [ -z "$FORCE" ] && ! command -v rustup > /dev/null; then
    exit
fi

if ! command -v rustup > /dev/null; then
    cleanup() {
        rm -f "${TEMP_FILE}"
    }

    trap cleanup EXIT
    TEMP_FILE="$(mktemp)"
    curl https://sh.rustup.rs > "${TEMP_FILE}"
    chmod +x "${TEMP_FILE}"
    "${TEMP_FILE}" -y --profile complete --no-modify-path
else
    rustup update
fi
