#!/usr/bin/env sh
set -e

export PIP_REQUIRE_VIRTUALENV=0

if ! command -v pip > /dev/null 2>&1; then
    exit
fi

pip() {
    python -m pip "$@"
}

if ! [ -x "$(command -v pip)" ] || [ "$(pip list | grep -c -e '^pip ' -e '^setuptools ' -e '^wheel ')" != '3' ]; then
    python -m ensurepip --user --default-pip
    pip install --user --upgrade --force-reinstall pip setuptools wheel
fi

ood_packages="$(pip list --outdated --format=freeze)"
if [ -n "${ood_packages}" ]; then
    pip install --user --upgrade $(echo "${ood_packages}" | cut -d = -f 1)
fi
