#!/usr/bin/env sh
set -e
if ! command -v pip > /dev/null; then
    exit
fi

if ! command -v pipx > /dev/null; then
    exit

    cleanup() {
        rm -f "${TEMP_FILE}"
    }

    trap cleanup EXIT
    TEMP_FILE="$(mktemp)"

    export PIPX_HOME=~/.local/pipx
    export PIPX_BIN_DIR="${PIPX_HOME}/bin"
    curl -L https://github.com/pypa/pipx/releases/latest/download/pipx.pyz -o "${TEMP_FILE}"
    python "${TEMP_FILE}" install pipx
    rm "${TEMP_FILE}"

    pipx() {
        "${PIPX_BIN_DIR}/pipx" "$@"
    }
fi

for package in $(pipx list --short | cut -d' ' -f1); do
    pipx upgrade --pip-args='--upgrade-strategy=eager' "$package"
done
