#!/usr/bin/env sh
set -e

if ! command -v alacritty > /dev/null; then
    rm -rf ~/.config/alacritty
    exit
fi

if [ "$(realpath ~/.config/alacritty)" != "$DOTFILES/alacritty" ]; then
    rm -rf ~/.config/alacritty
    ln -sT "${DOTFILES}/alacritty" ~/.config/alacritty
fi
