#!/usr/bin/env sh
if ! command -v discord > /dev/null; then
    exit
fi

python << EOF
import json
import pathlib

path = pathlib.Path('~/.config/discord/settings.json').expanduser()
if path.exists():
    settings = json.loads(path.read_text())
    if settings.get('SKIP_HOST_UPDATE') != True:
        settings['SKIP_HOST_UPDATE'] = True
        path.write_text(json.dumps(settings))

EOF
