#!/usr/bin/env sh
set -e

if ! command -v dosbox > /dev/null; then
    exit
fi

if [ "$(realpath ~/.config/dosbox)" != "$DOTFILES/dosbox" ]; then
    echo "Linking configuration ..."
    rm -rf ~/.config/dosbox
    ln -sT "${DOTFILES}/dosbox" ~/.config/dosbox
fi
