#!/usr/bin/env sh
set -e

if ! command -v firefox > /dev/null; then
    exit
fi

for d in ~/.mozilla/firefox/*; do
    if [ -d "$d" ] && [ -f "$d/prefs.js" ]; then
        if [ "$(realpath "$d/user.js")" != "${DOTFILES_PRIVATE}/firefox/user.js" ]; then
            echo "Linking to $d"
            rm -rf "$d/user.js"
            ln -sT "${DOTFILES_PRIVATE}/firefox/user.js" "$d/user.js"
        fi
    fi
done
