#!/usr/bin/env sh
set -e

if ! command -v helix > /dev/null; then
    rm -rf ~/.config/helix
    exit
fi

if [ "$(realpath ~/.config/helix)" != "$DOTFILES/helix" ]; then
    rm -rf ~/.config/helix
    ln -sT "${DOTFILES}/helix" ~/.config/helix
fi
