#!/usr/bin/env sh
set -e

if ! command -v i3 > /dev/null; then
    rm -rf ~/.config/i3
else
    if [ "$(realpath ~/.config/i3)" != "$DOTFILES/i3" ]; then
        echo "Linking configuration ..."
        rm -rf ~/.config/i3
        ln -sT "${DOTFILES}/i3" ~/.config/i3
    fi
fi
