#!/usr/bin/env sh
set -e

if ! command -v i3status-rs > /dev/null; then
    rm -rf ~/.config/i3status-rust
else
    if [ "$(realpath ~/.config/i3status-rust)" != "$DOTFILES/i3status-rust" ]; then
        echo "Linking configuration ..."
        rm -rf ~/.config/i3status-rust
        ln -sT "${DOTFILES}/i3status-rust" ~/.config/i3status-rust
    fi
fi
