#!/usr/bin/env sh
set -e

if ! command -v jellyfinmediaplayer > /dev/null; then
    rm -rf ~/.local/share/jellyfinmediaplayer
else
    mkdir -p ~/.local/share/jellyfinmediaplayer
    if [ "$(realpath ~/.local/share/jellyfinmediaplayer/mpv.conf)" != "$DOTFILES/jellyfinmediaplayer/mpv.conf" ]; then
        echo "Linking mpv.conf ..."
        rm -rf ~/.local/share/jellyfinmediaplayer/mpv.conf
        ln -sT "${DOTFILES}/jellyfinmediaplayer/mpv.conf" ~/.local/share/jellyfinmediaplayer/mpv.conf
    fi
fi
