#!/usr/bin/env sh
set -e

if command -v krunner > /dev/null; then
    if [ "$(realpath ~/.local/share/kf6/searchproviders/)" != "${DOTFILES}/krunner/searchproviders" ]; then
        echo "Linking searchproviders ..."
        rm -rf ~/.local/share/kf6/searchproviders
        mkdir -p ~/.local/share/kf6
        ln -sT "${DOTFILES}/krunner/searchproviders" ~/.local/share/kf6/searchproviders
    fi
    if [ "$(realpath ~/.config/kuriikwsfilterrc)" != "${DOTFILES}/krunner/kuriikwsfilterrc" ]; then
        echo "Linking kuriikwsfilterrc ..."
        rm -rf ~/.config/kuriikwsfilterrc
        ln -sT "${DOTFILES}/krunner/kuriikwsfilterrc" ~/.config/kuriikwsfilterrc
    fi
    if [ "$(realpath ~/.local/share/applications)" != "${DOTFILES}/krunner/applications" ]; then
        echo "Linking applications ..."
        rm -rf ~/.local/share/applications
        ln -sT "${DOTFILES}/krunner/applications" ~/.local/share/applications
    fi
    if [ "$(realpath ~/.local/share/icons)" != "${DOTFILES}/krunner/icons" ]; then
        echo "Linking icons ..."
        rm -rf ~/.local/share/icons
        ln -sT "${DOTFILES}/krunner/icons" ~/.local/share/icons
    fi
    HOSTNAME="$(hostname)"
    if [ -n "$HOSTNAME" ] && [ -d "${DOTFILES}/krunner/applications_host/${HOSTNAME}/" ]; then
        rsync -av -q --delete "${DOTFILES}/krunner/applications_host/${HOSTNAME}/" ~/.local/share/applications/dotfiles-localhost/
    else
        rm -rf ~/.local/share/applications/dotfiles-localhost
    fi
    update-desktop-database
fi
