#!/usr/bin/env sh
set -e

if command -v kwriteconfig6 > /dev/null; then
    if [ "$(realpath ~/.config/kdesurc)" != "${DOTFILES}/kdesurc" ]; then
        echo "Linking configuration ..."
        rm -rf ~/.config/kdesurc
        ln -sT "${DOTFILES}/kdesurc" ~/.config/kdesurc
    fi
fi
