#!/usr/bin/env sh
set -e

if ! command -v lf > /dev/null; then
    rm -rf ~/.config/lf
else
    if [ "$(realpath ~/.config/lf)" != "$DOTFILES/lf" ]; then
        echo "Linking configuration ..."
        rm -rf ~/.config/lf
        ln -s "${DOTFILES}/lf" ~/.config/lf
    fi
    rm -f \
        ~/.local/share/lf/marks \
        ~/.local/share/lf/tags
fi
