#!/usr/bin/env sh
set -e

if ! command -v mpv > /dev/null; then
    exit
fi

if [ "$(realpath ~/.config/mpv)" != "$DOTFILES/mpv" ]; then
    echo "Linking configuration ..."
    rm -rf ~/.config/mpv
    ln -sT "${DOTFILES}/mpv" ~/.config/mpv
fi
