#!/usr/bin/env sh
set -e

if ! command -v ncmpcpp > /dev/null; then
    rm -rf ~/.config/ncmpcpp
else
    if [ "$(realpath ~/.config/ncmpcpp)" != "$DOTFILES/ncmpcpp" ]; then
        echo "Linking configuration ..."
        rm -rf ~/.config/ncmpcpp
        ln -sT "${DOTFILES}/ncmpcpp" ~/.config/ncmpcpp
    fi
fi
