#!/usr/bin/env sh
set -e

if ! command -v nvim > /dev/null; then
    rm -rf ~/.config/nvim
    exit
fi

if [ "$(realpath ~/.config/nvim)" != "$DOTFILES/nvim" ]; then
    rm -rf ~/.config/nvim
    ln -sT "${DOTFILES}/nvim" ~/.config/nvim
fi

if [ ! -f ~/.config/nvim/autoload/plug.vim ]; then
    echo Installing plugin manager environment ...
    curl --compressed -fLo ~/.config/nvim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

if [ -e ~/.config/nvim/plugged ]; then
    for d in ~/.config/nvim/plugged/*/; do
        git -C "$d" reset --quiet --hard HEAD
    done
fi

echo Updating plugins ...
nvim -c 'PlugUpgrade | PlugUpdate! | PlugClean!' -c 'qa'

if command -v pip; then
    pip install jedi-language-server
fi
