#!/usr/bin/env sh
set -e

if ! command -v nvim > /dev/null; then
    rm -rf ~/.config/nvim ~/.cache/nvim ~/.local/share/nvim
    exit
fi

if [ "$(realpath ~/.config/nvim)" != "$DOTFILES/nvim" ]; then
    rm -rf ~/.config/nvim
    ln -sT "${DOTFILES}/nvim" ~/.config/nvim
fi


if command -v pipx > /dev/null; then
    if ! command -v pyright > /dev/null; then
        pipx install pyright
    fi
fi
nvim -c 'autocmd User PackerComplete quitall' -c 'PackerSync'
