#!/usr/bin/env sh
set -e

if ! command -v onboard > /dev/null; then
    rm -rf ~/.local/share/onboard
else
    if [ "$(realpath ~/.local/share/onboard)" != "$DOTFILES/onboard" ]; then
        echo "Linking configuration ..."
        rm -rf ~/.local/share/onboard
        ln -sT "${DOTFILES}/onboard" ~/.local/share/onboard
    fi
fi
