#!/usr/bin/env sh
set -e

if ! command -v picom > /dev/null; then
    rm -rf ~/.config/picom.conf
else
    if [ "$(realpath ~/.config/picom.conf)" != "$DOTFILES/picom/picom.conf" ]; then
        echo "Linking configuration ..."
        rm -rf ~/.config/picom.conf
        ln -sT "${DOTFILES}/picom/picom.conf" ~/.config/picom.conf
    fi
fi
