#!/usr/bin/env sh
set -e

if ! command -v rofimoji > /dev/null; then
    exit
fi

if [ "$(realpath ~/.config/rofimoji)" != "$DOTFILES/rofimoji" ]; then
    echo "Linking configuration ..."
    rm -rf ~/.config/rofimoji
    ln -sT "${DOTFILES}/rofimoji" ~/.config/rofimoji
fi
