#!/usr/bin/env sh
set -e

if ! command -v sway > /dev/null; then
    rm -rf ~/.config/sway
else
    if [ "$(realpath ~/.config/sway)" != "$DOTFILES/sway" ]; then
        echo "Linking configuration ..."
        rm -rf ~/.config/sway
        ln -sT "${DOTFILES}/sway" ~/.config/sway
    fi
fi
