#!/usr/bin/env sh
set -e

if ! command -v sway > /dev/null; then
    exit
fi

if [ "$(realpath ~/.config/sway)" != "$DOTFILES/sway" ]; then
    echo "Linking configuration ..."
    rm -rf ~/.config/sway
    ln -sT "${DOTFILES}/sway" ~/.config/sway
fi
