#!/usr/bin/env sh
set -e

if command -v sqlite3 > /dev/null; then
    if [ "$(realpath ~/.sqliterc)" != "$DOTFILES/sqlite/.sqliterc" ]; then
        echo "Linking configuration ..."
        rm -rf ~/.sqliterc
        ln -sT "${DOTFILES}/sqlite/.sqliterc" ~/.sqliterc
    fi
else
    rm -rf ~/.sqliterc
fi
