#!/usr/bin/env sh
set -e

if ! command -v systemctl > /dev/null; then
    exit
fi

if [ "$(realpath ~/.config/environment.d)" != "$DOTFILES/environment.d" ]; then
    echo "Linking configuration ..."
    rm -rf ~/.config/environment.d
    ln -sT "${DOTFILES}/environment.d" ~/.config/environment.d
fi
