#!/usr/bin/env sh
set -e

if ! command -v swaylock > /dev/null; then
    rm -rf ~/.config/swaylock
else
    if [ "$(realpath ~/.config/swaylock)" != "$DOTFILES/swaylock" ]; then
        echo "Linking configuration ..."
        rm -rf ~/.config/swaylock
        ln -sT "${DOTFILES}/swaylock" ~/.config/swaylock
    fi
fi
