#!/usr/bin/env sh
set -e

if ! command -v wezterm > /dev/null; then
    rm -rf ~/.config/wezterm
else
    if [ "$(realpath ~/.config/wezterm)" != "${DOTFILES}/wezterm" ]; then
        echo "Linking configuration ..."
        rm -rf ~/.config/wezterm
        ln -sT "${DOTFILES}/wezterm" ~/.config/wezterm
    fi
fi
