#!/usr/bin/env sh
set -e

if ! command -v waybar > /dev/null; then
    rm -rf ~/.config/waybar
else
    if [ "$(realpath ~/.config/waybar)" != "$DOTFILES/waybar" ]; then
        echo "Linking configuration ..."
        rm -rf ~/.config/waybar
        ln -sT "${DOTFILES}/waybar" ~/.config/waybar
    fi
fi
