#!/usr/bin/env sh
set -e

if ! command -v xinit > /dev/null; then
    rm -rf ~/.xinitrc
else
    if [ "$(realpath ~/.xinitrc)" != "$DOTFILES/xinit/.xinitrc" ]; then
        echo "Linking configuration ..."
        rm -rf ~/.xinitrc
        ln -sT "${DOTFILES}/xinit/.xinitrc" ~/.xinitrc
    fi
fi
