#!/usr/bin/env sh
set -eu
if ! command -v zsh > /dev/null; then
    rm -rf ~/.zshenv
    rm -rf ~/.zshrc
else
    ln -sfT "${DOTFILES}/zsh/.zshenv" ~/.zshenv
    ln -sfT "${DOTFILES}/zsh/.zshrc" ~/.zshrc

    rm -f ~/.zcompdump
    zsh -ic 'echo -n'
fi
