#!/usr/bin/env python3
import asyncio
import pathlib
import socket
import subprocess

try:
    import pyalpm
except ImportError:
    subprocess.run(['yay', '-S', '--noconfirm', 'pyalpm'], check=True)
    import pyalpm


EXPECTED_PACKAGES = {
    '7-zip',
    'advancecomp',
    'aria2',
    'bat',
    'bchunk',
    'binmerge',
    'cabextract',
    'cuetools',
    'curlie',
    'dash',
    'direnv',
    'dosfstools',
    'e2fsprogs',
    'epub-tools-bin',
    'exfatprogs',
    'fd',
    'flake8',
    'foot-terminfo',
    'fzf',
    'gifsicle',
    'git',
    'htop',
    'hugo',
    'hyperfine',
    'iftop',
    'innoextract',
    'iperf3',
    'jpegoptim',
    'jq',
    'ledger',
    'less',
    'lf',
    'mac',
    'moreutils',
    'mp3val',
    'mprime-bin',
    'ms-sys',
    'neovim',
    'nsz',
    'ntfs-3g',
    'openssh',
    'opus-tools',
    'oxipng',
    'pandoc-cli',
    'pbzip2',
    'perl-image-exiftool',
    'pigz',
    'pixz',
    'pwgen',
    'pyright',
    'python',
    'python-async-executor',
    'python-httpx',
    'python-magic',
    'python-mutagen',
    'python-numpy',
    'python-psutil',
    'python-pytorch-rocm',
    'python-yarl',
    'rdfind',
    'reflector',
    'ripgrep',
    'rsync',
    'rust-analyzer',
    'shellcheck',
    'shntool',
    'speedtest-cli',
    'sshfs',
    'sshuttle',
    'syncthing',
    'tmux',
    'tmux-xpanes',
    'transmission-cli',
    'tree-sitter-cli',
    'typescript-language-server',
    'unace',
    'unrar',
    'unshield',
    'unzip',
    'vim',
    'vorbis-tools',
    'wl-clipboard',
    'xsel',
    'yt-dlp',
    'zip',
    'zsh',
}

EXPECTED_PACKAGES_DESKTOP = {
    'alacritty',
    'art-rawconverter',
    'audacity',
    'base16-shell-preview',
    'bitwig-studio',
    'chromium',
    'discord',
    'docker-compose',
    'dolphin',
    'element-desktop',
    'firefox',
    'foliate',
    'foot',
    'gamescope',
    'gifski',
    'gimp-devel',
    'gparted',
    'gwenview',
    'inkscape',
    'jellyfin-media-player',
    'kdeconnect',
    'kid3-qt',
    'krita',
    'mangohud',
    'mkvtoolnix-gui',
    'noto-fonts',
    'noto-fonts-cjk',
    'noto-fonts-emoji',
    'noto-fonts-extra',
    'obs-studio',
    'okular',
    'piavpn-bin',
    'podman',
    'proton-ge-custom-bin',
    'signal-desktop',
    'slack-desktop',
    'spectacle',
    'steam',
    'strawberry',
    'tremotesf',
    'ttf-dejavu-emojiless',
    'upscayl-bin',
    'virt-manager',
    'wine',
    'xboxdrv',
}


# bool True == package is installed
EXPECTED_OPT_DEPENDS = {
    'art-rawconverter': {
        'perl-image-exiftool',
        'art-rawconverter-imageio',
        'art-rawconverter-ctlscripts',
    },
    'digikam': {
        'darktable',
        'hugin',
        'qt6-imageformats',
    },
    'dolphin': {
        'ffmpegthumbs',
        'kde-cli-tools',
        'kdegraphics-thumbnailers',
        'kio-admin',
        'purpose',
    },
    'gimp-devel': {
        'aalib',
        'alsa-lib',
        'cfitsio',
        'curl',
        'ghostscript',
        'gjs',
        'iso-codes',
        'libheif',
        'libjxl',
        'libmng',
        'libwebp',
        'libxpm',
        'lua51-lgi',
        'luajit',
        'qoi-headers',
        'zlib',
    },
    'gwenview': {
        'kimageformats',
        'qt6-imageformats',
    },
    'krita': {
        'kimageformats5',
        'krita-plugin-gmic',
        'kseexpr',
        'libheif',
        'libjxl',
        'libmypaint',
        'poppler-qt5',
        'python-pyqt5',
    },
    'okular': {
        'ebook-tools',
        'kdegraphics-mobipocket',
        'unrar',
    },
    'proton-ge-custom-bin': {
        'kdialog',
        'lib32-vulkan-icd-loader',
        'python-kivy',
        'steam',
        'vulkan-driver',
        'wine',
        'winetricks',
        'xboxdrv',
        'zenity',
    },
    'steam': {
        'steam-native-runtime',
    },
    'udiskie': {
        'libappindicator-gtk3',
    },
    'wine': {
        'alsa-plugins',
        'cups',
        'dosbox',
        'gnutls',
        'gst-plugins-bad',
        'gst-plugins-base',
        'gst-plugins-base-libs',
        'gst-plugins-good',
        'gst-plugins-ugly',
        'lib32-alsa-lib',
        'lib32-alsa-plugins',
        'lib32-gnutls',
        'lib32-gst-plugins-base',
        'lib32-gst-plugins-base-libs',
        'lib32-gst-plugins-good',
        'lib32-libcups',
        'lib32-libpulse',
        'lib32-libxcomposite',
        'lib32-libxinerama',
        'lib32-opencl-icd-loader',
        'lib32-pcsclite',
        'lib32-sdl2',
        'lib32-v4l-utils',
        'libgphoto2',
        'libpulse',
        'libxcomposite',
        'libxinerama',
        'opencl-icd-loader',
        'pcsclite',
        'samba',
        'sane',
        'sdl2',
        'unixodbc',
        'v4l-utils',
        'wine-gecko',
        'wine-mono',
    },
    'yt-dlp': {
        'aria2',
        'atomicparsley',
        'ffmpeg',
        'python-brotli',
        'python-brotlicffi',
        'python-mutagen',
        'python-pycryptodome',
        'python-pycryptodomex',
        'python-pyxattr',
        'python-secretstorage',
        'python-websockets',
        'python-xattr',
        'rtmpdump',
    },
}


async def is_unit_enabled(name, user=False):
    proc = await asyncio.create_subprocess_exec(
        'systemctl',
        '--user' if user else '--system',
        'show',
        '--property=UnitFileState',
        '--',
        name,
        stdout=asyncio.subprocess.PIPE,
    )
    if proc.returncode:
        raise RuntimeError(f'exit {proc.returncode}')
    stdout, _ = await proc.communicate()
    match stdout.decode().strip():
        case 'UnitFileState=enabled':
            return True
        case 'UnitFileState=disabled':
            return False
        case _:
            raise RuntimeError


async def enable_unit(name, now=False, user=False):
    if await is_unit_enabled(name, user=user):
        return
    print(f'Enabling unit {name} (user={user}) (now={now})')
    args = []
    if not user:
        args.append('sudo')

    args.extend([
        'systemctl',
        '--user' if user else '--system',
        'enable',
    ])
    if now:
        args.append('--now')
    args.extend(['--', name])
    proc = await asyncio.create_subprocess_exec(*args)
    await proc.communicate()
    if proc.returncode:
        raise RuntimeError(f'exit {proc.returncode}')


async def install_packages(packages, asdeps=False, asexplicit=False):
    args = [
        'sudo',
        'pacman',
        '-S',
        '--noconfirm',
    ]
    if asdeps:
        args.append('--asdeps')
    if asexplicit:
        args.append('--asexplicit')
    args.extend(['--', *packages])
    proc = await asyncio.create_subprocess_exec(*args)
    await proc.communicate()


def all_packages():
    handle = pyalpm.Handle('.', '/var/lib/pacman')
    localdb = handle.get_localdb()
    return localdb.pkgcache


async def ensure_packages():
    expected_packages = set(EXPECTED_PACKAGES)
    if socket.gethostname() in ('mars', 'phobos'):
        expected_packages.update(EXPECTED_PACKAGES_DESKTOP)
    installed_packages = {
        package.name: package
        for package in all_packages()
    }

    missing = set()
    for name in expected_packages:
        if name not in installed_packages:
            missing.add(name)
        elif installed_packages[name].reason != pyalpm.PKG_REASON_EXPLICIT:
            missing.add(name)

    if missing:
        print('Installing missing packages ...')
        await install_packages(missing, asexplicit=True)


async def ensure_opt_depends():
    provided_packages = set()
    for package in all_packages():
        provided_packages.add(package.name)
        provided_packages.update(package.provides)

    missing = set()
    for expected_optdepends in EXPECTED_OPT_DEPENDS.values():
        for optdep in expected_optdepends:
            if optdep not in provided_packages:
                missing.add(optdep)

    if missing:
        print('Installing missing opt depends ...')
        await install_packages(missing, asdeps=True)


async def main():
    if not pathlib.Path('/etc/arch-release').exists():
        return

    await enable_unit('fstrim.timer', now=True)
    await enable_unit('systemd-timesyncd.service', now=True)
    await enable_unit('logrotate.timer', now=True)

    await ensure_packages()
    await ensure_opt_depends()


if __name__ == '__main__':
    asyncio.run(main())
