#!/usr/bin/env sh
set -e 

# hostname is not set to anything useful
if ! command -v termux-info > /dev/null; then
    exit
fi

if ! command -v flake8 > /dev/null; then
    pipx install flake8
fi
if ! command -v pyright > /dev/null; then
    pipx install pyright
fi
