#!/usr/bin/env sh
set -e 
if [ "$(hostname)" != 'sol' ]; then
    exit
fi

if ! [ -d ~/.config/systemd ] || [ "$(realpath ~/.config/systemd)" != "${DOTFILES}/systemd" ]; then
    rm -rf ~/.config/systemd
    ln -sT "${DOTFILES}/systemd" ~/.config/systemd
fi

git-auto-update ~/src/git.nullsum.net/nvllsvm/sol-docker
sol-docker pull
sol-repotool update
