#!/usr/bin/env sh
set -e

if ! command -v nvim > /dev/null; then
    exit
fi

VENV=~/.config/nvim/python3_env
export PIP_USER=0

create_venv() {
    rm -rf "$VENV"
    python -m venv "$VENV"
}

update_venv() {
    if ! [ -f "$(readlink -f "$VENV/bin/python")" ]; then
        create_venv
    fi
    if ! python -c ''; then
        create_venv
    fi
    if ! "$VENV/bin/pip" > /dev/null 2>&1; then
        create_venv
    fi
    . "$VENV/bin/activate"
    python -m pip install --quiet --upgrade $(pip freeze --all | cut -d = -f 1) 2> /dev/null
    # install after updating to ensure compatible deps exist for explicit pkgs
    python -m pip install --quiet --upgrade pynvim jedi
}

if [ ! -f ~/.config/nvim/autoload/plug.vim ]; then
    echo Installing plugin manager environment ...
    curl --compressed -fLo ~/.config/nvim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

echo Updating python environment ...
(update_venv)

echo Updating plugins ...
nvim -c 'PlugUpgrade | PlugUpdate! | PlugClean!' -c 'qa'
