#!/usr/bin/env python3
import pathlib

FOLDER = pathlib.Path('~/syncthing/default').expanduser()
STIGNORE = FOLDER / '.stignore'

EXPECTED = '#include syncthing/ignore_default_folder.txt\n'

STIGNORE_INCLUDE = {
    '~/syncthing/default': '.syncthing/ignore_default_folder.txt',
    '~/storage/shared': '.syncthing/ignore_android.txt',
}

def write_stignore(path, contents):
    print('Writring', path)
    path.write_text(contents)


for sync_folder, include_path in STIGNORE_INCLUDE.items():
    sync_folder = pathlib.Path(sync_folder).expanduser()
    expected_contents = f'#include {include_path}\n'

    needs_write = False
    stignore = sync_folder / '.stignore'
    if sync_folder.is_dir():
        if stignore.is_file():
            if stignore.read_text() != expected_contents:
                needs_write = True
        else:
            needs_write = True

    if needs_write:
        print('Writing', stignore)
        stignore.write_text(expected_contents)
