#!/usr/bin/env python3
import pathlib

FOLDER = pathlib.Path('~/syncthing/default').expanduser()
STIGNORE = FOLDER / '.stignore'

EXPECTED = '#include syncthing/ignore_default_folder.txt\n'


def write_expected(path):
    print('Writing', path)
    path.write_text(EXPECTED)


if FOLDER:
    if STIGNORE.exists():
        if STIGNORE.read_text() != EXPECTED:
            write_expected(STIGNORE)
    else:
        write_expected(STIGNORE)
