#!/bin/sh
set -e

if [ $# -ne 2 ]; then
    echo 'usage: (fat32|ntfs) DEVICE' >&2
    exit 1
fi

FSTYPE="$1"
DEVICE="$2"

if [ "$(lsblk -ndo type)" != 'part' ]; then
    echo 'error: DEVICE is not a partition' >&2
    exit 1
fi

# partx is more likely to be up-to-date than lsblk
# (ex. after modifying the partition table)
PART_SIZE="$(partx --noheadings --output SIZE --bytes "$DEVICE")"

case "$FSTYPE" in
    fat32)
        fatresize -p --verbose -s $((PART_SIZE - 1)) "$DEVICE"
        fsck.fat -a "$DEVICE"
        ;;
    ntfs)
        ntfsresize -f -s "$PART_SIZE" "$DEVICE"
        ntfsfix -b -d "$DEVICE"
        ;;
    _)
        echo 'error: must specify either fat32 or ntfs' >&2
        exit 1
        ;;
esac
