#!/usr/bin/env sh
check_wifi1() {
    INSTALLED_VERSION='3004_384_19_0'
    CURRENT_VERSION="$(ssh wifi1 nvram get webs_state_info)"
    if [ "$INSTALLED_VERSION" != "$CURRENT_VERSION" ]; then
        echo "wifi1 is out-of-date (latest: $CURRENT_VERSION)" >&2
        exit 1
    else
        echo wifi1 is up-to-date
    fi
}
