#!/usr/bin/env sh
set -e
for f in "$@"; do
    target="$f".7z
    if [ -e "$target" ]; then
        echo "error: $f already exists" >&2
        exit 1
    fi
    7z a "$target" "$f"
    rm -r "$f"
done
