#!/usr/bin/env sh
termdown "$@" || exit
trap INT exit
while true; do
    play -nq -t alsa synth 0.15 square 440
    play -nq -t alsa synth 0.15 saw 440
    play -nq -t alsa synth 0.15 square 440
    play -nq -t alsa synth 0.15 saw 440
    play -nq -t alsa synth 0.15 saw 440
done
