#!/usr/bin/env python
import sys
import subprocess


def mockingly(text):
    next_upper = False
    chars = []
    for c in text:
        if next_upper:
            c = c.upper()
            next_upper = False
        else:
            c = c.lower()
            next_upper = True
        chars.append(c)
    return "".join(chars)


class Clipboard:
    @staticmethod
    def get():
        proc = subprocess.run(["cbpaste"], stdout=subprocess.PIPE, check=True)
        return proc.stdout

    @staticmethod
    def set(data):
        subprocess.run(["cbcopy"], input=data.encode(), check=True)


if not sys.stdin.isatty():
    if len(sys.argv) > 1:
        raise RuntimeError("unexpected arguments")
    data = sys.stdin.read()
elif len(sys.argv) == 1:
    data = Clipboard.get().decode()
elif len(sys.argv) >= 2:
    data = " ".join(sys.argv[1:])
else:
    raise NotImplementedError

result = mockingly(data)
data = Clipboard.set(result)
sys.stdout.write(result)
