#!/usr/bin/env sh
set -e

ANDROID_BASE=~/.android

if [ -z "$1" ]; then
    SDK_VERSION="$(ls "$ANDROID_BASE/sdk/build-tools" | sort | tail -n 1)"
else
    SDK_VERSION="$1"
    if ! [ -d "$ANDROID_BASE/sdk/build-tools/$SDK_VERSION" ]; then
        echo error: SDK version not found >&2
        ls "$ANDROID_BASE/sdk/build-tools" | sort >&2
        exit 1
    fi
fi

rm -f .envrc
cat > .envrc <<EOF
export PATH="\
$DOTFILES/scripts/android:\
$ANDROID_BASE/sdk/build-tools/$SDK_VERSION:\
$ANDROID_BASE/sdk/emulator:\
$ANDROID_BASE/sdk/platform-tools:\
$ANDROID_BASE/sdk/tools/bin:\
$ANDROID_BASE/sdk/tools:\
/opt/android-studio/jre/bin/:\
$PATH"

export ANDROID_HOME="$ANDROID_BASE/sdk"
export ANDROID_NDK_HOME="$ANDROID_HOME/sdk/ndk-bundle"
EOF

direnv allow
