#!/usr/bin/env python
import argparse
import base64
import sys


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        '-d', dest='decode', action='store_true', help='decode')
    parser.add_argument('text')
    args = parser.parse_args()

    text = args.text.encode()
    result = base64.b64decode(text) if args.decode else base64.b64encode(text)
    sys.stdout.write(result.decode())


if __name__ == '__main__':
    main()
