#!/usr/bin/env python
# - trims leading+trailing whitespace from input strings
# - perform multiple base64 decode passes for nested encoding
# - use clipboard if no arguments
import base64
import sys
import subprocess


def maybe_base64_decode(value):
    try:
        while True:
            if not value:
                return value
            value = base64.b64decode(value, validate=True)
    except Exception:
        return value


if not sys.stdin.isatty():
    if len(sys.argv) > 1:
        raise RuntimeError("unexpected arguments")
    data = sys.stdin.read()
elif len(sys.argv) == 1:
    proc = subprocess.run(["cbpaste"], stdout=subprocess.PIPE)
    if proc.returncode:
        sys.exit(proc.returncode)
    data = proc.stdout.decode()
elif len(sys.argv) >= 2:
    data = " ".join(sys.argv[1:])
else:
    print(len(sys.argv))
    raise NotImplementedError

data = data.strip().encode()

result = maybe_base64_decode(data)
if result == data:
    raise ValueError("cannot decode")

sys.stdout.buffer.write(result)
