#!/usr/bin/env python
# - base64-encodes input as-is
# - outputs a single string without extraneous whitespace
# - uses clipboard if no arguments
import base64
import sys
import subprocess

if not sys.stdin.isatty():
    if len(sys.argv) > 1:
        raise RuntimeError("unexpected arguments")
    data = sys.stdin.read()
elif len(sys.argv) == 1:
    proc = subprocess.run(["cbpaste"], stdout=subprocess.PIPE)
    if proc.returncode:
        sys.exit(proc.returncode)
    data = proc.stdout.decode()
elif len(sys.argv) == 2:
    data = sys.argv[1]
else:
    print(len(sys.argv))
    raise NotImplementedError

result = base64.b64encode(data.encode())
sys.stdout.buffer.write(result)
