#!/usr/bin/env python3
import argparse
import pathlib
import re


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('regex', type=re.compile)
    parser.add_argument('replacement')
    parser.add_argument('path', nargs='+', type=pathlib.Path)
    args = parser.parse_args()

    path_targets = {}
    for path in args.path:
        target = path.with_name(args.regex.sub(args.replacement, path.name))
        if target == path:
            continue
        if target.exists():
            parser.error(f'already exists {target}')
            parser.exit(1)
        path_targets[path] = target

    for source, target in path_targets.items():
        source.rename(target)


if __name__ == '__main__':
    main()
