#!/usr/bin/env python3
import argparse
import pathlib


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--lstrip', default='')
    parser.add_argument('--rstrip', default='')
    parser.add_argument('--append', default='')
    parser.add_argument('--prepend', default='')
    parser.add_argument('path', nargs='*', type=pathlib.Path)
    args = parser.parse_args()

    path_targets = {}
    for path in args.path:
        name = path.name.lstrip(args.lstrip).rstrip(args.rstrip)
        target = path.with_name(''.join([
            args.prepend,
            name,
            args.append
        ]))
        if target == path:
            continue
        if target.exists():
            parser.error(f'already exists {target}')
            parser.exit(1)
        path_targets[path] = target

    for source, target in path_targets.items():
        source.rename(target)


if __name__ == '__main__':
    main()
