#!/usr/bin/env sh
if command -v xclip > /dev/null; then
    exec xclip -selection c
elif command -v termux-clipboard-set > /dev/null; then
    exec termux-clipboard-set
elif command -v pbcopy > /dev/null; then
    exec pbcopy
fi
