#!/bin/bash
if type xclip >& /dev/null ; then
    exec xclip -selection c
elif type termux-clipboard-set >& /dev/null ; then
    exec termux-clipboard-set
elif type pbcopy >& /dev/null ; then
    exec pbcopy
fi
