#!/usr/bin/env sh
if [ -n "$WAYLAND_DISPLAY" ]; then
    exec wl-paste
elif command -v xclip > /dev/null; then
    exec xclip -selection c -o
elif command -v termux-clipboard-get > /dev/null; then
    exec termux-clipboard-get
elif command -v pbcopy > /dev/null; then
    exec pbpaste
fi
