#!/bin/bash
if type xclip >& /dev/null ; then
    exec xclip -selection c -o
elif type termux-clipboard-get >& /dev/null ; then
    exec termux-clipboard-get
elif type pbcopy >& /dev/null ; then
    exec pbpaste
fi
