#!/usr/bin/env python
import argparse

import pint


UNIT_REGISTRY = pint.UnitRegistry()


def _unit_argument(value):
    try:
        return UNIT_REGISTRY[value]
    except pint.errors.UndefinedUnitError as e:
        raise argparse.ArgumentTypeError(str(e))


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("from_amount", type=_unit_argument)
    parser.add_argument("to_unit", type=_unit_argument)
    args = parser.parse_args()

    print(args.from_amount.to(args.to_unit))


if __name__ == "__main__":
    main()
