#!/usr/bin/env sh
set -e
REPO_DIR="$(git install -k https://git.kernel.org/pub/scm/utils/dash/dash.git)"
cd "$REPO_DIR"
git checkout "$(git describe --abbrev=0 --tags)"
./autogen.sh
./configure
make -j8
ln -sf "$PWD/src/dash" "$HOME/.bin/dash"
ln -sf "$PWD/src/dash" "$HOME/.bin/sh"
