#!/usr/bin/env sh
set -e
REPO_DIR="$(git install -k https://git.kernel.org/pub/scm/utils/dash/dash.git)"
cd "$REPO_DIR"
git checkout "$(git describe --abbrev=0 --tags)"
./autogen.sh
./configure --prefix="$HOME/.local"
make -j8
make install
mkdir -p "$HOME/.bin"
ln -sf "$HOME/.local/bin/dash" "$HOME/.local/bin/sh"
