#!/usr/bin/env sh
set -e
PREFIX="$HOME/.local"
REPO_DIR="$(git install -k https://git.kernel.org/pub/scm/utils/dash/dash.git)"
cd "$REPO_DIR"
git checkout "$(git describe --abbrev=0 --tags)"
./autogen.sh
./configure --prefix="$PREFIX"
make -j8
make install
ln -sf "$PREFIX/bin/dash" "$PREFIX/bin/sh"
