#!/usr/bin/env sh
set -e

BANG_CACHE=~/.cache/ddg_bang.cache

update_bang_cache() {
    if [ -e "$BANG_CACHE" ]; then
        mod="$(stat --format=%Y "$BANG_CACHE" 2>/dev/null)"
        if [ "$mod" -lt "$(date --date '14 days ago' +%s)" ]; then 
            download_bang_cache
        fi
    else
        download_bang_cache
    fi
}

download_bang_cache() {
    echo Downloading bang list >&2
    curl -s https://duckduckgo.com/bang.js | jq -r '.[] | ["!" + .t, .s, .d] | @tsv' > "$BANG_CACHE" 
}

show_help() {
    cat << EOF
usage: ddg QUERY [QUERY]

    --bangs     search for bangs and exit
    --help      show help and exit
EOF
}


while true; do
    case "$1" in
        --bangs)
            update_bang_cache
            fzf < "$BANG_CACHE" | awk '{print $1}'
            exit
            ;;
        --help)
            show_help
            exit
            ;;
        --)
            shift
            break
            ;;
        *)
            if [ $# -eq 0 ]; then
                echo error: no argument provided >&2
                exit 1
            fi
            break
    esac
done

if command -v firefox > /dev/null; then
    nohup firefox --private-window "https://duckduckgo.com/?q=$*" > /dev/null 2>&1 &
else
    exec open "https://duckduckgo.com/?q=$*"
fi
