#!/usr/bin/env sh
set -e

download_bang_list() {
    curl -s --compressed https://duckduckgo.com/bang.js | jq -r '.[] | ["!" + .t, .s, .d] | @tsv'
}

show_help() {
    cat << EOF
usage: ddg QUERY [QUERY]

    --bangs     show bang list and exit
    --help      show help and exit
EOF
}


while true; do
    case "$1" in
        --bangs)
            download_bang_list
            exit
            ;;
        --help)
            show_help
            exit
            ;;
        --)
            shift
            break
            ;;
        *)
            if [ $# -eq 0 ]; then
                echo error: no argument provided >&2
                exit 1
            fi
            break
    esac
done

exec open "https://duckduckgo.com/?q=$*"
