#!/usr/bin/env sh
set -e

usage() {
    cat << EOF
usage: dl [OPTIONS] url [url ...]

optional arguments:
    --help      show help and exit
    --insecure  disable certificate validation
EOF
}

DL_INSECURE=
while [ $# -ge 1 ]; do
    case "$1" in
        --help)
            usage
            exit
            ;;
        --insecure)
            DL_INSECURE=1
            shift
            ;;
        -*)
            echo 'error: unrecognized argument' >&2
            exit 1
            ;;
        *)
            break
    esac
done

download() {
    case "$1" in
        http://www.youtube.com*|\
        http://youtube.com*|\
        https://www.youtube.com*|\
        https://youtube.com*)
            yt-dlp "$1"
            ;;
        *)
            if command -v aria2c > /dev/null; then
                if [ -n "$DL_INSECURE" ]; then
                    aria2c --check-certificate=false -x 16 -j 20 --split 20 "$@"
                else
                    aria2c -x 16 -j 20 --split 20 "$@"
                fi
            elif command -v curl > /dev/null; then
                if [ -n "$DL_INSECURE" ]; then
                    curl --insecure -L -O "$@"
                else
                    curl -L -O "$@"
                fi
            fi
    esac
}
if [ $# -eq 0 ]; then
    if [ -t 0 ]; then
        download "$(cbpaste 2> /dev/null)"
    else
        download "$(urlextract)"
    fi
else
    for link in "$@"; do
        download "$link"
    done
fi
