#!/usr/bin/env sh
set -e

MAGENTA='\033[1;35m'
RESET='\033[0m'

update_repo() {
    if [ -d "$2/.git" ]; then
        printf "${MAGENTA}Updating $1 ($2)...${RESET}\n"
        git auto-update "$2"
    fi

    # non-user files
    BACKUP_ROOT="$2"/desktop
    if [ -d "$BACKUP_ROOT" ]; then
        for source in $(find "$BACKUP_ROOT" -type f); do
            target=${source#$BACKUP_ROOT}
            if [ -f "$target" ]; then
                echo Found "$target"
                if ! diff "$source" "$target" > /dev/null ; then
                    echo Syncing "$target"
                    sudo cp "$source" "$target"
                fi
            fi
        done
    fi
}

update_repo "DOTFILES" "$DOTFILES"


for d in $(env | grep ^DOTFILES_ | sort); do
    name="$(echo "$d" | cut -d = -f 1)"
    loc="$(echo "$d" | cut -d = -f 2)"
    update_repo "$name" "$loc"
done
