#!/usr/bin/env sh
set -e

if [ "$1" = '-v' ]; then
    VERBOSE=1
    shift
fi

MAGENTA='\033[1;35m'
RESET='\033[0m'

update_repo() {
    if [ -d "$2/.git" ]; then
        printf "${MAGENTA}Updating $1 ($2)...${RESET}\n"
        git auto-update "$2"
    fi

    # non-user files
    if command -v sudo > /dev/null; then
        for tag in common "$(hostname)"; do
            backup_root="$2/non-user/$tag"
            if [ -d "$backup_root" ]; then
                for source in $(find "$backup_root" -type f); do
                    target=${source#$backup_root}
                    if test -f "$target" || [ "$tag" != 'common' ]; then
                        if ! diff "$source" "$target" > /dev/null 2>&1 ; then
                            echo Syncing "$target"
                            sudo cp "$source" "$target"
                        elif [ -n "$VERBOSE" ]; then
                            echo Found "$tag" "$target"
                        fi
                    fi
                done
            fi
        done
    fi
}

update_repo "DOTFILES" "$DOTFILES"


for d in $(env | grep ^DOTFILES_ | sort); do
    name="$(echo "$d" | cut -d = -f 1)"
    loc="$(echo "$d" | cut -d = -f 2)"
    update_repo "$name" "$loc"
done
