#!/usr/bin/env bash
GREEN='\033[1;32m'
RED='\033[1;31m'
RESET_COLOR='\033[0m'

column_num() {
    exec < /dev/tty
    oldstty=$(stty -g)
    stty raw -echo min 0
    # on my system, the following line can be replaced by the line below it
    echo -en "\033[6n" > /dev/tty
    # tput u7 > /dev/tty    # when TERM=xterm (and relatives)
    IFS=';' read -r -d R -a pos
    stty $oldstty
    # change from one-based to zero based so they work with: tput cup $row $col
    row=$((${pos[0]:2} - 1))    # strip off the esc-[
    col=$((${pos[1]} - 1))
    echo $col
}

"$@"
ret=$?
if [ "$ret" != '0' ]; then
    color="$RED"
else
    color="$GREEN"
fi
if [ "$(column_num 2> /dev/null)" != '0' ]; then
    # printf '%b%%%b\n' "$REVERSE_COLOR" "$RESET_COLOR"
    printf '\n'
fi
printf '%b%bExit %s - %s%b\n' "$RESET_COLOR" "$color" "$ret" "$(date -u +"%Y-%m-%d %H:%M:%S")" "$RESET_COLOR"
