#!/usr/bin/env bash
set -e

show_help() {
    cat << EOF
usage: extract [-i] [-r] [-d] FILE [FILE ...]
    -c      create a child directory for each archive and extract there
    -p      parent directory to extract to. defaults to directory where archive resides
    -r      remove archive after successful extraction
EOF
}


gen_target() {
    target="${1%.*}"
    if [ -n "$EXTRACT_BASE" ]; then
        target="$EXTRACT_BASE/$(basename "$target")"
    fi
    if [ -z "$EXTRACT_IN_CHILD" ]; then
        target="$(dirname "$target")"
    fi
    echo "$target"
}


if [ $# -eq 0 ]; then
    show_help >&2
    exit 1
fi

while true; do
    case "$1" in
        -c)
            EXTRACT_IN_CHILD=1
            shift
            ;;
        -r)
            EXTRACT_RM=1
            shift
            ;;
        -p)
            EXTRACT_BASE="$(realpath "$2")"
            shift
            shift
            ;;
        --help)
            show_help
            exit
            ;;
        *)
            break
    esac
done

for filename in "$@"; do
    if ! [ -e "$filename" ]; then
        echo "error: file not found \"$filename\"" >&2
        exit 1
    fi
done

for filename in "$@"; do
    target="$(gen_target "$filename")"
    tarext=".tar."
    if [ "${filename#*$tarext}" != "$filename" ]; then
        target="$(gen_target "$target")"
        7z x "${filename}" -so | 7z x -aoa -si -ttar -o"${target}"
    else
        7z x -spe -o"${target}" "${filename}"
    fi
    if [ -n "$EXTRACT_RM" ]; then
        rm "$filename"
    fi
done
