#!/usr/bin/env sh
set -e

PIPEDIR="${TMPDIR:-/tmp}"
PIPEPREFIX="fanpipe"
TOPIC=''

show_usage() {
    printf '%s' \
'usage: fanpipe (-p|-s) [-f] [-t TOPIC] [MESSAGE [MESSAGE ...]]
    -p, --publish       publish to a pipe
    -s, --subscribe     subscribe to a pipe until one message is received
    -f, --follow        subscribe indefinitely
    -t, --topic=TOPIC   topic name
        --help          display this help and exit
'
}

while [ $# -gt 0 ]; do
    case "$1" in
        -p|--publish)
            PUBLISH=1
            shift
            ;;
        -s|--subscribe)
            SUBSCRIBE=1
            shift
            ;;
        -f|--follow)
            FOLLOW=1
            shift
            ;;
        -t|--topic)
            TOPIC="$2"
            shift
            shift
            ;;
        --help)
            show_usage
            exit
            ;;
        *)
            break
    esac
done

for pipe in "${PIPEDIR}/${PIPEPREFIX}-"*; do
    if [ -e "$pipe" ]; then
        pid="${pipe##*-}"
        if ! kill -0 "$pid" > /dev/null 2>&1; then
            rm -f "$pipe"
        fi
    fi
done

if [ -n "$PUBLISH" ]; then
    data="$*"
    set "${PIPEDIR}/${PIPEPREFIX}-${TOPIC}-"*
    if [ "$1" != "${PIPEDIR}/${PIPEPREFIX}-${TOPIC}-*" ]; then
        if [ -t 0 ]; then
            printf '%s' "$data" | tee "$@" > /dev/null
        else
            tee "$@" > /dev/null
        fi
    fi
elif [ -n "$SUBSCRIBE" ]; then
    pipe="${PIPEDIR}/${PIPEPREFIX}-${TOPIC}-$$"
    exit_trap() {
        rm -f "$pipe"
    }
    trap exit_trap EXIT
    mkfifo "$pipe"
    while true; do
        cat "$pipe"
        if [ -z "${FOLLOW}" ]; then
            break
        fi
    done
else
    show_usage >&2
    exit 1
fi
