#!/usr/bin/env python3
import argparse
import pathlib


def all_files(root):
    stack = [root]
    files = set()
    while stack:
        for path in stack.pop().iterdir():
            if path.is_dir():
                stack.append(path)
            else:
                files.add(path)
    return files


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--separator", default="_")
    parser.add_argument("path", type=pathlib.Path)
    args = parser.parse_args()

    for path in all_files(args.path):
        if path.parent == args.path:
            continue
        path = path.relative_to(args.path)
        parts = list(path.parents)[:-1]
        parts.append(path.name)
        newname = args.separator.join(str(p) for p in parts)
        newpath = args.path / newname
        if newpath.exists():
            print(path)
            print(newpath)
            raise RuntimeError
        path.rename(newpath)


if __name__ == "__main__":
    main()
