#!/usr/bin/env sh
set -eu

UPDATE_DIR="$DOTFILES/full-update"

YELLOW='\033[1;33m'
RESET_COLOR='\033[0m'

run_script() {
    printf '%bRunning %s ...%b\n' "$YELLOW" "${1##*/}" "$RESET_COLOR"
    "$@"
}

show_help() {
    cat << EOF
usage: full-update [script ...]

    --help      show help and exit
    --list      list scripts and exit
EOF
}

while [ $# -gt 0 ]; do
    case "$1" in
        --list)
            find "$UPDATE_DIR" -type f -printf '%f\n' | sort -n
            exit
            ;;
        --help)
            show_help
            exit
            ;;
        *)
            script="$1"
            shift
            run_script "$UPDATE_DIR"/"$script" "$@"
            exit
            ;;
    esac
done

printf '%bfull-update - start %s%b\n' "$YELLOW" "$(date)" "$RESET_COLOR"
for cmd in "$UPDATE_DIR"/*; do
    run_script "$cmd"
done
printf '%bfull-update - done %s%b\n' "$YELLOW" "$(date)" "$RESET_COLOR"
