#!/usr/bin/env sh
lookup_geoip() {
    curl "http://ip-api.com/json/$1" 2> /dev/null | jq -S
}

if [ -t 0 ]; then
    data="$*"
else
    data="$(cat -)"
fi

for value in $data; do
    lookup_geoip "$value"
done
