#!/usr/bin/env bash
if [ -z $1 ]; then
    if git status 2> /dev/null; then
        GIT_DIR='.'
    else
        echo ERROR: No git directory specified
        exit 1
    fi
else
    GIT_DIR="$1"
fi

cd "${GIT_DIR}"
git pull

error_code=$?

if [[ $error_code != 0 ]]; then
    exit $error_code
fi

branch=$(git rev-parse --abbrev-ref HEAD)
if [ $(git status --porcelain | wc -l) -gt 0 ]; then
    git add -A
    git commit -m "git-auto-update $(date +"%Y-%m-%d %H:%M:%S")"
fi

if [ $(git log origin/master..master | wc -l) -gt 0 ]; then
    git push
fi
