#!/bin/sh
set -e

REMOTE="$1"
TAG="$2"

if [[ -z "$REMOTE" || -z "$TAG" ]]; then
    echo 'usage: git rm-tag <remotename> <tagname>'
    exit 1
fi

git tag -d "$TAG"
git push "$REMOTE" :refs/tags/"$TAG"
