#!/usr/bin/env sh
YELLOW='\033[1;33m'
RESET_COLOR='\033[0m'


log() {
    if [ -n "$LOGGED_FIRST" ]; then
        echo
    else
        LOGGED_FIRST=1
    fi
    echo "${YELLOW}> $@${RESET_COLOR}"
}

# ensure git repo
git status > /dev/null
EC=$?
if [ "$EC" != 0 ]; then
    exit "$EC"
fi

log Remote
git remote -v

log All Branch
git branch

log Changes
git status --short --show-stash --branch
