#!/usr/bin/env sh
ipv4="$(curl https://ipv4.icanhazip.com 2> /dev/null)"
ipv6="$(curl https://ipv6.icanhazip.com 2> /dev/null)"
if [ -t 1 ]; then
    echo IPv4: "$ipv4"
    echo IPv6: "$ipv6"
else
    echo "$ipv4"
    echo "$ipv6"
fi
