#!/usr/bin/env python3
import argparse
import pathlib

import PIL.Image


SUFFIXES = {
    ".bmp",
    ".gif",
    ".jpeg",
    ".jpg",
    ".png",
    ".png",
    ".tif",
    ".tiff",
    ".webp",
}


def all_files(root):
    stack = [root]
    files = []
    while stack:
        for path in stack.pop().iterdir():
            if path.is_dir():
                stack.append(path)
            else:
                files.append(path)
    return files


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("path", type=pathlib.Path, nargs="+")
    args = parser.parse_args()

    paths = {}
    for path in args.path:
        if path.is_file():
            paths[path] = None
        else:
            paths.update({p: None for p in all_files(path)})

    for path in sorted(paths):
        if path.suffix.lower() not in SUFFIXES:
            continue
        im = PIL.Image.open(path)
        paths[path] = im.size
        im.close()

    for path in sorted(paths):
        value = paths[path]
        if value is None:
            continue
        print(*value, path)


if __name__ == "__main__":
    main()
