#!/usr/bin/env sh
set -e
IMAGE=denji/docker-image_optim
if command -v podman > /dev/null; then
    exec conrun \
        --pull \
        --podman \
        --here \
        "${IMAGE}" \
        image_optim "$@"
elif command -v docker > /dev/null; then
    exec conrun \
        --pull \
        --docker \
        --here \
        --me \
        "${IMAGE}" \
        image_optim "$@"
fi
