#!/usr/bin/env sh
set -e
IMAGE=denji/docker-image_optim
container_name="image_optim-$$"
if command -v podman > /dev/null; then
    trap "podman kill "${container_name}" > /dev/null 2>&1; true" HUP EXIT
    if [ -t 0 -a -t 1 -a -t 2 ]; then
        tty_flag="-t"
    fi
    podman pull -q "${IMAGE}" > /dev/null
    podman run \
        --rm \
        -i $tty_flag \
        --name "${container_name}" \
        --volume "$(pwd):$(pwd)" \
        --workdir "$(pwd)" \
        "${IMAGE}" \
        image_optim "$@"
elif command -v docker > /dev/null; then
    trap "docker kill "${container_name}" > /dev/null 2>&1; true" HUP EXIT
    if [ -t 0 -a -t 1 -a -t 2 ]; then
        tty_flag="-t"
    fi
    docker pull "${IMAGE}" > /dev/null
    docker run \
        --rm \
        -i $tty_flag \
        --name "${container_name}" \
        --volume "$(pwd):$(pwd)" \
        --workdir "$(pwd)" \
        --user "$(id -u):$(id -g)" \
        "${IMAGE}" \
        image_optim "$@"
fi
