#!/usr/bin/env python3
import argparse

from PIL import Image


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("path", nargs="+")
    args = parser.parse_args()

    max_width = 0
    max_height = 0
    for path in args.path:
        im = Image.open(path)
        width, height = im.size
        max_width = max(width, max_width)
        max_height = max(height, max_height)

    print(f"{max_width}x{max_height}")


if __name__ == "__main__":
    main()
