#!/usr/bin/env sh
set -e
PREFIX="$HOME/.local"
REPO_DIR="$(git install https://github.com/stedolan/jq.git)"
cd "$REPO_DIR"
git checkout -q "$(git tag --sort=committerdate | grep -v rc | tail -n 1)"

current_version=$(git rev-parse --short HEAD)
key="git-install/jq"
if [ "$(kv $key || true)" != "$current_version" ]; then
    autoreconf -i
    ./configure --prefix="$PREFIX" --disable-maintainer-mode
    make -j8
    make install
    kv $key $current_version
fi
