#!/usr/bin/env python3
import argparse
import json
import sys


def flatten(root, delimiter):
    stack = [([], root)]
    flat = {}
    while stack:
        prefixes, data = stack.pop()
        for key, value in data.items():
            prefix = prefixes.copy()
            prefix.append(key)

            if isinstance(value, dict):
                stack.append((prefix, value))
            else:
                if any(delimiter in part for part in prefix):
                    raise ValueError("separator found in prefix")
                flat_key = delimiter.join(prefix)
                if flat_key in flat:
                    raise KeyError(f'duplicate key "{flat_key}"')
                flat[flat_key] = value
    return flat


def main():
    parser = argparse.ArgumentParser("json-flat")
    parser.add_argument("delimiter")
    parser.add_argument(
        "data", nargs="?", default=sys.stdin, type=argparse.FileType("r")
    )
    args = parser.parse_args()

    data = json.load(args.data)
    data = flatten(data, args.delimiter)
    print(json.dumps(data, indent=2, sort_keys=True, ensure_ascii=False))


if __name__ == "__main__":
    main()
