#!/usr/bin/env python3
import argparse
import json
import sys


def nest(data, delimiter):
    nested = {}

    for okey, value in sorted(data.items()):
        d = nested
        parts = okey.split(delimiter)
        key = parts.pop(-1)
        if key == "":
            continue

        for part in (p for p in parts if p != ""):
            if part not in d:
                d[part] = {}
            elif part in d and not isinstance(d[part], dict):
                d[part] = {}
            d = d[part]

        d[key] = value

    return nested


def main():
    parser = argparse.ArgumentParser("json-nest")
    parser.add_argument("delimiter")
    parser.add_argument(
        "data", nargs="?", default=sys.stdin, type=argparse.FileType("r")
    )
    args = parser.parse_args()

    data = json.load(args.data)
    data = nest(data, args.delimiter)
    print(json.dumps(data, indent=2, sort_keys=True, ensure_ascii=False))


if __name__ == "__main__":
    main()
