#!/usr/bin/env sh
# A filesystem-based key/value utility
#
# Usage:
#
# # list keys
# $ kv
# a
#
# # set key
# $ kv b value
# $ kv
# a
# b
#
# # get key value
# $ kv b
# value
#
# # delete key with zero-length parameter
# $ kv b ''
# $ kv
# a
#
# Environment:
# KVDIR: root of the key/value store. Defaults to $HOME/.local/share/kv
#
# Dependencies:
# - GNU Findutils
# - GNU Coreutils
set -e

KVDIR="$(realpath -m "${KVDIR:-"$HOME/.local/share/kv"}")"
KEY="$1"
VALUE="$2"

if [ $# -eq 0 ]; then
    if [ -d "$KVDIR" ]; then
        cd "$KVDIR"
        find . -type f -printf '%P\n'
    fi
else
    mkdir -p "$KVDIR"

    # restrict key to be under the $KVDIR (prevent ../ usage)
    USER_KEY_PATH="$KVDIR/$KEY"
    KEY_PATH="$(realpath -m "$USER_KEY_PATH")"
    if [ "$USER_KEY_PATH" != "$KEY_PATH" ]; then
        echo error: invalid key >&2
        exit 1
    fi

    if [ $# -eq 1 ]; then
        if [ -e "$KEY_PATH" ]; then
            cat "$KEY_PATH"
        else
            exit 1
        fi
    elif [ $# -eq 2 ]; then
        if [ -z "$VALUE" ]; then
            rm -rf "$KEY_PATH"
        else
            mkdir -p "$(dirname "$KEY_PATH")"
            printf "$VALUE" > "$KEY_PATH"
            find "$KVDIR" -type d -empty -delete
        fi
    fi
fi
