#!/bin/bash
set -e

TOPIC='file-updated'

kill_all() {
    jobs -rp | xargs -L 1 pkill -P &> /dev/null || true
    pkill -P $$ &> /dev/null || true
}


if [ -z $1 ]; then
    echo Publishing event for current directory
    zmq pub "$TOPIC" "$PWD"/
    exit
fi

trap "exit 1" SIGINT
trap "kill_all" EXIT

while true; do
    kill_all

    # exit tmux copy-mode
    if [[ -n $TMUX ]]; then
        tmux if -F -t $TMUX_PANE "#{pane_in_mode}" "send-keys -t $TMUX_PANE -X cancel"
    fi

    clear
    "$@" &

    disown
    while true; do
        FILE=$(zmq sub -t "$TOPIC" | cut -f2- -d ' ')
        if [[ "$FILE" == "$PWD"/* ]]; then
            break
        fi
    done
done
