#!/usr/bin/env sh
set -e

FANPIPE_TOPIC='lmk-fs-event'

publish_message() {
    fanpipe --publish --topic "$FANPIPE_TOPIC"
}

get_message() {
    fanpipe --subscribe --topic "$FANPIPE_TOPIC"
}

show_help() {
    cat << EOF
usage: lmk [--help] [COMMAND [ARGUMENT ...]]
    -q, --quiet     Suppress the exit status line
        --help      Display this help and exit
EOF
}

while true; do
    case "$1" in
        --)
            shift
            break
            ;;
        --help)
            show_help
            exit
            ;;
        *)
            break
    esac
done

if [ $# -eq 0 ]; then
    publish_message "$PWD"
    exit
fi

if [ -n "$TMUX" ]; then
    (get_message && tmux respawn-pane -k -t "$TMUX_PANE" lmk "$@") > /dev/null 2>&1 &
    "$@"
    wait
else
    tmux -L lmk-$$ -f /dev/null \
        new-session lmk "$@" ';' \
        unbind -a ';' \
        set-option status off ';' \
        set-option destroy-unattached on ';' \
        set-option detach-on-destroy on ';' \
        attach -r
fi
