#!/bin/bash
set -e

PYTHON3_BIN=$(which -a python3 | grep -v "^$VIRTUAL_ENV" | head -n 1 | tr -d '\n')
ZMQ_BIN=$(which zmq)

TOPIC='lmk-fs-event'
LINK_PWD=$(readlink -f "$PWD")

kill_all() {
    jobs -rp | xargs -L 1 pkill -P &> /dev/null || true
    pkill -P $$ &> /dev/null || true
}


publish_message() {
    "$PYTHON3_BIN" "$ZMQ_BIN" pub "$TOPIC" "$1"
}

get_message() {
    "$PYTHON3_BIN" "$ZMQ_BIN" sub -t "$TOPIC" | cut -f2- -d ' '
}


if [ -z $1 ]; then
    publish_message "$PWD"
    exit
elif [[ $1 == '--path' ]]; then
    publish_message "$(readlink -f "$2")"
    exit
fi


trap "exit 1" SIGINT
trap "kill_all" EXIT

while true; do
    kill_all

    # exit tmux copy-mode
    if [[ -n $TMUX ]]; then
        tmux if -F -t $TMUX_PANE "#{pane_in_mode}" "send-keys -t $TMUX_PANE -X cancel"
    fi

    clear
    "$@" &

    disown
    while true; do
        EVENT_PATH=$(get_message)
        if [[ "$EVENT_PATH"/ == "$PWD"/* || "$EVENT_PATH"/ == "$LINK_PWD"/* ]]; then
            break
        fi
    done
done
