#!/usr/bin/env sh
_lower() {
    tr '[:upper:]' '[:lower:]'
}

if [ $# -gt 0 ]; then
    if [ $# -eq 1 ]; then
        printf '%s' "$1" | _lower
    else
        echo 'error: unexpected arguments' >&2
        exit 1
    fi
else
    _lower
fi
