#!/usr/bin/env sh
if command -v xdg-mime > /dev/null; then
get_mime() {
    xdg-mime query filetype "$1"
}
else
get_mime() {
    file --brief --mime-type "$1"
}
fi

for i in "$@"; do
    printf '%s\t%s\n' "$(get_mime "$i")" "$i"
done
