#!/usr/bin/env sh
if command -v xdg-mime > /dev/null; then
get_mime() {
    # allows for overrides in ~/.local/share/mime/packages to work
    # on headless system.
    export XDG_CURRENT_DESKTOP="${XDG_CURRENT_DESKTOP:=kde}"

    xdg-mime query filetype "$1"
}
else
get_mime() {
    file --brief --mime-type "$1"
}
fi

get_mime "$1"
