#!/usr/bin/env sh
get_mime() {
    if command -v xdg-mime > /dev/null; then
        xdg-mime query filetype "$1"
    else
        file --brief --mime-type "$1"
    fi
}

if [ $# -gt 1 ]; then
    for i in "$@"; do
        printf '%s\t%s\n' "$(get_mime "$i")" "$i"
    done
else
    get_mime "$1"
fi
