#!/usr/bin/env python
import argparse
import collections
import json
import pathlib

import magic


def all_files(root):
    stack = [pathlib.Path(root)]
    files = []
    while stack:
        for path in stack.pop().iterdir():
            if path.is_file():
                files.append(path)
            elif path.is_dir():
                stack.append(path)
    return files


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('path', default='.', nargs='?')
    args = parser.parse_args()

    exts = collections.defaultdict(set)
    for path in all_files(args.path):
        mime = magic.from_file(str(path), mime=True)
        exts[mime].add(path)

    exts = {
        ext: sorted(str(p.resolve()) for p in paths)
        for ext, paths in exts.items()
    }

    print(json.dumps(exts, indent=2, sort_keys=True))


if __name__ == '__main__':
    main()
