#!/usr/bin/env sh
YELLOW='\033[1;33m'
RESET='\033[0m'

echo "${YELLOW}CPU (MHz)${RESET}"
cat /proc/cpuinfo | grep MHz | awk '{print int($4)}'
echo

echo "${YELLOW}Memory${RESET}"
free -m
echo

echo "${YELLOW}Sensors${RESET}"
sensors
