#!/usr/bin/env sh
set -e

NORDVPN_BASE=~/.local/share/nordvpn
EXTRA_SCRIPT="$DOTFILES/scripts/openvpn/update-resolv-conf"
CONFIG_URL='https://downloads.nordcdn.com/configs/archives/servers/ovpn.zip'
RECOMMENDED_URL='https://nordvpn.com/wp-admin/admin-ajax.php?action=servers_recommendations'

show_help() {
    cat << EOF
usage: nordvpn [--help] [--random] [--server] [--update]

connect to the recommended NordVPN server

    --help          show help and exit
    --list          show available servers and exit
    --random        use a random server instead of the recommended
    --server        connect to this server
    --tcp           use TCP (default UDP)
    --update        update OpenVPN config files and exit
EOF
}

extract_etag() {
    awk '{ if (tolower($1) == "etag:") print $2 }'
}

update_config() {
    target="$NORDVPN_BASE/ovpn.zip"
    etag="$NORDVPN_BASE/etag"
    remote_etag="$(curl -s --head "$CONFIG_URL" | extract_etag)"
    if [ "$(cat "$etag" 2> /dev/null)" != "$remote_etag" ]; then
        echo "Downloading OpenVPN configuration ..."
        rm -rf "$NORDVPN_BASE"
        mkdir -p "$NORDVPN_BASE"
        curl -sS -D - "$CONFIG_URL" -o "$target" | extract_etag > "$etag"
        7z x "$target" "-o$NORDVPN_BASE" > /dev/null
        rm "$target"
    fi
}

list_servers() {
    cd "$NORDVPN_BASE/ovpn_$NORDVPN_PROTOCOL"
    for f in *; do
        echo "${f%%.*}"
    done
}

LIST_SERVERS=''
RANDOM_CONFIG=''
SERVER=''
NORDVPN_PROTOCOL=udp
while true; do
    case "$1" in
        --help)
            show_help
            exit
            ;;
        --list)
            LIST_SERVERS=1
            shift
            ;;
        --update)
            update_config
            exit
            ;;
        --random)
            RANDOM_CONFIG=1
            shift
            ;;
        --server)
            SERVER="$2"
            shift
            shift
            ;;
        --tcp)
            NORDVPN_PROTOCOL=tcp
            shift
            ;;
        *)
            if [ -n "$SERVER" -a -n "$RANDOM_CONFIG" ]; then
                echo error: cannot use --random and --server together >&2
                exit 1
            fi
            if [ $# -ne 0 ]; then
                show_help >&2
                exit 1
            fi
            break
    esac
done

if [ -n "$LIST_SERVERS" ]; then
    list_servers | sort
    exit
fi

NORDVPN_DIR="$NORDVPN_BASE/ovpn_$NORDVPN_PROTOCOL"

if ! [ -d "$NORDVPN_DIR" ]; then
    update_config
fi

if [ -n "$RANDOM_CONFIG" ]; then
    config_file="$NORDVPN_DIR/$(ls $NORDVPN_DIR | grep ^us | shuf | head -n 1)"
elif [ -n "$SERVER" ]; then
    config_file="$NORDVPN_DIR/$SERVER.nordvpn.com.$NORDVPN_PROTOCOL.ovpn"
else
    recommended_ip=$(curl -s "$RECOMMENDED_URL" | jq -r '.[0].station')
    config_file="$(grep -lr " $recommended_ip " $NORDVPN_DIR)"
    if ! [ -e "$config_file" ]; then
        echo error: recommend config not cached. Run --update >&2
        exit 1
    fi
fi

echo "using $config_file"
sudo openvpn \
    --config "$config_file" \
    --script-security 2 \
    --auth-user-pass "$DOTFILES_PRIVATE/nordvpn/auth" \
    --up "$EXTRA_SCRIPT" \
    --down "$EXTRA_SCRIPT"
