#!/usr/bin/env sh
set -e

NORDVPN_PROTOCOL=udp
NORDVPN_DIR=~/.local/share/nordvpn/ovpn_$NORDVPN_PROTOCOL
EXTRA_SCRIPT=$(which update-resolv-conf)

mkdir -p "$NORDVPN_DIR"

if [ "$1" = 'update' ]; then
    rm -rf ~/.local/share/nordvpn
    curl https://downloads.nordcdn.com/configs/archives/servers/ovpn.zip > ~/ovpn.zip
    7z x ~/ovpn.zip "-o$HOME/.local/share/nordvpn"
    rm ~/ovpn.zip
    grep -r -L SHA512 ~/.local/share/nordvpn | xargs rm
    exit
elif [ "$1" = 'random' ]; then
    config_file="$NORDVPN_DIR/$(ls $NORDVPN_DIR | grep ^us | shuf | head -n 1)"
elif [ -n "$1" ]; then
    echo Unknown argument: \"$1\"
    exit 1
else
    recommended_ip=$(curl -s 'https://nordvpn.com/wp-admin/admin-ajax.php?action=servers_recommendations' | jq -r '.[0].station')
    config_file="$(grep -lr " $recommended_ip " $NORDVPN_DIR)"
fi

echo using $config_file
exec sudo openvpn \
    --config $config_file \
    --script-security 2 \
    --auth-user-pass $DOTFILES_PRIVATE/nordvpn/auth \
    --up $EXTRA_SCRIPT \
    --down $EXTRA_SCRIPT
