#!/usr/bin/env sh
set -e

note_contents_rg() {
    rg \
        -0 \
        --glob '!*.bkp' \
        --glob '!*.dot' \
        --glob '!*.drawio' \
        --glob '!*.svg' \
        --glob '!.git/' \
        --sortr modified \
        --hidden \
        '.+'
}

note_contents() {
    note_contents_rg | sed 's/\x0/\x0 /' | uniq
}

show_fzf() {
    fzf --literal --bind ctrl-l:clear-query | tr '\0' '\n' | head -n 1
}

set_note_file() {
    NOTE_FILE="$(note_contents | show_fzf)"
    #if [ -z "$NOTE_FILE" ]; then
    #    NOTE_FILE="$(printf '' | fzf --print-query || true)"
    #fi
    if [ -z "$NOTE_FILE" ]; then
        exit
    fi
}

NOTES_DIR="${NOTES_DIR:-$HOME/notes}"
if ! [ -d "$NOTES_DIR" ]; then
    echo error: notes directory does not exist: \""$NOTES_DIR"\" >&2
    exit 1
fi
cd "${NOTES_DIR}"

SHOW_PATH=
NO_FZF=
while true; do
    case "$1" in
        -p)
            SHOW_PATH=1
            shift
            ;;
        -d)
            echo "$NOTES_DIR"
            exit
            ;;
        -f)
            set_note_file
            exec notes "$NOTE_FILE"
            ;;
        --no-fzf)
            NO_FZF=1
            shift
            ;;
        *)
            break
    esac
done

if [ -n "$NO_FZF" ]; then
    note_contents
    exit
fi

NOTE_FILE=
case $# in
    0)
        set_note_file
        ;;
    1)
        NOTE_FILE="$1"
        mkdir -p "$(dirname -- "$NOTE_FILE")"
        ;;
    *)
        echo 'error: unknown arguments' >&2
        exit 1
        ;;
esac

if [ -n "$SHOW_PATH" ]; then
    realpath "$NOTE_FILE"
else
    exec "${EDITOR}" -- "$NOTE_FILE"
fi
