#!/usr/bin/env sh
set -e

echo Updating piptfo environment ...
piptfo neovim install > /dev/null 2>&1
piptfo neovim update > /dev/null 2>&1
ln -sf "$(piptfo neovim --venv)/bin/python" ~/.config/nvim/plugged/python

if [ ! -f ~/.config/nvim/autoload/plug.vim ]; then
    echo Installing plugin manager environment ...
    curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi
echo Updating plugins ...
nvim -c 'PlugUpgrade | PlugUpdate | PlugClean | silent UpdateRemotePlugins' -c 'qa'
