#!/usr/bin/env sh
set -e

template_python() {
    cat <<EOF
from pprint import pprint as p

EOF
}


template_php() {
    cat <<EOF
<?php

EOF
}


write_template() {
    WORKFILE="$1"
    COMMAND="$2"
    if [ "$COMMAND" = 'python' ]; then
        template_python > "$WORKFILE"
    elif [ "$COMMAND" = 'php' ]; then
        template_php > "$WORKFILE"
    fi
}


while true; do
    if [ "$1" = '-s' ]; then
        FILETYPE="$2"
        shift
        shift
    else
        break
    fi
done

COMMAND="$1"

if [ -z "$COMMAND" ]; then
    cat >&2 << EOF
usage nvim-repl: COMMAND [FILE]
EOF
    exit 1
fi

if [ -n "$2" ]; then
    WORKFILE="$2"
    if ! [ -e "$WORKFILE" ]; then
        write_template "$WORKFILE" "$COMMAND"
    fi

else
    WORKFILE="$(mktemp)"
    write_template "$WORKFILE" "$COMMAND"
    cleanup() {
        rm -f "$WORKFILE"
    }
    trap cleanup EXIT
fi

if [ -z "$FILETYPE" ]; then
    FILETYPE="$COMMAND"
fi

nvim "$WORKFILE" -c "set ft=$FILETYPE | REPL '$COMMAND'"
