#!/usr/bin/env sh
if [ ! -f ~/.config/nvim/autoload/plug.vim ]; then
    curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi
if ! pip list | grep '^neovim ' > /dev/null || pip list -o | grep '^neovim ' > /dev/null; then
    pip install -U neovim
fi
exit
nvim -c 'PlugUpgrade | PlugUpdate | PlugClean | silent UpdateRemotePlugins' -c 'qa'
