#!/usr/bin/env sh
set -e

MAGENTA='\033[1;35m'
RESET='\033[0m'

log() {
    echo ${MAGENTA}$@${RESET}
}

log Updating pipns environment ...
pipns install neovim > /dev/null 2>&1
pipns -n neovim update > /dev/null 2>&1
ln -sf "$(pipns -n neovim --venv)/bin/python" ~/.config/nvim/plugged/python

if [ ! -f ~/.config/nvim/autoload/plug.vim ]; then
    log Installing plugin manager environment ...
    curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi
log Updating plugins ...
nvim -c 'PlugUpgrade | PlugUpdate | PlugClean | silent UpdateRemotePlugins' -c 'qa'
