#!/usr/bin/env sh
set -e
if command -v termux-open > /dev/null; then
    nohup termux-open "$@" > /dev/null 2>&1 &
elif command -v xdg-open > /dev/null; then
    nohup xdg-open "$@" > /dev/null 2>&1 &
else
    bin="$(which -a "${0##*/}" | grep -m 1 -v "^$0$")"
    if [ -n "$bin" ]; then
        exec "$bin" "$@"
    else
        echo error: command not not found >&2
        exit 1
    fi
fi
