#!/usr/bin/env sh
set -e
if command -v xdg-open > /dev/null; then
    if [ -z "$XAUTHORITY" ]; then
        export XAUTHORITY=~/.Xauthority
        export DISPLAY=$(
            ps e -u $USERNAME | \
            sed -rn 's/.* DISPLAY=(:[0-9]*).*/\1/p' | \
            head -n 1)
    fi
    nohup xdg-open "$@" > /dev/null 2>&1 &
elif command -v termux-open > /dev/null; then
    nohup termux-open "$@" > /dev/null 2>&1 &
else
    bin="$(which -a "$(basename "$0")" | grep -v "^$0$" | head -n 1)"
    if [ -n "$bin" ]; then
        exec open "$@"
    else
        echo error: command not not found >&2
        exit 1
    fi
fi
