#!/bin/bash

file="$1"
filename=$(basename "$file")
extension="${filename##*.}"

if [ -z "$2" ]; then
    OUTPUT_FILE=/tmp/pandoc.html
else
    OUTPUT_FILE=$2
fi

if [ "${extension}" == "md" ]; then
    pandoc_format=gfm
elif [ "${extension}" == "rst" ]; then
    pandoc_format=rst
else
    echo error: unknown filetype
    exit 1
fi

pandoc \
    --from "${pandoc_format}" \
    --to html \
    -c "${DOTFILES_DIR}"/pandoc/css/github-markdown.css \
    --self-contained \
    --standalone \
    --columns=10000 "$1" > $OUTPUT_FILE
