#!/usr/bin/env sh
grep -e '^Dirty:' -e '^Writeback:' /proc/meminfo | awk '
    {split($0,a); sum += a[2]} END { split( "K M G" , v ); s=1; while( sum>1024 ){ sum/=1024; s++ } { printf "%0.1f%s\n", sum, v[s] } }
'
