#!/usr/bin/awk -f
BEGIN {
    ARGV[1] = "/proc/meminfo"
    ARGC = 2
}

/(^Dirty:|^Writeback:)/{
    split($0,a)
    sum += a[2]
} END { 
    split("K M G T", v)
    s=1
    while (sum > 1024) {
        sum /= 1024
        s++
    } 
    printf "%0.1f%s\n", sum, v[s]
}
