#!/usr/bin/env sh
set -e
default_preview() {
    # set line count to avoid unnecessary page length.
    # 1024 is overkill, but using $(tput lines) is not reliable.
    bat -r :1024 --color=always --plain -- "$1"
}

if [ $# -eq 0 ]; then
    echo 'error: missing argument' >&2
    exit 1
elif [ -d "$1" ]; then
    cd "$1" || exit 1
    fd --color=always --maxdepth=1
else
    mimetype=''
    USE_XDG_MIME=1
    case "$1" in
        # xdg-mime incorrectly identifies all files ending with this as
        # application/x-trash
        # lf appends this when copying to a target that already exists.
        *'.~1~')
            USE_XDG_MIME=
            ;;
    esac
    if command -v xdg-mime > /dev/null && [ -n "$USE_XDG_MIME" ]; then
        # allows for overrides in ~/.local/share/mime/packages to work
        # on headless system.
        export XDG_CURRENT_DESKTOP="${XDG_CURRENT_DESKTOP:=kde}"

        mimetype="$(xdg-mime query filetype "$1")"
    else
        mimetype="$(file --brief --mime-type "$1")"
    fi
    case "$mimetype" in
        application/gzip|\
        application/x-rpm|\
        application/java-archive|\
        application/vnd.comicbook-rar|\
        application/vnd.comicbook+zip|\
        application/vnd.efi.iso|\
        application/vnd.google-earth.kmz|\
        application/vnd.ms-cab-compressed|\
        application/vnd.rar|\
        application/x-7z-compressed|\
        application/x-ace|\
        application/x-bzip-compressed-tar|\
        application/x-cd-image|\
        application/x-compressed-tar|\
        application/x-dosexec|\
        application/x-iso9660-image|\
        application/x-ms-dos-executable|\
        application/x-pak|\
        application/x-rar|\
        application/x-raw-disk-image|\
        application/x-tar|\
        application/x-xz-compressed-tar|\
        application/x-zstd-compressed-tar|\
        application/zip|\
        application/zstd)
            extract -l -- "$1"
            ;;
        audio/x-mod)
            # xdg-mime reports go.mod files as this
            default_preview "$1"
            ;;
        audio/x-mpegurl)
            default_preview "$1"
            ;;
        video/x-matroska)
            mkv-preview "$1"
            ;;
        audio/*|\
        video/*)
            ffprobe -hide_banner -- "$1" 2>&1
            ;;
        application/epub+zip)
            epubmeta -- "$1"
            ;;
        application/vnd.microsoft.portable-executable)
            exiftool -- "$1" || extract -l -- "$1"
            ;;
        application/pdf|\
        image/gif|\
        image/x-canon-cr2|\
        image/x-canon-cr3)
            exiftool -- "$1"
            ;;
        application/vnd.iccprofile)
            iccdump -t desc "$1"
            ;;
        image/jxl)
            jxlinfo --verbose "$1"
            ;;
        image/tiff)
            tiffinfo -- "$1"
            ;;
        image/x-portable-pixmap)
            identify -- "$1"
            ;;
        image/*)
            #chafa -f sixel -s "$2x$3" --animate off --polite on "$1"
            exiv2 "$1" || true
            ;;
        application/octet-stream)
            case "$(printf %s "$1" | tr '[:upper:]' '[:lower:]')" in
                *.umx)
                    ffprobe -hide_banner -- "$1" 2>&1
                    ;;
                *)
                    default_preview "$1"
            esac
            ;;
        *)
            default_preview "$1"
    esac
fi
