#!/usr/bin/env sh
YELLOW='\033[1;33m'
RESET='\033[0m'

show_dashboard() {
    date
    echo

    echo "${YELLOW}Uptime${RESET}"
    uptime -p
    echo

    echo "${YELLOW}CPU (MHz)${RESET}"
    cat /proc/cpuinfo | grep MHz | awk '{print int($4)}'
    echo

    echo "${YELLOW}Memory${RESET}"
    free -m
    echo

    echo "${YELLOW}Sensors${RESET}"
    sensors
}

if ! [ -z $1 ]; then
    while true; do
        clear
        show_dashboard
        sleep $1
    done
else
    show_dashboard
fi
