#!/usr/bin/env python3
import argparse
import json
import pathlib
import re


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('pattern')
    parser.add_argument('path', type=pathlib.Path)
    args = parser.parse_args()

    pattern = re.compile(args.pattern)
    text = args.path.read_text()

    matches = [
        match.groups()
        for match in pattern.finditer(text)
    ]
    print(json.dumps(matches, indent=2, sort_keys=True))


if __name__ == '__main__':
    main()
