#!/usr/bin/env sh
set -e
MOUNT_POINT="$(mktemp -d)"

cleanup() {
    sudo umount "$MOUNT_POINT"
    rm -rf "$MOUNT_POINT"
}

trap cleanup EXIT INT
if [ -e /dev/disk/by-label/rg350_external ]; then
    sudo mount /dev/disk/by-label/rg350_external "$MOUNT_POINT"
    sudo "${MOUNT_POINT}"/sync_saves.sh
else
    sshfs rg350:/ "${MOUNT_POINT}"
    sudo "${MOUNT_POINT}"/sync_saves.sh
    ssh rg350 /media/sdcard/sync_saves.sh
fi

sync
