#!/usr/bin/env python3
import argparse
import random


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('end', type=int, default=6, nargs='?')
    parser.add_argument('start', type=int, default=1, nargs='?')
    args = parser.parse_args()

    print(random.randint(args.start, args.end))


if __name__ == '__main__':
    main()
