#!/usr/bin/env sh
set -eu
pattern="$1"
shift
for f in "$@"; do
    dir="$(dirname "$f")"
    base="$(basename "$f")"
    new="$(printf %s "$base" | sed -E "$pattern")"
    if [ "$new" != "$base" ]; then
        if [ -e "$new" ]; then
            printf 'error: target exists "%s" (original "%s")\n' "$new" "$base" >&2
        else
            mv --no-clobber "$f" "$dir/$new"
        fi
    fi
done
