#!/usr/bin/env sh
set -eu
pattern="$1"
shift
for f in "$@"; do
    dir="$(dirname "$f")"
    base="$(basename "$f")"
    new="$(printf %s "$base" | sed "$pattern")"
    if [ "$dir/$new" != "$f" ]; then
        mv --no-clobber "$f" "$dir/$new"
    fi
done
