#!/usr/bin/env python3
import argparse
import functools
import json
import sys


def __write(obj, mode, value):
    try:
        if mode != 'bytes':
            if mode == 'json':
                value = json.dumps(value)
            if isinstance(value, str):
                value = value.encode()
            elif not isinstance(value, bytes):
                value = str(value).encode()
        obj.buffer.write(value)
    except TypeError as e:
        print(f'error: unable to write output. {str(e)}', file=sys.stderr)
        sys.exit(1)
    obj.flush()


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('command')
    group = parser.add_mutually_exclusive_group()
    group.add_argument(
        '-b',
        action='store_const',
        const='bytes',
        default=False,
        dest='mode',
        help='Read/write as bytes'
    )
    group.add_argument(
        '-j',
        action='store_const',
        const='json',
        default=False,
        dest='mode',
        help='Read/write as JSON'
    )
    group.add_argument(
        '-d', dest='delimiter', default=False,
        help='Set to process input in chunks'
    )
    args = parser.parse_args()

    if sys.stdin.isatty():
        inp = None
    else:
        inp = sys.stdin.buffer.read()
        if args.mode != 'bytes':
            inp = inp.decode()
            if args.mode == 'json':
                try:
                    inp = json.loads(inp)
                except json.JSONDecodeError:
                    print(
                        'error: stdin is not valid json',
                        file=sys.stderr
                    )
                    sys.exit(1)

    # convenience variables
    out = functools.partial(__write, sys.stdout, args.mode)
    err = functools.partial(__write, sys.stderr, args.mode)

    if args.delimiter:
        delimiter = args.delimiter.encode().decode('unicode_escape')
        lines = inp.strip().split(delimiter)
        for inp in lines:
            exec(args.command)
    else:
        exec(args.command)


if __name__ == '__main__':
    main()
