#!/usr/bin/env sh
# soak all stdin and save to a file (aka shell ripoff of moretuils's sponge) 
set -e
if [ -z "$1" ]; then
    echo error: missing output file >&2
    exit 1
fi
tmpfile="$(mktemp)"
cleanup() {
    rm -f "$tmpfile"
}
trap cleanup EXIT
cat - > "$tmpfile"
mv "$tmpfile" "$1"
