#!/usr/bin/env python3
import argparse
import collections
import logging
import pathlib


def main():
    logging.basicConfig(level=logging.INFO)

    parser = argparse.ArgumentParser()
    parser.add_argument("file", type=pathlib.Path)
    parser.add_argument("-n", "--start-num", type=int, default=1)
    args = parser.parse_args()

    num = 1
    file_data = collections.defaultdict(list)
    for line in args.file.read_text().split("\n"):
        if not line:
            num += 1
        else:
            file_data[num].append(line)
    for num, lines in file_data.items():
        pathlib.Path(str(num)).write_text("\n".join(lines))


if __name__ == "__main__":
    main()
