#!/usr/bin/env sh
NTH_ARG=
WITH_NTH_ARG=
NO_FZF=
while true; do
    case "$1" in
        --no-fzf)
            NO_FZF=1
            shift
            ;;
        --no-filename)
            NTH_ARG='--nth=2..'
            WITH_NTH_ARG='--with-nth=2..'
            shift
            ;;
        *)
            break
    esac
done

get_contents() {
    rg -0 --hidden -g '!\.git/' '.+' | sed 's/\x0/\x0 /' | LC_ALL=C sort -u
}

show_fzf() {
    fzf $NTH_ARG $WITH_NTH_ARG --literal --bind ctrl-l:clear-query | tr '\0' '\n' | head -n 1
}

if [ -t 0 ]; then
    if [ -n "$NO_FZF" ]; then
        get_contents
    else
        get_contents | show_fzf
    fi
else
    show_fzf
fi
