#!/usr/bin/env bash
IMAGE=nginx:alpine
PORT=8000

if [ $1 = '--pull' ]; then
    docker pull "${IMAGE}"
    exit
fi

if ! [ -t 0 ]; then
    TEMP_DIR=$(mktemp -d /tmp/srvit.XXXXXXXXX)
    HTML_DIR=$TEMP_DIR
    trap "rm -rf "$TEMP_DIR"" EXIT
    cat > "$TEMP_DIR/index.html"
elif [ -n "$1" ]; then
    HTML_DIR="$(realpath "$1")"
else
    HTML_DIR=$(pwd)
fi

NGINX_CONFIG=$(mktemp -p /tmp)
cat > "${NGINX_CONFIG}" <<EOF
server {
    listen 80;
    server_name localhost;

    sendfile off;
    add_header Cache-Control no-cache;

    location / {
        root /content;
        index index.html;
    }
}
EOF

echo http://localhost:$PORT

container_name="docker_shell-$(uuidgen | tr -d -)"
trap "rm -rf $TEMP_DIR; docker kill "${container_name}" >& /dev/null || true" SIGHUP EXIT

docker run \
    --rm \
    --name ${container_name} \
    -p ${PORT}:80 \
    -v "${NGINX_CONFIG}":/etc/nginx/conf.d/default.conf \
    -v "${HTML_DIR}":/content \
    "${IMAGE}"
