#!/usr/bin/env sh
IMAGE=nginx:alpine
PORT=8000

if [ "$1" = '--pull' ]; then
    docker pull "${IMAGE}"
    exit
fi

if [ -n "$1" ]; then
    HTML_DIR="$(realpath "$1")"
else
    HTML_DIR=$(pwd)
fi

NGINX_CONFIG=$(mktemp -p /tmp)
cat > "${NGINX_CONFIG}" <<EOF
server {
    listen 80;
    server_name localhost;

    sendfile off;
    add_header Cache-Control no-cache;

    location / {
        root /content;
        index index.html;
    }
}
EOF

echo http://localhost:$PORT

container_name="srvit-$PORT"

cleanup() {
    set +e
    rm -rf "${NGINX_CONFIG}"
    docker kill "${container_name}" > /dev/null 2>&1
}

trap cleanup HUP EXIT

# Run as root to avoid permission issues accessing files
docker run \
    --rm \
    --name ${container_name} \
    -p ${PORT}:80 \
    -v "${NGINX_CONFIG}":/etc/nginx/conf.d/default.conf \
    -v "${HTML_DIR}":/content:ro \
    "${IMAGE}" sh -c "sed -i 's/user.\snginx/user root/g' /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
