#!/usr/bin/env sh
set -e

show_help() {
    cat << EOF
usage: syncdir [--help] SOURCE TARGET
    --help      Display this help and exit
EOF
}

while [ $# -gt 0 ]; do
    case "$1" in
        --)
            shift
            break
            ;;
        --help)
            show_help
            exit
            ;;
        *)
            break
    esac
done

if [ $# -eq 2 ]; then
    SOURCE="$1"
    TARGET="$2"
else
    show_help >&2
    exit 1
fi

echo "Syncing \"$SOURCE\" to \"$TARGET\""

exec rsync -av --progress --delete "$SOURCE/" "$TARGET/"
