#!/usr/bin/env sh
set -e

NOTES_DIR="${NOTES_DIR:-$HOME/Notes}"
TODO_FILE="${NOTES_DIR}/todo.txt"

if [ "$(ls "${NOTES_DIR}" | grep '^todo.*.txt' | wc -l)" -gt 1 ] ; then
    echo error: sync conflict detected >&2
    exit 1
fi

show_help() {
    echo 'usage: todo TASK'
}

while true; do
    case "$1" in
        --help)
            show_help
            exit
            ;;
        *)
            if [ -n "$1" ]; then
                echo "$(date -I)" "$@" >> "${TODO_FILE}"
            else
                exec "${EDITOR}" "${TODO_FILE}"
            fi
            break
    esac
done
