#!/usr/bin/env python
import argparse
import subprocess

SHIPPERS = {
    'aquiline': 'https://aquiline-tracking.com/data/TrackPackage{}',
    'fedex': 'https://www.fedex.com/fedextrack/?tracknumbers={}',
    'ups': 'https://www.ups.com/track?trackNums={}',
    'usps': 'https://tools.usps.com/go/TrackConfirmAction?qtc_tLabels1={}',
}


class Clipboard:
    @staticmethod
    def copy(data):
        subprocess.run(
            ['cbcopy'],
            input=data,
            check=True)

    @staticmethod
    def paste():
        proc = subprocess.run(
            ['cbpaste'],
            stdout=subprocess.PIPE,
            check=True)
        return proc.stdout


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('shipper', choices=SHIPPERS.keys())
    parser.add_argument('id', nargs='?')
    args = parser.parse_args()

    tracking_id = (args.id or Clipboard.paste().decode()).strip()
    if tracking_id.lower().startswith(('http://', 'https://')):
        raise ValueError('invalid tracking id')

    url = SHIPPERS[args.shipper].format(tracking_id)
    Clipboard.copy(url.encode())
    print(url)


if __name__ == '__main__':
    main()
