#!/usr/bin/env python
import argparse
import subprocess
import string

CARRIERS = {
    "fedex": "https://www.fedex.com/fedextrack/?tracknumbers=",
    "ups": "https://www.ups.com/track?trackNums=",
    "usps": "https://tools.usps.com/go/TrackConfirmAction?qtc_tLabels1=",
}


class Clipboard:
    @staticmethod
    def copy(data):
        subprocess.run(["cbcopy"], input=data, stdout=subprocess.DEVNULL, check=True)

    @staticmethod
    def paste():
        proc = subprocess.run(["cbpaste"], stdout=subprocess.PIPE, check=True)
        return proc.stdout


def determine_carrier(tracking_id):
    is_numeric = not set(tracking_id) - set(string.digits)

    if is_numeric:
        if 20 <= len(tracking_id) <= 35:
            return "usps"
        elif 12 <= len(tracking_id) <= 14:
            return "fedex"
    else:
        if len(tracking_id) == 18 and tracking_id.startswith("1Z"):
            return "ups"
    raise ValueError("cannot determine carrier")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("-c", "--carrier", choices=CARRIERS.keys())
    parser.add_argument("id", nargs="?")
    args = parser.parse_args()

    tracking_id = (args.id or Clipboard.paste().decode()).strip()
    for url in CARRIERS.values():
        tracking_id = tracking_id.removeprefix(url)

    carrier = args.carrier or determine_carrier(tracking_id)

    url = CARRIERS[carrier] + tracking_id
    print(url)
    Clipboard.copy(url.encode())


if __name__ == "__main__":
    main()
