#!/usr/bin/env sh
_upper() {
    tr '[:lower:]' '[:upper:]'
}

if [ $# -gt 0 ]; then
    if [ $# -eq 1 ]; then
        printf '%s' "$1" | _upper
    else
        echo 'error: unexpected arguments' >&2
        exit 1
    fi
else
    _upper
fi
