#!/usr/bin/env python
import sys
import subprocess


def upper_first_letter(text):
    words = []
    for word in text.split():
        word = word.lower()
        letters = [word[0].upper(), *word[1:]]
        words.append("".join(letters))
    return " ".join(words)


class Clipboard:
    @staticmethod
    def get():
        proc = subprocess.run(["cbpaste"], stdout=subprocess.PIPE, check=True)
        return proc.stdout

    @staticmethod
    def set(data):
        subprocess.run(["cbcopy"], input=data.encode(), check=True)


if not sys.stdin.isatty():
    if len(sys.argv) > 1:
        raise RuntimeError("unexpected arguments")
    data = sys.stdin.read()
elif len(sys.argv) == 1:
    data = Clipboard.get().decode()
elif len(sys.argv) >= 2:
    data = " ".join(sys.argv[1:])
else:
    raise NotImplementedError

result = upper_first_letter(data)
data = Clipboard.set(result)
sys.stdout.write(result)
