#!/usr/bin/env python
import sys
import urllib.parse

if sys.stdin.isatty():
    assert len(sys.argv) == 2
    data = sys.argv[1]
else:
    data = sys.stdin.read()
sys.stdout.write(urllib.parse.unquote(data))
