#!/usr/bin/env python
import argparse
import re
import sys

# https://urlregex.com/
pattern = re.compile(r'http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\(\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+')  # noqa: E501

parser = argparse.ArgumentParser()
parser.add_argument(
    'data',
    nargs='?',
    default=sys.stdin,
    type=argparse.FileType('r')
)
args = parser.parse_args()

for url in set(pattern.findall(args.data.read())):
    print(url)
