#!/usr/bin/env python
import re
import sys
pattern = re.compile('http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\(\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+')
urls = set(pattern.findall(sys.stdin.read()))
for url in urls:
    print(url)
