#!/usr/bin/env sh
# Portable random UUID generation
set -e

randhex() {
    cat /dev/urandom | LC_ALL=C tr -cd 'a-f0-9' | head -c $1
}

uuid="$(randhex 8)-$(randhex 4)-$(randhex 4)-$(randhex 4)-$(randhex 12)"

if [ -t 1 ]; then
    echo $uuid
else
    printf $uuid
fi
