#!/usr/bin/env sh
# Portable random UUID generation
set -e

randhex() {
    LC_ALL=C tr -cd 'a-f0-9' < /dev/urandom | head -c "$1"
}

uuid="$(randhex 8)-$(randhex 4)-$(randhex 4)-$(randhex 4)-$(randhex 12)"

if [ -t 1 ]; then
    echo "$uuid"
else
    printf '%s' "$uuid"
fi
