#!/bin/sh
set -e

trap "exit 0" SIGINT

if [ -z $1 ]; then
    echo ERROR: No command provided
    exit 1
fi

while true; do
    clear
    eval "$@ &"
    child=$!
    trap "kill -- $child -$child &> /dev/null || true" EXIT
    wait
    sleep 0.5
    fswatch -r -l 0.1 --one-event ./ \
    --event=Created \
    --event=Updated \
    --event=Removed \
    --event=Renamed \
    --event=OwnerModified \
    --event=AttributeModified \
    --event=MovedFrom \
    --event=MovedTo \
    --event=Link \
    &> /dev/null
done
