#!/bin/sh
set -e

if [ -z $1 ]; then
    echo ERROR: No command provided
    exit 1
fi

while true; do
    clear
    eval "$@ &"
    trap "pkill -P $!; exit" 2
    wait
    fswatch -r -l 0.1 --one-event ./ \
    --event=Created \
    --event=Updated \
    --event=Removed \
    --event=Renamed \
    --event=OwnerModified \
    --event=AttributeModified \
    --event=MovedFrom \
    --event=MovedTo \
    --event=Link \
    > /dev/null
done
