#!/usr/bin/env python3
import argparse
import sys

import pyaml
import yaml


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('file', nargs='?', type=argparse.FileType('r'))
    args = parser.parse_args()

    if args.file:
        content = args.file.read()
    else:
        content = sys.stdin.read()
    data = yaml.safe_load(content)
    formatted = pyaml.dump(data, vspacing=[1, 0])
    sys.stdout.write(formatted)


if __name__ == '__main__':
    main()
