#!/usr/bin/env python3
import argparse
import pathlib

import yaml


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('file', type=pathlib.Path)
    parser.add_argument('-r', dest='replace', action='store_true')
    args = parser.parse_args()

    data = yaml.load(args.file.read_text())
    formatted = yaml.dump(
        data, default_flow_style=False, default_style=False, indent=4
    )
    if args.replace:
        args.file.write_text(formatted)
    else:
        print(formatted)


if __name__ == '__main__':
    main()
