#!/usr/bin/env python3
import argparse
import signal
import sys

import pyaml
import yaml


def _sigint_handler(*_):
    print()
    sys.exit(130)


def main():
    signal.signal(signal.SIGINT, _sigint_handler)

    parser = argparse.ArgumentParser()
    parser.add_argument('file', nargs='?', type=argparse.FileType('r'))
    args = parser.parse_args()

    data = yaml.safe_load(
        args.file.read() if args.file else sys.stdin.read()
    )
    sys.stdout.write(
        pyaml.dump(data, vspacing=[1, 0])
    )


if __name__ == '__main__':
    main()
