#!/usr/bin/env python3
import argparse
import sys
import zlib

parser = argparse.ArgumentParser()
parser.add_argument('-d', '--decompress', action='store_true')
parser.add_argument(
    'file', nargs='?', type=argparse.FileType('rb'), default=sys.stdin.buffer
)
args = parser.parse_args()

data = args.file.read()
sys.stdout.buffer.write(
    zlib.decompress(data) if args.decompress else zlib.compress(data)
)
