#!/usr/bin/env sh
set -e

zstd_compress() {
    # -T0 uses number of cores, not threads
    if [ -n "$FAST" ]; then
        LEVEL=3
    else
        LEVEL=22
    fi
    zstd -f "-T$(nproc)" --ultra "-${LEVEL}" "$@"
}

RM=1
FAST=
while [ $# -gt 0 ]; do
    case "$1" in
        --keep)
            RM=
            shift
            ;;
        --fast)
            FAST=1
            shift
            ;;
        *)
            break
    esac
done

if [ $# -eq 0 ]; then
    echo 'usage: zstd-tar [--kee] PATH [PATH..]' >&2
    exit 1
fi

process() {
    SOURCE="$(realpath "$1")"
    DEST="$(basename "$SOURCE").tar.zst"

    echo "Processing $SOURCE"

    if [ -f "$SOURCE" ]; then
        tar cf - -C "$(dirname "$SOURCE")" "$(basename "$SOURCE")" | zstd_compress -o "$DEST"
    elif [ -d "$SOURCE" ]; then
        find "$SOURCE" -printf '%P\0' | tar cf - -C "$SOURCE" --no-recursion --verbatim-files-from --null -T - | zstd_compress -o "$DEST"
    else
        exit 1
    fi
    if [ -n "$RM" ]; then
        rm -rf "$SOURCE"
    fi
}

for path in "$@"; do
    process "$path"
done
