#!/usr/bin/env python3
import argparse
import base64
import json
import subprocess
import sys


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--exchange", required=True)
    parser.add_argument("--routing", required=True)
    parser.add_argument("--header", nargs=2, action="append")
    parser.add_argument(
        "body", default=sys.stdin, type=argparse.FileType("r"), nargs="?"
    )
    args = parser.parse_args()

    body = base64.b64encode(json.dumps(json.load(args.body)).encode()).decode()

    data = {
        "ContentType": "application/json",
        "Exchange": args.exchange,
        "RoutingKey": args.routing,
        "ContentEncoding": "",
        "DeliveryMode": 0,
        "Priority": 0,
        "CorrelationID": "",
        "ReplyTo": "",
        "Expiration": "",
        "MessageID": "",
        "Type": "",
        "UserID": "",
        "AppID": "",
        "Headers": {key: value for key, value in args.header},
        "Body": body,
    }

    subprocess.run(
        ["rabtap", "pub", "--format=json"], input=json.dumps(data).encode(), check=True
    )


if __name__ == "__main__":
    main()
