#!/usr/bin/env sh
set -e
PREFIX="$HOME/.local"
REPO_DIR="$(git install https://git.kernel.org/pub/scm/utils/dash/dash.git)"
cd "$REPO_DIR"
git checkout -q "$(git describe --abbrev=0 --tags)"

current_version=$(git rev-parse HEAD)
key="git-install/dash"
if [ "$(kv $key)" != "$current_version" ]; then
    ./autogen.sh
    ./configure --prefix="$PREFIX"
    make -j8
    make install
    ln -sf "$PREFIX/bin/dash" "$PREFIX/bin/sh"
    kv $key $current_version
fi
