#!/usr/bin/env sh
set -e
PREFIX="$HOME/.local"
cd "$(git install -k https://github.com/neovim/neovim)"
git checkout nightly

current_version=$(git rev-parse HEAD)
key="git-install/nvim-nightly"
if [ "$(kv $key)" != "$current_version" ]; then
    if [ -d current ]; then
        mv current old
    fi
    mkdir current
    cd current
    curl -L https://github.com/neovim/neovim/releases/download/nightly/nvim-macos.tar.gz | tar xvf -
    ln -sf "$(pwd)/nvim-osx64/bin/nvim" ~/.local/bin/nvim
    rm -rf ../old
    kv $key $current_version
fi
