#!/usr/bin/env sh
cd "$(git install https://github.com/pushrax/osxmpdkeys.git)"
current_version=$(git rev-parse HEAD)
key="git-install/osxmpdkeys"
if [ "$(kv $key)" != "$current_version" ]; then
    pip install .
    kv $key $current_version
fi
