#!/usr/bin/env sh
log() {
    printf '%s %s\n' "$(date)" "$1"
}

while true; do
    log 'Starting MPD'
    /usr/local/bin/mpd --no-daemon ~/.config/mpd/mpd.conf.macos
    ret=$?
    log "MPD Exit Code $ret"
    sleep 1
done
