#!/usr/bin/env sh
set -x
defaults write com.apple.coreservices.uiagent CSUIHasSafariBeenLaunched -bool YES
defaults write com.apple.coreservices.uiagent CSUIRecommendSafariNextNotificationDate -date 2050-01-01T00:00:00Z
defaults write com.apple.coreservices.uiagent CSUILastOSVersionWhereSafariRecommendationWasMade -float 10.13
defaults write com.apple.Dock autohide-delay -float 0 && killall Dock
sudo launchctl limit maxfiles 1000000 unlimited
