#!/usr/bin/env python
import os
import sys

import i3ipc


def find_firefox_windows(is_private):
    if is_private:
        pattern = r'.*Mozilla Firefox \(Private Browsing\)$'
    else:
        pattern = '.*Mozilla Firefox$'

    return [
        item
        for item in conn.get_tree().find_named(pattern)
        if item.window_role == 'browser'
    ]


conn = i3ipc.Connection()

is_private = '--private-window' in sys.argv
if (len(sys.argv) == 2 and is_private) or len(sys.argv) == 1:
    if windows := find_firefox_windows(is_private):
        windows[0].command('focus')
        sys.exit()

os.execvp('/usr/bin/firefox', sys.argv)
