#!/usr/bin/env python
import os
import sys

import i3ipc


def find_firefox_windows(is_private):
    if is_private:
        pattern = r'.*Mozilla Firefox \(Private Browsing\)$'
    else:
        pattern = '.*Mozilla Firefox$'

    return [
        item
        for item in conn.get_tree().find_named(pattern)
        if item.window_instance == 'Navigator'
    ]


conn = i3ipc.Connection()

is_private = '--private-window' in sys.argv
has_url = any(
    not arg.startswith('-')
    for arg in sys.argv[1:]
)

if windows := find_firefox_windows(is_private):
    window = windows[0]
    window.command('focus')
    print(windows)
    if has_url:
        print(has_url)
        os.execvp('/usr/bin/firefox', sys.argv)
else:
    os.execvp('/usr/bin/firefox', sys.argv)
