#!/usr/bin/env python
import subprocess
import sys

import i3ipc

FIREFOX_PATH = '/usr/bin/firefox'


def find_firefox_windows(is_private):
    if is_private:
        pattern = r'.*Mozilla Firefox \(Private Browsing\)$'
    else:
        pattern = '.*Mozilla Firefox$'

    return [
        item
        for item in conn.get_tree().find_named(pattern)
        if item.window_instance == 'Navigator'
    ]


conn = i3ipc.Connection()

is_private = '--private-window' in sys.argv
has_url = any(
    not arg.startswith('-')
    for arg in sys.argv[1:]
)

args = [FIREFOX_PATH, *sys.argv[1:]]

if windows := find_firefox_windows(is_private):
    window = windows[0]
    window.command('focus')
    if has_url:
        subprocess.run(args)
else:
    subprocess.run(args)
