#!/usr/bin/env sh
if ! command -v k9s > /dev/null; then
    exit
fi

eval "$(base16-export)}"
mkdir -p ~/.config/k9s
cat > ~/.config/k9s/skin.yml << EOF
k9s:
  body:
    fgColor: "#${BASE16_COLOR7}"
    bgColor: default
    logoColor: "#${BASE16_COLOR6}"
  info:
    fgColor: "#${BASE16_COLOR12}"
    sectionColor: "#${BASE16_COLOR7}"
  frame:
    border:
      fgColor: "#${BASE16_COLOR120}"
      focusColor: "#${BASE16_COLOR19}"
    menu:
      fgColor: "#${BASE16_COLOR7}"
      keyColor: "#${BASE16_COLOR12}"
      numKeyColor: "#${BASE16_COLOR12}"
    crumbs:
      fgColor: "#${BASE16_COLOR6}"
      bgColor: default
      activeColor: default
    status:
      newColor: "#${BASE16_COLOR7}"
      modifyColor: "#${BASE16_COLOR3}"
      addColor: "#${BASE16_COLOR12}"
      errorColor: "#${BASE16_COLOR1}"
      highlightcolor: "#${BASE16_COLOR6}"
      killColor: "#${BASE16_COLOR1}"
      completedColor: "#${BASE16_COLOR12}"
    title:
      fgColor: "#${BASE16_COLOR7}"
      bgColor: default
      highlightColor: "#${BASE16_COLOR5}"
      counterColor: "#${BASE16_COLOR5}"
      filterColor: "#${BASE16_COLOR5}"
  views:
    table:
      fgColor: "#${BASE16_COLOR4}"
      bgColor: default
      cursorColor: "#${BASE16_COLOR6}"
      header:
        fgColor: "#${BASE16_COLOR4}"
        bgColor: default
        sorterColor: "#${BASE16_COLOR5}"
    yaml:
      keyColor: "#${BASE16_COLOR1}"
      colonColor: "#${BASE16_COLOR6}"
      valueColor: "#${BASE16_COLOR7}"
    logs:
      fgColor: "#${BASE16_COLOR7}"
      bgColor: default
EOF
