#!/usr/bin/env sh
# Backup a multi-session CD on a drive that doesn't properly support
# multi-session. Ex WH16NS40.
#
# Prefer using a drive which properly supports multi-session ex.
# PX-716A or PX-760A
set -e

DEVICE="$1"
DESTINATION="$2"

if ! [ -e "$DEVICE" ]; then
    cat >&2 << EOF
usage: INFILE OUTDIR
EOF
    exit 1
fi

LABEL="$(blkid -o value -s LABEL "$DEVICE")"

OUTFILE="${DESTINATION}/${LABEL}.bin"
TOCFILE="${DESTINATION}/${LABEL}.toc"

if [ -e "$OUTFILE" ] || [ -e "$TOCFILE" ]; then
    echo 'error: OUTFILE and/or TOCFILE already exists' >&2
    exit 1
fi
mkdir -p "$DESTINATION"

cdrdao read-cd --read-raw --datafile "$OUTFILE" "$TOCFILE"
