#!/usr/bin/env sh
set -e

DEVICE="$1"
DESTINATION="$2"
LABEL="$3"

if ! [ -e "$DEVICE" ]; then
    cat >&2 << EOF
usage: INFILE OUTDIR
EOF
    exit 1
fi

if [ -z "$LABEL" ]; then
    LABEL="$(blkid -o value -s LABEL "$DEVICE")"
fi

OUTFILE="${DESTINATION}/${LABEL}.iso"
LOGFILE="${DESTINATION}/${LABEL}.log"

if [ -e "$OUTFILE" ] || [ -e "$LOGFILE" ]; then
    echo 'error: OUTFILE and/or LOGFILE already exists' >&2
    exit 1
fi

echo 'Reading without retry ...'
ddrescue --sector-size=2048 --verbose --no-scrape "$DEVICE" "${OUTFILE}" "${LOGFILE}"

echo 'Reading with retry ...'
ddrescue --sector-size=2048 --verbose --idirect --retry-passes=5 "$DEVICE" "${OUTFILE}" "${LOGFILE}"

echo 'Reading with retry and reversed ...'
ddrescue --sector-size=2048 --verbose --idirect --retry-passes=5 --reverse "$DEVICE" "${OUTFILE}" "${LOGFILE}"
