#!/usr/bin/env sh
set -e

DEVICE="$1"
DESTINATION="$2"

if ! [ -e "$DEVICE" ]; then
    cat >&2 << EOF
usage: INFILE OUTDIR
EOF
    exit 1
fi

LABEL="$(blkid -o value -s LABEL "$DEVICE")"
if [ -z "$DESTINATION" ]; then
    DESTINATION="$LABEL"
fi

OUTFILE="${DESTINATION}/${LABEL}.iso"
LOGFILE="${DESTINATION}/${LABEL}.log"

if [ -e "$OUTFILE" ] || [ -e "$LOGFILE" ]; then
    echo 'error: OUTFILE and/or LOGFILE already exists' >&2
    exit 1
fi
mkdir -p "$DESTINATION"

# "authenticates" the drive. something to do with encryption, not sure.
# doesn't work without doing this
echo 'Running lsdvd ...'
lsdvd -x "$DEVICE"

echo 'Reading without retry ...'
ddrescue --sector-size=2048 --verbose --no-scrape "$DEVICE" "${OUTFILE}" "${LOGFILE}"

echo 'Reading with retry ...'
ddrescue --sector-size=2048 --verbose --idirect --retry-passes=5 "$DEVICE" "${OUTFILE}" "${LOGFILE}"

echo 'Reading with retry and reversed ...'
ddrescue --sector-size=2048 --verbose --idirect --retry-passes=5 --reverse "$DEVICE" "${OUTFILE}" "${LOGFILE}"
