#!/usr/bin/env python3
import argparse
import contextlib
import datetime
import json
import pathlib
import shutil
import subprocess
import tempfile


def ffmpeg_merge(path, target, framerate='30/1', loops=1):
    subprocess.run(
        ['ffmpeg',
        '-y', '-stream_loop', str(loops),
        '-framerate', framerate,
        '-pattern_type', 'glob', '-i', f'{path}/*.png',
        '-c:v', 'libx264', '-preset', 'slow', '-crf', '16', 
        target],
        stderr=subprocess.DEVNULL,
        stdout=subprocess.DEVNULL,
        check=True)


def ffmpeg_frames_to_png(path, target, remove_duplicates=True):
    args = [
        'ffmpeg',
        '-i', path,
    ]
    if remove_duplicates:
        info = ffprobe(path)
        avg_frame_rate = None
        for stream in info:
            avg_frame_rate = stream.get('avg_frame_rate')
            if avg_frame_rate:
                x, y = avg_frame_rate.split('/')
                avg_frame_rate = int(x) / int(y)
        args.extend([
            '-vsync', '0',
            '-vf', f'mpdecimate,setpts=N/{round(avg_frame_rate, 3)}/TB',
        ])

    args.extend([
        '-compression_level', '0',
        f'{target}/%08d.png',
    ])
    subprocess.run(
        args,
        stderr=subprocess.DEVNULL,
        stdout=subprocess.DEVNULL,
        check=True)


def ffprobe(path):
    proc = subprocess.run(
        ['ffprobe',
         '-v', 'error',
         '-show_streams',
         '-print_format', 'json',
         '--', path],
        stderr=subprocess.DEVNULL,
        stdout=subprocess.PIPE,
        check=True)
    return json.loads(proc.stdout)['streams']


def rife(source, target):
    subprocess.run(
        ['rife', source, target], 
        stderr=subprocess.DEVNULL,
        stdout=subprocess.DEVNULL,
        check=True)


def main():
    now = datetime.datetime.now().strftime('%Y%m%d_%H%M%S')
    parser = argparse.ArgumentParser()
    parser.add_argument('-o', '--output', type=pathlib.Path, 
                        default=pathlib.Path(f'{now}.mp4'))
    parser.add_argument(
        '-l', '--loops', type=int, metavar='NUM', default=3, help='(default %(default)s)')
    parser.add_argument(
        '-r', '--rife-iterations', type=int, metavar='NUM', default=3, help='(default %(default)s)')
    parser.add_argument('-f', '--framerate', default='30/1', metavar='FPS', help='(default %(default)s)')
    parser.add_argument('--no-bounce', action='store_true')
    parser.add_argument('source', type=pathlib.Path)
    args = parser.parse_args()

    with contextlib.ExitStack() as exitstack:
        if args.source.is_file():
            source = pathlib.Path(
                exitstack.enter_context(tempfile.TemporaryDirectory()))
            ffmpeg_frames_to_png(args.source, source)
        elif args.source.is_dir():
            source = args.source
        else:
            raise FileNotFoundError

        tmpdir = exitstack.enter_context(
                tempfile.TemporaryDirectory(dir=source.parent))
        tmpdir = pathlib.Path(tmpdir)
        sources = sorted(list(source.iterdir()))

        new = [*sources]
        if not args.no_bounce:
            new.extend([*list(reversed(sources[:-1]))])

        for i, p in enumerate(new):
            shutil.copy(p, tmpdir / f'{i:032d}.png')

        iterations = args.rife_iterations
        for i in range(args.rife_iterations):
            print('Rife iteration', i+1, 'of', iterations)
            tmpdir2 = exitstack.enter_context(
                tempfile.TemporaryDirectory(dir=source.parent))
            tmpdir2 = pathlib.Path(tmpdir2)
            rife(tmpdir, tmpdir2)
            shutil.rmtree(tmpdir)
            shutil.move(tmpdir2, tmpdir)

        if not args.no_bounce:
            sources = sorted(list(tmpdir.iterdir()))
            for i, path in enumerate(sources[-pow(2, args.rife_iterations-1):]):
                path.unlink()

        print('Rendering video')
        ffmpeg_merge(
            tmpdir, 
            args.output,
            framerate=args.framerate,
            loops=args.loops,
        )
        print(args.output)


if __name__ == '__main__':
    main()
