#!/usr/bin/env python3
import shlex
import subprocess
import sys

args = ' '.join(shlex.quote(v) for v in ['printlabel', *sys.argv[1:]])
args = shlex.quote(args)
proc = subprocess.run(['ssh', 'ptouch-print', 'sh', '-c', args])
sys.exit(proc.returncode)
