#!/usr/bin/env sh
set -ex

CURRENT_THEME=~/.setdesktoptheme

show_help() {
    cat << EOF
usage: set-desktop-themes [--help] [--dpi DPI] [--large]

    --dpi DPI       scale theme to this DPI
    --help          show help and exit
    --medium-large  use medium-large fonts
    --large         use large fonts
EOF
}

LARGE=
MEDIUM_LARGE=
DPI=96
HASARGS=

while [ $# -gt 0 ]; do
    HASARGS=1
    case "$1" in
        --dpi)
            DPI="$2"
            shift
            shift
            ;;
        --large)
            LARGE=1
            shift
            ;;
        --medium-large)
            MEDIUM_LARGE=1
            shift
            ;;
        --help)
            show_help
            exit
            ;;
        *)
            echo error: unrecognized arguments >&2
            exit 1
    esac
done

if [ -z "$HASARGS" ] && [ -e "$CURRENT_THEME" ]; then
    . "$CURRENT_THEME"
else
    FONT_NAME='monospace'

    if [ "$DPI" -le 138 ]; then
        CURSOR_SIZE=16
        SCALING_FACTOR=1

        if [ -n "$LARGE" ]; then
            FONT_SIZE=14
        elif [ -n "$MEDIUM_LARGE" ]; then
            FONT_SIZE=12
        else
            FONT_SIZE=9
        fi
    else
        CURSOR_SIZE=48
        SCALING_FACTOR=2

        if [ -n "$LARGE" ]; then
            FONT_SIZE=14
        elif [ -n "$MEDIUM_LARGE" ]; then
            FONT_SIZE=12
        else
            FONT_SIZE=10
        fi
    fi

    # save settings
    cat > "$CURRENT_THEME" << EOF
CURSOR_SIZE="$CURSOR_SIZE"
DPI="$DPI"
FONT_NAME="$FONT_NAME"
FONT_SIZE="$FONT_SIZE"
SCALING_FACTOR="$SCALING_FACTOR"
EOF
fi

gsettings set org.gnome.desktop.interface color-scheme prefer-dark

# changing org.gnome.desktop.interface cursor-size after xrdb steps
# fucks up i3's scaling...
gsettings set org.gnome.desktop.interface cursor-size "$CURSOR_SIZE"
gsettings set org.gnome.desktop.interface scaling-factor "$SCALING_FACTOR"

# Xft/DPI: needed for Qt5 applications
gsettings set org.gnome.settings-daemon.plugins.xsettings overrides \
    "{'Gdk/WindowScalingFactor': <$SCALING_FACTOR>, 'Gtk/CursorThemeSize': <$CURSOR_SIZE>, 'Xft/DPI': <$((${DPI}*1024))>}"

# set default base16 theme
if ! [ -f ~/.base16_theme ]; then
    ln -s ~/.local/share/base16-shell/scripts/base16-classic-dark.sh ~/.base16_theme
fi

eval "$(base16-export)"

if command -v xrdb > /dev/null; then
# update xresources
xrdb << EOF
*facename: ${FONT_NAME}
*fontsize: ${FONT_SIZE}
*font: xft:${FONT_NAME}:size=${FONT_SIZE}:antialias=true:dpi=${DPI}
*boldFont:

Xft.dpi: ${DPI}

Xcursor.size: ${CURSOR_SIZE}
*color0: #${BASE16_COLOR0}
*color1: #${BASE16_COLOR1}
*color2: #${BASE16_COLOR2}
*color3: #${BASE16_COLOR3}
*color4: #${BASE16_COLOR4}
*color5: #${BASE16_COLOR5}
*color6: #${BASE16_COLOR6}
*color7: #${BASE16_COLOR7}
*color8: #${BASE16_COLOR8}
*color9: #${BASE16_COLOR9}
*color10: #${BASE16_COLOR10}
*color11: #${BASE16_COLOR11}
*color12: #${BASE16_COLOR12}
*color13: #${BASE16_COLOR13}
*color14: #${BASE16_COLOR14}
*color15: #${BASE16_COLOR15}
*color16: #${BASE16_COLOR16}
*color17: #${BASE16_COLOR17}
*color18: #${BASE16_COLOR18}
*color19: #${BASE16_COLOR19}
*color20: #${BASE16_COLOR20}
*color21: #${BASE16_COLOR21}
*foreground: #${BASE16_FOREGROUND}
*background: #${BASE16_BACKGROUND}
EOF
fi

alacritty-config-reload
mkdir -p ~/.config/alacritty
cat > ~/.config/alacritty/alacritty.toml << EOF
[colors.primary]
background = "0x${BASE16_BACKGROUND}"

[env]
TERM = "screen-256color"

[font]
size = ${FONT_SIZE}

[font.normal]
family = "${FONT_NAME}"

[mouse]
hide_when_typing = true
EOF
