#!/usr/bin/env sh
IFS=:
name="${0##*/}"
for p in $PATH; do
    bin="$p/$name"
    if [ -f "$bin" ] && [ -x "$bin" ] && [ "$bin" != "$0" ]; then
        if ! "$bin" "$@"; then
            pkill -9 mpd
            "$bin" "$@"
            sudo renice -19 $(pgrep '^mpd$')
            sudo renice -19 $(pgrep '^mpdcontrold$')
        fi
        exit
    fi
done
echo "error: command not found" >&2
