#!/usr/bin/env sh
set-desktop-themes --dpi 96

pactl-all-off
pactl set-card-profile alsa_card.usb-Schiit_Audio_USB_Modi_Device-00 pro-audio
pactl set-card-profile alsa_card.usb-audio-technica_AT2020USB_-00 input:analog-stereo
pactl set-default-sink alsa_output.usb-Schiit_Audio_USB_Modi_Device-00.pro-output-0
pactl set-default-source alsa_input.usb-audio-technica_AT2020USB_-00.pro-input-0
