#!/usr/bin/env python3
import argparse
import sys

import pika


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--content-type', default=None)
    parser.add_argument('--exchange', required=True)
    parser.add_argument('--routing-key', required=True)
    parser.add_argument('--type', default=None)
    parser.add_argument('--url', required=True, help='AMQP URL')
    args = parser.parse_args()

    content = sys.stdin.buffer.read()

    with pika.BlockingConnection(pika.URLParameters(args.url)) as connection:
        channel = connection.channel()
        channel.basic_publish(
            exchange=args.exchange,
            routing_key=args.routing_key,
            body=content,
            properties=pika.BasicProperties(
                content_type=args.content_type,
                type=args.type
            )
        )


if __name__ == '__main__':
    main()
