awful.rules = require("awful.rules")
local beautiful = require("beautiful")
local tags = require("config/tags")
local key_bindings = require("config/key_bindings")

awful.rules.rules = {
    -- All clients will match this rule.
    { rule = { },
      properties = { border_width = beautiful.border_width,
                     border_color = beautiful.border_normal,
                     focus = awful.client.focus.filter,
                     keys = clientkeys,
					 buttons = clientbuttons } },

	{ rule = { class = "chromium" },
		properties = { tag = tags[1][2] } },

    { rule = { class = "Calibre-ebook-viewer" },
		properties = { tag = tags[1][5] } },
    { rule = { class = "Calibre-gui" },
		properties = { tag = tags[1][5] } },
    { rule = { class = "qpdfview" },
		properties = { tag = tags[1][5] } },
    { rule = { class = "Mirage" },
		properties = { tag = tags[1][5] } },
 
    { rule = { class = "Gimp" },
		properties = { tag = tags[1][6] } },
    { rule = { class = "libreoffice-writer" },
		properties = { tag = tags[1][6] } },
    { rule = { name = "LibreOffice" },
		properties = { tag = tags[1][6] } },

	{ rule = { name="Steam" },
		properties = { tag = tags[1][7], floating = true },
		callback = awful.placement.centered },
	{ rule = { class="Steam" },
		properties = { tag = tags[1][7], floating = true },
		callback = awful.placement.centered },
	{ rule = { class="uoc" },
		properties = { tag = tags[1][7], floating = false },
		callback = awful.placement.centered },
    { rule = { class = "steelstorm64" },
		properties = { tag = tags[1][7], },
		callback = awful.placement.centered },
    { rule = { class = "net-minecraft-LauncherFrame" },
		properties = { tag = tags[1][7] } },
	{ rule = { class="Dredmor-amd64" },
		properties = { tag = tags[1][7], },
		callback = awful.placement.centered },
	{ rule = { class="SuperMeatBoy-amd64" },
		properties = { tag = tags[1][7], },
		callback = awful.placement.centered },
	{ rule = { class="Torchlight.bin.x86_64" },
		properties = { tag = tags[1][7], },
		callback = awful.placement.centered },
	{ rule = { class="Hedgewars" },
		properties = { tag = tags[1][7], },
		callback = awful.placement.centered },
	{ rule = { class="FTL" },
		properties = { tag = tags[1][7], },
		callback = awful.placement.centered },

	{ rule = { class="Wine" },
		properties = { tag = tags[1][7], floating = true, },
		callback = awful.placement.centered },
	{ rule = { class="Closure.bin.x86" },
		properties = { tag = tags[1][7], floating = true, },
		callback = awful.placement.centered },
	{ rule = { class="eduke32" },
		properties = { tag = tags[1][7], floating = true, },
		callback = awful.placement.centered },
	{ rule = { class="zdoom" },
		properties = { tag = tags[1][7], floating = true, },
		callback = awful.placement.centered },
	{ rule = { class="chocolate-doom" },
		properties = { tag = tags[1][7], floating = true, },
		callback = awful.placement.centered },
	{ rule = { class="chocolate-heretic" },
		properties = { tag = tags[1][7], floating = true, },
		callback = awful.placement.centered },
	{ rule = { name="Neverwinter Nights Client" },
		properties = { tag = tags[1][7], floating = false, },
		callback = awful.placement.centered },
	{ rule = { class="binkplayer" },
		properties = { tag = tags[1][7], floating = true, },
		callback = awful.placement.centered },
	{ rule = { class="dosbox" },
		properties = { tag = tags[1][7], floating = true, },
		callback = awful.placement.centered },

    { rule = { class = "VirtualBox" },
		properties = { tag = tags[1][8] } },
    { rule = { class = "Vncviewer" },
		properties = { tag = tags[1][8] } },
    { rule = { class = "Wfica" },
		properties = { tag = tags[1][8] } },

	{ rule = { class = "Pidgin" },
		properties = { tag = tags[1][9], } },
    { rule = { class = "Transmission" },
		properties = { tag = tags[1][9] } },

	{ rule = { class="CMST - Connman System Tray" },
		properties = { floating = false, } },

}
