#!/usr/bin/env sh
show_usage() {
    cat << EOF
usage: jq-flatten [options]

    --delim     delimiter to use (default: .)
    --help      show help and exit
EOF
}

DELIM='.'
while true; do
    case "$1" in
        --delim)
            DELIM="$2"
            shift
            shift
            ;;
        --help)
            show_usage
            exit
            ;;
        *)
            break
            ;;
    esac
done

exec jq --arg delim "$DELIM" 'reduce (tostream|select(length==2)) as $i ({};
    .[[$i[0][]|tostring]|join($delim)] = $i[1]
    )' "$@"
