#!/bin/sh
MAX_ATTEMPTS=60
ATTEMPTS=$MAX_ATTEMPTS
while [ "${ATTEMPTS}" -gt 0 ]; do 
    START="$(date +%s)"
    foot --title tmux-scratchpad --app-id tmux-scratchpad -- zsh -ic 'tmux-attach'
    END="$(date +%s)"
    
    if [ "$((END - START))" -le 2 ]; then
        ATTEMPTS=$((ATTEMPTS - 1))
        echo 'warning: application exited too quicky' >&2
        sleep 1
    else
        ATTEMPTS=$MAX_ATTEMPTS
    fi
done
echo 'error: too many attempts' >&2
exit 1
