#!/usr/bin/env sh
export STEAM_COMPAT_DATA_PATH="$HOME/.steam/proton"
STEAMAPPS_COMMON=~/.steam/steam/steamapps/common
PROTON_BASE="$STEAMAPPS_COMMON/$(ls "$STEAMAPPS_COMMON" | grep '^Proton' | sort --version-sort | tail -n 1)"
PROTON_PREFIX="$STEAM_COMPAT_DATA_PATH/pfx"
mkdir -p "$STEAM_COMPAT_DATA_PATH"
show_help() {
    cat << EOF
usage: proton [--show-prefix] PROGRAM [ARG ...]
    --help          show help and exit
    --show-prefix   show proton prefix path and exit
    --version       show program's version and exit
EOF
}


case "$1" in
    --help)
        show_help
        exit
        ;;
    --show-prefix)
        echo "$PROTON_PREFIX"
        exit
        ;;
    --version)
        sed 's/.*\sproton-//' "$PROTON_BASE"/version
        exit
        ;;
    *)
        ;;
esac

if [ $# -eq 0 ]; then
    show_help >&2
    exit 1
fi

exec "$PROTON_BASE"/proton run "$@"
