#!/usr/bin/env sh
CACHE_FILE=~/.cache/rofi-3.runcache

rofi "$@"
ret=$?

history_data="$(cat "$CACHE_FILE")"
for cmd in ddg todo; do
    history_data="$(printf '%s' "$history_data" | awk -v cmd="$cmd" '{if ($2 != cmd) print $0}')"
done
printf '%s' "$history_data" | sort --reverse > "$CACHE_FILE"

exit $ret
