#!/usr/bin/env sh
options() {
    cat << EOF
closet-lights
desk-lamp
fan-light
fan-max
fan-off
fan-silent
dark
on
on-cool
studio-monitors-on
studio-monitors-off
EOF
}

fzf_menu() {
    fzf --black --prompt= --no-info --exact --no-sort --no-extended -i --layout=reverse
}


OPTION="$(options | fzf_menu)"
hass office-"$OPTION"
