#!/usr/bin/env sh
options() {
    cat << EOF
at-monitor-desk
at-tv-desk
fan-off
fan-max
fan-silent
dark
on
on-cool
studio-monitors-on
studio-monitors-off
EOF
}

OPTION="$(options | rofi -dmenu -p '' -i)"
if [ -n "$OPTION" ]; then
    hass office-"$OPTION"
fi
