#!/bin/sh
xrandr --output DP-3 --off --output DVI-I-0 --off --output HDMI-0 --off --output DP-5 --off --output DP-4 --primary --mode 1920x1200 --pos 0x0 --rotate normal --output DVI-I-1 --off --output DP-2 --mode 1920x1200 --pos 1920x0 --rotate right --output DP-1 --off --output DP-0 --off
