#!/bin/sh
xrandr \
    --output DP-0 --off \
    --output DP-1 --off \
    --output DP-2 --off \
    --output DP-3 --off \
    --output DP-4 --primary --mode 3440x1440 --pos 0x0 --rotate normal --refresh 120 \
    --output DP-5 --off \
    --output DVI-I-0 --off \
    --output DVI-I-1 --off \
    --output HDMI-0 --off
set-x-dpi 96
