#!/usr/bin/env sh
set -e

cd "${SYNCTHING_DIR}"/Notes

if [ -t 1 ]; then
    if [ -n "$1" ]; then
        mkdir -p "$(dirname "$1")"
        exec "${EDITOR}" "$1"
    else
        exec "${EDITOR}" misc.md
    fi
else
    if [ -n "$1" ]; then
        echo "$(pwd)/$1"
    else
        pwd
    fi
fi
