#!/usr/bin/env sh
set -e

cd "${SYNCTHING_DIR}"/Notes

if [ "$1" = '-p' ]; then
    abspath="$(pwd)/$2"
    if [ -e "$abspath" ]; then
        echo "$abspath"
        exit
    else
        echo error: path "$abspath" not found >&2
        exit 1
    fi
fi

if [ -n "$1" ]; then
    mkdir -p "$(dirname "$1")"
    exec "${EDITOR}" "$1"
else
    exec "${EDITOR}" misc.md
fi
