#!/usr/bin/env sh
NOTES_DIR="${SYNCTHING_DIR}"/Notes
NOTES_FILE="$NOTES_DIR/$1"
if [ -t 1 ]; then
    mkdir -p "$(dirname "${NOTES_FILE}")"
    exec "${EDITOR}" "${NOTES_FILE}"
else
    echo "${NOTES_DIR}"
fi
