#!/usr/bin/env sh
set -e

TODO_FILE="${SYNCTHING_DIR}"/Notes/todo.txt

if [ "$(ls "${SYNCTHING_DIR}/Notes" | grep '^todo.*.txt' | wc -l)" -gt 1 ] ; then
    echo error: sync conflict detected >&2
    exit 1
fi

if [ "$1" = '-l' ]; then
   TOKENIZED=$(sed 's/ /\n/g' "${TODO_FILE}" | sort -u)
   echo "${TOKENIZED}" | grep '^@'
   echo
   echo "${TOKENIZED}" | grep '^+'
   exit
fi

if [ -z "$1" ]; then
    "${EDITOR}" "${TODO_FILE}"
else
    echo $(date +%Y-%m-%d) $@ >> "${TODO_FILE}"
fi
