#!/usr/bin/env sh
set -e

TODO_FILE="${SYNCTHING_DIR}"/Notes/todo.txt

if [ "$(ls "${SYNCTHING_DIR}/Notes" | grep '^todo.*.txt' | wc -l)" -gt 1 ] ; then
    echo error: sync conflict detected >&2
    exit 1
fi

if [ "$1" = '-l' ]; then
   TOKENIZED=$(sed 's/ /\n/g' "${TODO_FILE}" | sort -u)
   echo "${TOKENIZED}" | grep '^@'
   echo
   echo "${TOKENIZED}" | grep '^+'
   exit
fi

if [ "$1" = '-d' ]; then
    shift
    DUE="due:$(date -I)"
    data="$(grep "$DUE" ~/Syncthing/Notes/todo.txt | sed "s/$DUE//g" | sort)"
    if [ -t 1 ]; then
        color_opt=always
    else
        color_opt=never
    fi
    for filter in "$@"; do
        data="$(echo "$data" | grep --color="$color_opt" -i "$filter")"
    done
    echo "$data"
    exit
fi

if [ -z "$1" ]; then
    "${EDITOR}" "${TODO_FILE}"
else
    echo "$(date -I)" "$@" >> "${TODO_FILE}"
fi
