#!/usr/bin/env bash
set -e

TODO_FILE="${SYNCTHING_DIR}"/Notes/todo.txt

if [ -n "$(find "${SYNCTHING_DIR}/Notes" -maxdepth 1 -name 'todo.*.txt')" ] ; then
    echo error: sync conflict detected >&2
    exit 1
fi

if [[ $# -eq 1 && $1 == '-l' ]]; then
   TOKENIZED=$(sed 's/ /\n/g' "${TODO_FILE}" | sort -u)
   echo "${TOKENIZED}" | grep '^@'
   echo
   echo "${TOKENIZED}" | grep '^+'
   exit
fi

if [ -z "$1" ]; then
    "${EDITOR}" "${TODO_FILE}"
else
    echo $(date +%Y-%m-%d) $@ >> "${TODO_FILE}"
fi
