#!/usr/bin/env sh
set -e

DEST="$(date -I)_$(date +%s)".mkv

ALSA_DEVICE_NUM="$(arecord -l | grep 'Cx231xxAudio' | grep '^card ' | tr ':' ' ' | awk '{print $2}')"
if [ -z "$ALSA_DEVICE_NUM" ]; then
    echo 'error: cannot detected alsa device' >&2
    exit 1
fi
ALSA_DEVICE="hw:${ALSA_DEVICE_NUM}"

VIDEO_DEVICE="$(v4l2-ctl --list-devices | grep -A 3 '^Hauppauge USB Live 2' | grep '/dev/video' | awk '{print $1}')"
if [ -z "$VIDEO_DEVICE" ]; then
    echo 'error: cannot detected video device' >&2
    exit 1
fi

echo "Alsa device:  ${ALSA_DEVICE}" 
echo "Video device: ${VIDEO_DEVICE}" 

ffplay -f alsa -i "$ALSA_DEVICE" -nodisp 2> /dev/null &
ffplay -f video4linux2 -i "$VIDEO_DEVICE" 2> /dev/null
wait
