#!/usr/bin/env sh
if [ $# -ne 1 ]; then
    echo 'usage: SSH_HOST' >&2
fi
SSH_HOST="$1"
exec ssh -t "${SSH_HOST}" -- systemd-inhibit --who='ssh-tmux-attach' --what=idle --mode=block zsh -lic tmux-attach
