#!/usr/bin/env python3
import argparse
import json
import subprocess


def mkv_info(path):
    proc = subprocess.run(
        ['mkvmerge', '-J', path],
        stdout=subprocess.PIPE,
        check=True)
    return json.loads(proc.stdout)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('path')
    args = parser.parse_args()

    metadata = mkv_info(args.path)

    results = {
        'audio': [],
        'subtitles': [],
        'video': [],
    }
    for track in metadata['tracks']:
        results[track['type']].append(track)

    for track_type in ['video', 'audio', 'subtitles']:
        if tracks := results[track_type]:
            print(track_type)
            for track in tracks:
                if track['type'] == 'video':
                    line = [
                        track['id'],
                        track['codec'],
                        track['properties']['pixel_dimensions'],
                    ]
                elif track['type'] == 'audio':
                    line = [
                        track['id'],
                        track['properties'].get('language', 'und'),
                        track['codec'],
                    ]
                elif track['type'] == 'subtitles':
                    line = [
                        track['id'],
                        track['properties'].get('language', 'und'),
                        track['codec'],
                    ]
                info = '\t'.join(
                    str(value)
                    for value in line
                    if value is not None
                )
                print(f'  {info}')


if __name__ == '__main__':
    main()
