#!/usr/bin/env sh
cat > .envrc << EOF
poetry env info --path > .envrc

# export PIP_USER even though it's disabled in pip.conf.
# tox doesn't seem to respect the venv's pip.conf
export PIP_USER=0

# zsh-only. fixes virtualenv in PATH not taking precedence
command -v rehash >/dev/null && rehash
EOF
direnv allow .envrc
direnv reload
