#!/usr/bin/env sh
set -e

show_dialog() {
    zenity \
        --hide-header \
        --list \
        --text 'Max CPU %' \
        --column % \
        16 45 61 100
}

pct="$(show_dialog)"
if [ "$pct" -gt 61 ]; then
    no_turbo=0
else
    no_turbo=1
fi
sudo pstate-frequency -q -S -g powersave -m "$pct" -t "$no_turbo"
dunstify --replace 12385 "Max CPU" "${pct}%"
