#!/usr/bin/env sh
show_dialog() {
    zenity \
        --hide-header \
        --list \
        --text 'Max CPU %' \
        --column % \
        16 45 61 100
}

pct="$(show_dialog)"
if [ -n "$pct" ]; then
    if [ "$pct" -gt 61 ]; then
        no_turbo=0
    else
        no_turbo=1
    fi
    sudo pstate-frequency -q -S -g powersave -m "$pct" -t "$no_turbo"
fi
current_pct="$(sudo pstate-frequency -G -c | grep CPU_MAX | awk '{print $3}')"
dunstify --replace 12385 "Max CPU" "${current_pct}"
