#!/usr/bin/env sh
show_dialog() {
    zenity \
        --scale \
        --text 'Max CPU %' \
        --min-value 0 \
        --max-value 100 \
        --step 20 \
        --value 40
}

current_pct() {
    sudo pstate-frequency -G -c | grep CPU_MAX | awk '{print $3}' | sed 's/%//'
}

pct="$(show_dialog)"
if [ -n "$pct" ]; then
    sudo pstate-frequency -q -S -g powersave -m "$pct" -t 1
    if [ "$(current_pct)" -lt "$pct" ]; then
        sudo pstate-frequency -q -S -g powersave -m "$pct" -t 0
    fi
fi

dunstify \
    --hints=string:x-dunst-stack-tag:set-performance \
    "Max CPU" "$(current_pct)%"
