#!/usr/bin/env sh
set -eux
# name of domain, snapshot, and target disk device
thedomain="$1"
snapshotname="$2"
targetdisk="hda"

# look at '<disk>' types, should be just 'file' types
virsh dumpxml "$thedomain" | grep '<disk' -A5

# show block level devices and qcow2 paths (hda,hdb,..etc)
virsh domblklist "$thedomain"

# create snapshot in default pool location
# file name is $thedomain.$snapshotname
virsh snapshot-create-as "$thedomain" --name "$snapshotname" --disk-only

# list snapshot
virsh snapshot-list "$thedomain"
