#!/usr/bin/env sh
set -e

YELLOW='\033[1;33m'
RESET_COLOR='\033[0m'

log() {
    printf "%b> %s%b\n" "${YELLOW}" "$*" "${RESET_COLOR}"
}

# ensure git repo
git status > /dev/null

log Remote
output=''
for remote in $(git remote); do
    fetch_remote="$(git remote get-url "${remote}")"
    push_remote="$(git remote get-url --push "${remote}")"
    if [ "${fetch_remote}" = "${push_remote}" ]; then
        output="${output}${remote} ${fetch_remote}\n"
    else
        output="${output}${remote} ${fetch_remote} (fetch)\n"
        output="${output}${remote} ${push_remote} (push)\n"
    fi
done
echo "${output}" | column -t

echo

log All Branch
git branch -vv

stash="$(git stash list)"
if [ -n "$stash" ]; then
    echo
    log Stash
    echo "$stash"
fi

status="$(git -c color.status=always status --short)"
if [ -n "$status" ]; then
    echo
    log Changes
    echo "$status"
fi

