#!/usr/bin/env sh
set -e

REMOTE=upstream

has_upstream_remote() {
    git remote | grep -q "^${REMOTE}$"
}

if [ "$1" = '--help' ]; then
    cat << EOF
usage: git upstream [URL]

add and update upstream remote and branches
EOF
    exit
fi

if [ -n "$1" ]; then
    if has_upstream_remote; then
        git remote set-url "$REMOTE" -- "$1"
    else
        git remote add upstream -- "$1"
    fi
fi

if ! has_upstream_remote; then
    echo error: upstream remote is not set >&2
    exit 1
fi

git fetch "$REMOTE"

current_branch="$(git rev-parse --abbrev-ref HEAD)"
if [ "$current_branch" != master ]; then
    git stash --all --quiet
    git checkout master
    git branch -u "${REMOTE}/master"
    git rebase "${REMOTE}/master"
    git checkout "$current_branch"
    git stash pop --quiet
else
    git branch -u "${REMOTE}/master"
    git rebase "${REMOTE}/master"
fi
