#!/usr/bin/env sh
case $# in
    0)
        SEARCH_DIR="."
        ;;
    1)
        SEARCH_DIR="$1"
        ;;
    *)
        echo 'error: unknown arguments' >&2
        exit 1
esac

if command -v fd > /dev/null; then
    exec fd --base-directory "$SEARCH_DIR" -uu -t d '^\.git$' "$SEARCH_DIR" -X printf '%s\n' '{//}'
else
    exec find "$SEARCH_DIR" -type d -name .git -printf "%h\n";
fi
