#!/usr/bin/env sh
set -e

if [ "$1" = '-k' ]; then
    NO_CLEAN="1"
    shift
fi

if [ "$1" = '-v' ]; then
    VERBOSE="1"
    shift
fi

BASE_DIR=~/.local/git
REPO_URL="$1"
REPO_NAME="$(basename "$REPO_URL")"
REPO_NAME="${REPO_NAME%.git}"
REPO_DIR="$BASE_DIR/$REPO_NAME"

if [ -z "$REPO_URL" ]; then
    echo error: missing url >&2
    exit 1
fi


echo "$REPO_DIR"

_update() {
    if ! [ -d "$REPO_DIR" ]; then
        git clone "$REPO_URL" "$REPO_DIR"
    fi

    cd "$REPO_DIR"

    if [ -z "$NO_CLEAN" ]; then
        echo cleaning!
        git clean -xdf
    fi
    git checkout -q .
    git checkout -q master
    git pull
}

if [ -z "$VERBOSE" ]; then
    _update > /dev/null
else
    _update
fi
