#!/usr/bin/env sh
set -e

get_ssh_hostname() {
    awk -v target_host="$1" '
        tolower($1) == "host" {
            host = $2;
            next;
        }
        tolower($1) == "hostname" && host == target_host {
            printf "%s", $2;
        }' \
        ~/.ssh/config
}

if [ -n "$1" ]; then
    url="$1"
else
    for remote in upstream origin; do
        url="$(git remote get-url "$remote" 2> /dev/null || true)"
        if [ -n "$url" ]; then
            break
        fi
    done
    url=''
fi


if [ -z "$url" ]; then
    echo error: cannot determine remote 2> /dev/null
    exit 1
fi

git_path="${url#*:}"
git_host="${url%:*}"

ssh_hostname="$(get_ssh_hostname "$git_host")"
case "$(echo "$url" | tr '[:upper:]' '[:lower:]')" in
    https://*|http://*)
        url="${url}"
        ;;
    *@*:*)
        url="${url#*@}"
        git_path="${url#*:}"
        git_host="${url%:*}"
        url="http://${git_host}/${git_path}"
        ;;
    *)
        if [ -n "$ssh_hostname" ]; then
            url="https://${ssh_hostname}/${git_path}"
        else
            echo "error: cannot open \"${url}\"" >&2
            exit 1
        fi
esac

if [ -t 1 ] && [ -z "$SSH_TTY" ]; then
    open "$url"
else
    echo "$url"
fi
