#!/usr/bin/env sh
set -e
STAGED=
if [ "$1" = '--staged' ]; then
    STAGED=1
    shift
fi

if [ -z $1 ]; then
    if git status 2> /dev/null; then
        GIT_DIR='.'
    else
        echo ERROR: No git directory specified
        exit 1
    fi
else
    GIT_DIR="$1"
fi

cd "${GIT_DIR}"
git fetch
if [ "$(git rev-parse HEAD)" != "$(git rev-parse @{u})" ]; then
    git merge
fi

if [ "$(git status --porcelain | wc -l)" -gt 0 ]; then
    if [ -z "$STAGED" ]; then
        git add -A
    fi
    git commit -m "git-auto-update $(TZ=UTC date -Is)"
fi

branch=$(git rev-parse --abbrev-ref HEAD)
if [ "$(git log origin/$branch..$branch | wc -l)" -gt 0 ]; then
    git push
fi
