#!/usr/bin/env sh
set -e

REMOTE="${GIT_REMOTE:-origin}"
BRANCH="${GIT_BRANCH:-main}"
TAG="$1"

if [ $# -ne 1 ]; then
    echo 'usage: git-check-tag-is-pushed <TAG>' >&2
    exit 1
fi

local_ref="$(git show-ref --hash "$TAG")"
remote_ref="$(git ls-remote "$REMOTE" "$TAG" | cut -f1)"

if [ -z "$local_ref" ]; then
    echo 'error: local tag not found' >&2
    exit 1
elif [ -z "$remote_ref" ]; then
    echo 'error: remote tag not found' >&2
    exit 1
elif [ "$local_ref" != "$remote_ref" ]; then
    echo 'error: local tag ref does not match remote tag ref' >&2
    exit 1
fi

unpushed_commits="$(git rev-list "${REMOTE}/${BRANCH}..${TAG}")"
if [ -n "$unpushed_commits" ]; then
    echo 'error: unpushed commits' >&2
    exit 1
fi
