#!/usr/bin/env sh
export XDG_CURRENT_DESKTOP=sway

set -a
eval "$(/usr/lib/systemd/user-environment-generators/30-systemd-environment-d-generator)"
set +a

/usr/lib/gsd-xsettings &

if command -v syncthingtray > /dev/null; then
    syncthingtray --wait &
fi

if command -v mpd-notifier > /dev/null; then
    mpd-notifier --library ~/.config/mpd/library &
fi

exec sway
