#!/usr/bin/env sh
set -eu
usage() {
    echo 'usage: [--delay DELAY] SOURCE DEST'
}

DELAY=5
FRAMES=48

while [ $# -gt 0 ]; do
    case "$1" in
        --help)
            usage
            exit
            ;;
        --delay)
            DELAY="$2"
            shift
            shift
            ;;
        --frames)
            FRAMES="$2"
            shift
            shift
            ;;
        *)
            if [ $# -ne 2 ]; then
                usage >&2
                echo 'error: missing/unexpected arguments'
                exit 1
            fi
            SOURCE="$1"
            TARGET="$2"
            shift
            shift
    esac
done

magick "$SOURCE" -duplicate "$((FRAMES-1))" -distort SRT %[fx:t*360/n] -set delay "$DELAY" -loop 0 "$TARGET"
