#!/usr/bin/env python3
import argparse
import pathlib


def all_files(root):
    if root.is_dir():
        stack = [root]
        while stack:
            for path in stack.pop().iterdir():
                if path.is_dir():
                    stack.append(path)
                else:
                    yield path
    else:
        yield root


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("path", type=pathlib.Path)
    args = parser.parse_args()

    for path in all_files(args.path):
        if path.suffix.lower() != ".srt":
            continue
        data = path.read_bytes().decode("utf-8", "ignore")
        path.write_text(data)
        print(path)


if __name__ == "__main__":
    main()
