#!/usr/bin/env python3
import argparse
import pathlib
import subprocess
import tempfile


def split_flac(flac_path, cue_path):
    parent = cue_path.absolute().parent
    with tempfile.TemporaryDirectory(dir=parent, prefix=".shntool_split") as tmpdir:
        subprocess.run(
            [
                "shntool",
                "split",
                "-q",
                "-d",
                tmpdir,
                "-f",
                cue_path.name,
                "-o",
                "flac flac --best --verify --output-name split%f -",
                "-t",
                "%n",
                flac_path.name,
            ],
            cwd=parent,
            check=True,
        )
        for path in pathlib.Path(tmpdir).iterdir():
            path.rename(parent / path.name)
    flac_path.unlink()


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("flac", type=pathlib.Path)
    parser.add_argument("cue", type=pathlib.Path)
    args = parser.parse_args()

    split_flac(args.flac, args.cue)


if __name__ == "__main__":
    main()
