#!/usr/bin/env python3
import argparse
import contextlib
import datetime
import json
import pathlib
import shutil
import subprocess
import tempfile


@contextlib.contextmanager
def TempPath(**kwargs):
    """Wrapper around tempfile.NamedTemporaryFile which returns a path object

    Unlike tempfile.NamedTemporaryFile, the FileNotFoundError exception is not
    raised if the file is deleted before the context closes.

    :rtype: pathlib.Path
    """
    with tempfile.NamedTemporaryFile(**kwargs, delete=False) as tmp:
        temp_path = pathlib.Path(tmp.name)
        try:
            yield temp_path
        finally:
            try:
                temp_path.unlink()
            except FileNotFoundError:
                pass


def gifski(path, target, framerate="30", loops=1):
    with TempPath(
        dir=target.parent, prefix=".img-to-interpolated-video", suffix=target.suffix
    ) as tmptarget:
        subprocess.run(
            [
                "gifski",
                "--quiet",
                "--extra",
                "--fps",
                framerate,
                "--output",
                tmptarget,
                "--",
                *list(path.iterdir()),
            ],
            stdout=subprocess.DEVNULL,
            check=True,
        )
        tmptarget.rename(target)


def ffmpeg_merge(path, target, framerate="30", loops=1):
    with TempPath(
        dir=target.parent, prefix=".img-to-interpolated-video", suffix=target.suffix
    ) as tmptarget:
        subprocess.run(
            [
                "ffmpeg",
                "-y",
                "-stream_loop",
                str(loops),
                "-framerate",
                framerate,
                "-pattern_type",
                "glob",
                "-i",
                f"{path}/*.png",
                "-c:v",
                "libx264",
                "-preset",
                "slow",
                "-crf",
                "16",
                tmptarget,
            ],
            stderr=subprocess.DEVNULL,
            stdout=subprocess.DEVNULL,
            check=True,
        )
        tmptarget.rename(target)


def ffmpeg_frames_to_png(path, target, remove_duplicates=True):
    args = [
        "ffmpeg",
        "-i",
        path,
    ]
    if remove_duplicates:
        info = ffprobe(path)
        avg_frame_rate = None
        for stream in info:
            avg_frame_rate = stream.get("avg_frame_rate")
            if avg_frame_rate:
                x, y = avg_frame_rate.split("/")
                avg_frame_rate = int(x) / int(y)
        args.extend(
            [
                "-vsync",
                "0",
                "-vf",
                f"mpdecimate,setpts=N/{round(avg_frame_rate, 3)}/TB",
            ]
        )

    args.extend(
        [
            "-compression_level",
            "0",
            f"{target}/%08d.png",
        ]
    )
    subprocess.run(
        args, stderr=subprocess.DEVNULL, stdout=subprocess.DEVNULL, check=True
    )


def ffprobe(path):
    proc = subprocess.run(
        [
            "ffprobe",
            "-v",
            "error",
            "-show_streams",
            "-print_format",
            "json",
            "--",
            path,
        ],
        stderr=subprocess.DEVNULL,
        stdout=subprocess.PIPE,
        check=True,
    )
    return json.loads(proc.stdout)["streams"]


def rife(source, target, model=None, num_passes=1):
    args = ["rife", "--num-passes", str(num_passes)]
    if model is not None:
        args.extend(["--model", model])
    args.extend(["--", source, target])
    subprocess.run(args, check=True)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("-o", "--output", type=pathlib.Path)
    parser.add_argument(
        "-l",
        "--loops",
        type=int,
        metavar="NUM",
        default=3,
        help="(default %(default)s)",
    )
    parser.add_argument(
        "-r",
        "--rife-iterations",
        type=int,
        metavar="NUM",
        default=0,
        help="(default %(default)s)",
    )
    parser.add_argument("--rife-model")
    parser.add_argument(
        "--fps", default="30", metavar="FPS", help="(default %(default)s)"
    )
    parser.add_argument(
        "-m", "--mode", choices=["bounce", "cycle", "oneshot"], default="oneshot"
    )
    parser.add_argument("source", type=pathlib.Path)
    parser.add_argument("-f", "--format", default="mp4", choices=["gif", "mp4", "png"])
    args = parser.parse_args()

    output = args.output
    if output is None:
        name = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
        if args.format == "mp4":
            name += ".mp4"
        elif args.format == "gif":
            name += ".gif"
        output = pathlib.Path(name)

    with contextlib.ExitStack() as exitstack:
        if args.source.is_file():
            source = pathlib.Path(
                exitstack.enter_context(tempfile.TemporaryDirectory())
            )
            ffmpeg_frames_to_png(args.source, source)
        elif args.source.is_dir():
            source = args.source
        else:
            raise FileNotFoundError

        tmpdir = exitstack.enter_context(tempfile.TemporaryDirectory(dir=source.parent))
        tmpdir = pathlib.Path(tmpdir)
        sources = sorted(list(source.iterdir()))

        new = [*sources]
        match args.mode:
            case "cycle":
                new.append(sources[0])

        for i, p in enumerate(new):
            shutil.copy(p, tmpdir / f"{i:032d}.png")

        if args.rife_iterations:
            print("Running rife")
            tmpdir2 = exitstack.enter_context(
                tempfile.TemporaryDirectory(dir=source.parent)
            )
            tmpdir2 = pathlib.Path(tmpdir2)
            rife(
                tmpdir, tmpdir2, model=args.rife_model, num_passes=args.rife_iterations
            )
            shutil.rmtree(tmpdir)
            shutil.move(tmpdir2, tmpdir)

        sources = sorted(list(tmpdir.iterdir()))
        match args.mode:
            case "bounce":
                sources = [*sources, *reversed(sources[1:-1])]
                wz = len(str(len(sources)))

                tmpdir2 = exitstack.enter_context(
                    tempfile.TemporaryDirectory(dir=source.parent)
                )
                tmpdir2 = pathlib.Path(tmpdir2)

                for i, path in enumerate(sources):
                    shutil.copy(path, tmpdir2 / (str(i).zfill(wz) + ".png"))
                shutil.rmtree(tmpdir)
                shutil.move(tmpdir2, tmpdir)
            case "cycle":
                sources[-1].unlink()

        match args.format:
            case "mp4":
                print("Rendering video")
                ffmpeg_merge(
                    tmpdir,
                    output,
                    framerate=args.fps,
                    loops=args.loops,
                )
            case "gif":
                print("Rendering gif")
                gifski(
                    tmpdir,
                    output,
                    framerate=args.fps,
                )
            case "png":
                shutil.copytree(tmpdir, output)
            case _:
                raise RuntimeError
        print(output)


if __name__ == "__main__":
    main()
