#!/usr/bin/env python3
import argparse
import asyncio
import io
import os
import pathlib

import async_executor
import httpx
import PIL.Image
import tqdm.asyncio
import yarl

SEARCH_URL = yarl.URL('https://itunes.apple.com/search')
BASE_URL = yarl.URL('https://a5.mzstatic.com/us/r1000/0/')

CLIENT = httpx.AsyncClient()

# maximum number i've personally seen work
DEFAULT_LIMIT = 57

# does the stdlib define this anywhere?
PATH_LENGTH_MAX = 255


async def get_itunes_art(*terms, country='us', entity='album', limit=None):
    query = {
        'country': country,
        'entity': entity,
        'term': ' '.join(terms),
    }
    if limit:
        limit = int(limit)
        query['limit'] = limit

    url = SEARCH_URL.with_query(query)
    response = await CLIENT.get(str(url))
    response.raise_for_status()

    results = response.json()
    if results['resultCount'] == 0:
        raise KeyError
    if limit and results['resultCount'] == limit:
        raise NotImplementedError('limit too low')

    for result in results['results']:
        thumb_url = result['artworkUrl100']
        url = BASE_URL
        for part in thumb_url.split('/')[5:-1]:
            url = url / part
        result['artworkUrl'] = str(url)

    return results['results']


async def download_image(url):
    response = await CLIENT.get(str(url))
    response.raise_for_status()
    data = response.read()

    image = PIL.Image.open(io.BytesIO(data))
    image.verify()
    if image.format == 'TIFF':
        data = await convert_to_png(data)
    return data


def get_suffix(data):
    image = PIL.Image.open(io.BytesIO(data))
    match image.format:
        case 'JPEG':
            return '.jpg'
        case 'PNG':
            return '.png'
        case _:
            raise ValueError(image.format)


def build_image_path(name, suffix):
    name = name.replace(os.sep, '').strip()
    if not name:
        raise ValueError()
    iteration = 0
    while True:
        path = pathlib.Path(f'itunes_artwork_({name}){"_"*iteration}{suffix}')
        if len(path.name) > PATH_LENGTH_MAX:
            suffix = path.suffix
            name = path.name[0:PATH_LENGTH_MAX-len(suffix)]
            path = path.with_name(name + suffix)
        if not path.exists():
            break
        iteration += 1
    return path


async def convert_to_png(data):
    # use imagemagick instead of Pillow as Pillow's TIFF support doesn't
    # work without special compile flags
    proc = await asyncio.create_subprocess_exec(
        'convert', '-', 'png:-',
        stdin=asyncio.subprocess.PIPE,
        stdout=asyncio.subprocess.PIPE,
    )
    stdout, _ = await proc.communicate(data)
    if proc.returncode != 0:
        raise RuntimeError
    return stdout


async def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--limit', type=int, default=DEFAULT_LIMIT)
    parser.add_argument('terms', nargs='+')
    args = parser.parse_args()

    executor = async_executor.AsyncExecutor()
    task_names = {}
    for result in await get_itunes_art(*args.terms, limit=args.limit):
        name = '{} - {}'.format(
            result['artistName'],
            result['collectionName'])
        task = executor.submit(download_image, result['artworkUrl'])
        task_names[task] = name

    async for task in tqdm.asyncio.tqdm(executor):
        name = task_names[task]
        try:
            data = task.result()
        except Exception as e:
            print(e)
            continue

        suffix = get_suffix(data)
        path = build_image_path(name, suffix)
        path.write_bytes(data)


if __name__ == '__main__':
    asyncio.run(main())
