#!/usr/bin/env sh
set -e
FILE="$1"

tracks() {
    mkvinfo-json --type subtitle "$FILE" | jq -r '.[] | select(.language |  IN(null, "und", "eng")) | .number - 1 | tostring | . + ":subtitle_" + .'
}

mkvextract "$FILE" tracks $(tracks)
