#!/usr/bin/env python3
import argparse
import collections
import json
import pathlib

import enzyme


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('path', type=pathlib.Path)
    parser.add_argument('--type', choices=['audio', 'subtitle', 'video'])
    args = parser.parse_args()

    with open(args.path, 'rb') as f:
        metadata = enzyme.MKV(f).to_dict()

    filtered = collections.defaultdict(list)
    for key in ('audio_tracks', 'subtitle_tracks', 'video_tracks'):
        for track in metadata[key]:
            filtered[key.split('_')[0]].append({
                'language': track.get('language'),
                'number': track['number']
            })

    filtered = {
        key: sorted(values, key=lambda x: x['number'])
        for key, values in filtered.items()
    }

    if args.type:
        filtered = filtered[args.type]

    print(
        json.dumps(
            filtered,
            indent=2,
            sort_keys=True
        )
    )


if __name__ == '__main__':
    main()
