#!/usr/bin/env python3
import argparse
import os
import pathlib
import subprocess

import chardet
import mutagen.flac
import mutagen.mp3

AUDIO_EXT = ('.flac', '.mp3')
FLAC_EXT = '.flac'

IMAGE_EXT = ('.jpg', '.png')
IMAGE_PREFIX = 'cover'

CUE_EXT = ('.cue')

RENAME_MAP = {'.jpeg': '.jpg'}

EXPECTED_TAGS = (
    'albumartist',
    'album',
    'artist',
    'date',
    'genre',
    'tracknumber'
)


MUTAGEN_CLASS = {
    '.flac': mutagen.flac.FLAC,
    '.mp3': mutagen.mp3.EasyMP3
}


def cue_track_count(path):
    try:
        with open(path) as f:
            lines = f.readlines()
    except UnicodeDecodeError:
        detector = chardet.UniversalDetector()
        with open(path, 'rb') as f:
            data = f.read()
            detector.feed(data)
        detector.close()
        lines = data.decode(detector.result['encoding']).split('\n')
        with open(path, 'w') as f:
            f.write('\n'.join(lines))
    return len([l for l in lines if l.strip().startswith('TRACK ')])


def split_flac(flac_path, cue_path):
    print(f'Splitting {flac_path}')
    subprocess.run(
        ['shntool', 'split', '-f', cue_path.name, '-o',
         'flac flac --output-name=split%f -', '-t', '%n', flac_path.name],
        cwd=cue_path.parent,
        stderr=subprocess.DEVNULL,
        check=True
    )
    flac_path.unlink()


def check_cue_files(root_path):
    paths = [p for p in root_path.iterdir() if p.is_file()]
    flac_files = [p for p in paths if p.suffix == FLAC_EXT]
    if not flac_files:
        return

    cue_files = [p for p in paths if p.suffix in CUE_EXT]

    if len(cue_files) > 1:
        print(f'Multiple .cue files: {root_path}')
    elif len(cue_files) == len(flac_files) == 1:
        cue_file = cue_files[0]
        num_tracks = cue_track_count(cue_file)
        if num_tracks == 0:
            print(f'Bad cue file: {cue_file}')
        elif num_tracks != 1:
            split_flac(flac_files[0], cue_file)


def organize_images(root_path):
    paths = [p for p in root_path.iterdir() if p.is_file()]
    audio_files = [p for p in paths if p.suffix in AUDIO_EXT]
    if not audio_files:
        return

    images = [p for p in paths if p.suffix in IMAGE_EXT]
    if len(images) == 1:
        image = images[0]
        image.rename(
            pathlib.Path(image.parent, IMAGE_PREFIX + image.suffix)
        )
    elif len(images) > 1:
        print(f'Multiple images: {root_path}')
    else:
        print(f'No images: {root_path}')


def check_tags(path):
    mutagen_class = MUTAGEN_CLASS.get(path.suffix)
    if mutagen_class:
        metadata = mutagen_class(path)
        for tag in EXPECTED_TAGS:
            try:
                metadata[tag]
            except KeyError:
                print(f'File {path} missing "{tag}"')


def rename_extensions(path):
    for f in {p for p in path.iterdir() if p.is_file()}:
        suffix = f.suffix.lower()
        suffix = RENAME_MAP.get(suffix, suffix)
        new_f = pathlib.Path(f.parent, f.stem + suffix)
        if f != new_f:
            print(f'Renaming "{f}" to "{new_f}"')
            f.rename(new_f)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('directory')
    parser.add_argument('-t', '--check-tags', action='store_const', const=True)
    args = parser.parse_args()

    music_dir = pathlib.Path(args.directory)

    for root, dirs, files in os.walk(music_dir):
        root_path = pathlib.Path(root)

        rename_extensions(root_path)
        organize_images(root_path)
        check_cue_files(root_path)

        if args.check_tags:
            for path in {p for p in root_path.iterdir() if p.is_file()}:
                check_tags(path)


if __name__ == '__main__':
    main()
