#!/usr/bin/env sh
set -e
for f in "$@"; do
    OUTDIR="${f}.tmp"
    7z x "$f" -o"${OUTDIR}"
    image_optim -r "${OUTDIR}"
    mv "$f" "$f".bak
    7z a -mm=Deflate -mfb=258 -mpass=15 "$f".zip "$OUTDIR"/.
    mv "$f".zip "$f"
    rm -rf "$OUTDIR"
done
