#!/bin/bash
for f in "$@"; do
    TEMP_DIR=$(mktemp -d)
    trap "rm -rf "${TEMP_DIR}"" EXIT
    7z x "$f" "-o"${TEMP_DIR}""
    image_optim -r "${TEMP_DIR}"
    mv "$f" "$f".bak
    7z a -mm=Deflate -mfb=258 -mpass=15 "$f".zip "${TEMP_DIR}"/.
    mv "$f".zip "$f"
    rm -rf $TEMP_DIR
done
