#!/usr/bin/env python3
import argparse
import asyncio
import contextlib
import logging
import os
import pathlib
import tempfile

import mutagen

LOGGER = logging.getLogger('reencode-lossless')


def copy_tags(source, target):
    metadata_source = mutagen.File(source)
    metadata_target = mutagen.File(target)
    for key, value in metadata_source.items():
        if isinstance(value, mutagen.apev2.APETextValue):
            value = str(value)
        metadata_target[key] = value
    metadata_target.save()


async def decode_ape(source, fd):
    proc = await asyncio.create_subprocess_exec(
        'mac', source, '-', '-d',
        stderr=asyncio.subprocess.DEVNULL,
        stdout=fd)

    async def result():
        await proc.wait()
        if proc.returncode != 0:
            raise DecodeError(source)
    return result()


async def decode_wv(source, fd):
    proc = await asyncio.create_subprocess_exec(
        'wvunpack', '-q', source, '-o', '-',
        stdout=fd)

    async def result():
        await proc.wait()
        if proc.returncode != 0:
            raise DecodeError(source)
    return result()


async def decode_flac(source, fd):
    proc = await asyncio.create_subprocess_exec(
        'flac', '-csd', source,
        stderr=asyncio.subprocess.DEVNULL,
        stdout=fd)

    async def result():
        await proc.wait()
        if proc.returncode != 0:
            raise DecodeError(source)
    return result()


async def decode_wav(source, fd):
    proc = await asyncio.create_subprocess_exec(
        'cat', source,
        stdout=fd)

    async def result():
        await proc.wait()
        if proc.returncode != 0:
            raise DecodeError(source)
    return result()


@contextlib.contextmanager
def TempPath(**kwargs):
    """Wrapper around tempfile.NamedTemporaryFile which returns a path object

    Unlike tempfile.NamedTemporaryFile, the FileNotFoundError exception is not
    raised if the file is deleted before the context closes.

    :rtype: pathlib.Path
    """
    with tempfile.NamedTemporaryFile(**kwargs, delete=False) as tmp:
        temp_path = pathlib.Path(tmp.name)
        try:
            yield temp_path
        finally:
            try:
                temp_path.unlink()
            except FileNotFoundError:
                pass


async def encode_flac(fd, dest):
    proc = await asyncio.create_subprocess_exec(
        'flac', '--silent', '--best', '--verify', '--force',
        '--output-name', dest, '-',
        stdin=fd,
        stderr=asyncio.subprocess.DEVNULL,
    )

    async def result():
        await proc.wait()
        if proc.returncode != 0:
            raise EncodeError()
    return result()


class DecodeError(Exception):
    """Raised when an error occurs while decoding audio"""


class EncodeError(Exception):
    """Raised when an error occurs while encoding audio"""


async def reencode(source):
    suffix = source.suffix.lower()

    decode_contexts = {
        '.flac': decode_flac,
        '.ape': decode_ape,
        '.wv': decode_wv,
        '.wav': decode_wav
    }

    read, write = os.pipe()

    decode = await decode_contexts[suffix](source, write)
    os.close(write)

    before = source.stat().st_size

    with TempPath(dir=source.parent, suffix='.flac') as tmp:
        encode = await encode_flac(read, tmp)
        os.close(read)

        await asyncio.gather(decode, encode)

        try:
            copy_tags(source, tmp)
        except Exception:
            pass
        source.unlink()
        dest = source.with_suffix('.flac')
        tmp.rename(dest)

    after = dest.stat().st_size
    return source, before, after


def all_files(root):
    files = []
    stack = [root]
    while stack:
        for path in stack.pop().iterdir():
            if path.is_file():
                files.append(path)
            elif path.is_dir():
                stack.append(path)
    return files


async def run(executor, num_items):
    errors = []

    size_diff_printer = SizeDiffPrinter(num_items)

    async for result in executor.as_completed():
        try:
            source, before, after = result.result()
        except Exception as e:
            LOGGER.exception(e)
            errors.append(str(e))
            continue

        size_diff_printer.print(before, after, source)
    size_diff_printer.print_total()

    for error in sorted(errors):
        LOGGER.error('Error %s', error)


class AsyncExecutor:
    def __init__(self, max_pending=None):
        self._max_pending = \
            os.cpu_count() if max_pending is None else max_pending
        self._queued = []
        self._pending = set()

    def submit(self, func, *args, **kwargs):
        self._queued.append((func, args, kwargs))
        try:
            asyncio.get_running_loop()
        except RuntimeError:
            pass
        else:
            self._fill()

    async def as_completed(self):
        while self._queued or self._pending:
            self._fill()

            done, self._pending = await asyncio.wait(
                self._pending, return_when=asyncio.FIRST_COMPLETED)

            for result in done:
                yield result

    def _fill(self):
        for _ in range(self._max_pending - len(self._pending)):
            if not self._queued:
                return
            func, args, kwargs = self._queued.pop()
            self._pending.add(asyncio.create_task(func(*args, **kwargs)))


class SizeDiffPrinter:
    def __init__(self, num_items):
        self._before_total = 0
        self._after_total = 0
        self._num_items = num_items
        self._num_printed = 0
        self._printed = False

    @staticmethod
    def format_diff(before, after):
        diff = ((before - after) / before) * 100
        if diff:
            diff = '{:.2f}'.format(diff)
            if not float(diff):
                diff = f'<{diff}'
        return diff

    @staticmethod
    def sizeof_fmt(num):
        for unit in ['B', 'KB', 'MB', 'GB', 'TB', 'PB']:
            if abs(num) < 1024.0:
                break
            num /= 1024.0
        return f'{num:.1f}{unit}'

    def print(self, before, after, name):
        self._num_printed += 1
        self._before_total += before
        self._after_total += after
        diff = self.format_diff(before, after)

        s = f'{diff:>6}%' if diff else 7 * '-'
        num_printed = str(self._num_printed).rjust(len(str(self._num_items)))
        print(f'({num_printed}/{self._num_items})\t{s}\t{name}')

    def print_total(self):
        if self._num_printed:
            if diff := self.format_diff(self._before_total, self._after_total):
                fmt = self.sizeof_fmt(self._before_total - self._after_total)
                print(f'Total: {diff}% ({fmt})')
            else:
                print('Total: -')


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('-n', dest='numprocs', metavar='NUMPROCS', type=int)
    parser.add_argument('path', type=pathlib.Path, nargs='+')
    args = parser.parse_args()

    logging.basicConfig(
        format='%(levelname)s %(message)s',
        level=logging.INFO)

    paths = set()
    for path in args.path:
        if path.is_dir():
            paths.update(all_files(path))
        else:
            paths.add(path)

    executor = AsyncExecutor(max_pending=args.numprocs)
    num_items = 0
    for path in paths:
        if path.suffix.lower() in ('.flac', '.ape', '.wav', '.wv'):
            num_items += 1
            executor.submit(reencode, path)

    asyncio.run(run(executor, num_items))


if __name__ == '__main__':
    main()
