#!/usr/bin/env python3
import argparse
import struct


def fix_ntfs_partition(partition_path, start_offset):
    with open(partition_path, "rb+") as handle:
        handle.seek(0x1C)
        handle.write(struct.pack("<I", start_offset))


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("partition")
    parser.add_argument(
        "start_offset", type=int, help="found by running `fdisk -l DEVICE`"
    )
    args = parser.parse_args()

    fix_ntfs_partition(args.partition, args.start_offset)


if __name__ == "__main__":
    main()
