#!/usr/bin/env python3
import argparse


def fix_ntfs_partition(partition_path, start_offset):
    hex_offset = hex(start_offset)[2:].zfill(8)
    value = ''.join(
        hex_offset[v]
        for v in [6, 7, 4, 5, 2, 3, 0, 1]
    )
    with open(partition_path, 'rb+') as handle:
        handle.seek(0x1c)
        handle.write(bytes.fromhex(value))


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('partition')
    parser.add_argument('start_offset', type=int,
                        help='found by running `fdisk -l DEVICE`')
    args = parser.parse_args()

    fix_ntfs_partition(args.partition, args.start_offset)


if __name__ == '__main__':
    main()
