#!/usr/bin/env sh
find_devices() {
    for device in $(find /sys/class/video4linux/ -maxdepth 1 -type l -printf "%P\n" | sort); do
        echo "/dev/${device}"
        cat "/sys/class/video4linux/${device}/name"
    done
}
device="$(find_devices | zenity --list --column Device --column Name --hide-column 1)"
if [ -n "$device" ]; then
    mpv "$device" --profile=low-latency --untimed
fi
