#!/usr/bin/env sh
cleanup() {
    rm -f "${TEMP_FILE}"
}

trap cleanup EXIT
TEMP_FILE="$(mktemp --suffix='.m3u')"
PLAYDIR="$1"
if [ -z "$PLAYDIR" ]; then
    PLAYDIR="$(pwd)"
fi
cd "$PLAYDIR"
fd -t f -x realpath | sort > "$TEMP_FILE"
exec mpv "$TEMP_FILE"
