#!/usr/bin/env sh
set -e

export PIP_REQUIRE_VIRTUALENV=0

if ! [ -x "$(command -v pip)" ]; then
    python -m ensurepip --user --default-pip
fi

if [ "$(pip list | grep -e '^pip ' -e '^setuptools ' -e '^wheel ' | wc -l)" != '3' ]; then
    pip install --user --upgrade --force-reinstall pip setuptools wheel
fi

ood_packages="$(pip list --outdated --format=freeze)"
if [ -n "${ood_packages}" ]; then
    pip install --user --upgrade $(echo "${ood_packages}" | cut -d = -f 1)
fi
