#!/usr/bin/env python3
import subprocess
import sys

import packaging.version

proc = subprocess.run(
    ['pip', 'index', 'versions', '--ignore-requires-python', *sys.argv[1:]],
    stdout=subprocess.PIPE,
    stderr=subprocess.DEVNULL,
    check=True)

for line in proc.stdout.decode().splitlines():
    new_line = line.removeprefix('Available versions: ')
    if new_line != line:
        versions = [
            packaging.version.parse(v)
            for v in new_line.split(', ')
        ]
        break

for version in sorted(versions):
    print(version)
