#!/usr/bin/env python3
import argparse
import subprocess


def pip_index_versions(package):
    proc = subprocess.run(
        ['pip', 'index', 'versions', '--ignore-requires-python', package],
        stdout=subprocess.PIPE,
        stderr=subprocess.DEVNULL,
        check=True)

    for line in proc.stdout.decode().splitlines():
        new_line = line.removeprefix('Available versions: ')
        if new_line != line:
            return new_line.split(', ')
    raise RuntimeError


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('-a', '--all', action='store_true')
    parser.add_argument('package')
    args = parser.parse_args()

    # seems to be sorted newest to oldest
    versions = pip_index_versions(args.package)
    if args.all:
        for v in reversed(versions):
            print(v)
    else:
        print(versions[0])


if __name__ == '__main__':
    main()
